process.env.ASHUB_TEST_ROOT ||= require('path').resolve(__dirname,'..');
const {env,Res,req,Bridge,assert,ts,vm,fs,path,root}=require('./harness.cjs');
const {ui,El,signal}=require('./ui-harness.cjs');const {EventEmitter}=require('events');
const tick=()=>new Promise(r=>setImmediate(r));const findings=[];
function ast(file){return ts.createSourceFile(file,fs.readFileSync(path.join(root,file),'utf8'),ts.ScriptTarget.Latest,true)}
function find(sf,p){let out;function walk(n){if(!out&&p(n))out=n;if(!out)ts.forEachChild(n,walk)}walk(sf);assert(out,'AST missing');return out;}
function variable(file,name,ctx){const sf=ast(file),n=find(sf,n=>ts.isVariableDeclaration(n)&&n.name?.text===name);return vm.runInContext('('+n.initializer.getText(sf)+')',ctx)}
function method(file,name,ctx){const sf=ast(file),n=find(sf,n=>ts.isMethodDeclaration(n)&&n.name?.text===name);return vm.runInContext(ts.transpileModule('({'+n.getText(sf)+'})['+JSON.stringify(name)+']',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx)}
function callback(file,expression,event,ctx){const sf=ast(file),n=find(sf,n=>ts.isCallExpression(n)&&n.expression.getText(sf)===expression&&n.arguments[0]?.text===event);return vm.runInContext(ts.transpileModule('('+n.arguments[1].getText(sf)+')',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx)}
function hub(e){return e.load('src/hub.ts','export const audit={startHub,createSession,closeSession,forkEndpoint,rewindContext,saveSessionMeta,archiveSession,unarchiveSession,shutdownHub,_flushBuf,persistReplayFile,routeEvent,submit,dropContext,openSseMulti,getContext,setCwdEndpoint,updateConfig,setAutoApprove,uploadImage,serveUpload,readBody,updateTitle,flushPtyBuffer,setSubagentModel,setSubagentBudget,loadArchivedSessions,listSessions,restoreSessions,rewindToTurn,execCommand,tagLastQueryFrame,setSessionTitle,_writeLocks};').audit}
async function create(extra={}){const e=env(extra),h=hub(e),ss=new Map(),s=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir);return{e,h,ss,s}}
const frame=f=>JSON.parse(f.split('data: ')[1]);
async function check(id,fn){try{const detail=await fn();findings.push({id,passed:true,detail});console.log('PASS',id,JSON.stringify(detail))}catch(e){findings.push({id,passed:false,error:e.stack});console.log('FAIL',id,e.stack)}}
function acp(){const calls=[],child=new EventEmitter();child.stdout=new EventEmitter();child.stdout.setEncoding=()=>{};child.kill=()=>{};child.stdin=Object.assign(new EventEmitter(),{writable:true,end(){},write:raw=>{const m=JSON.parse(raw);calls.push(m);if(m.method==='initialize'||m.method==='session/new'||m.method==='session/load'||m.method==='session/prompt')queueMicrotask(()=>child.stdout.emit('data',JSON.stringify({jsonrpc:'2.0',id:m.id,result:m.method==='initialize'?{protocolVersion:1,agentCapabilities:{loadSession:true}}:m.method==='session/new'?{sessionId:'remote'}:{stopReason:'end_turn'}})+'\n'));}});const e=env({modules:{'node:child_process':{spawn:()=>child}}}),A=e.load('src/bridges/acp.ts').AcpBridge;return{e,A,calls,child}}

async function revision(h,s){const r=new Res();await h.getContext(r,s);return JSON.parse(r.body).revision}
async function reload(h,s,ss,e){const r=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir,{id:s.id,title:'saved',startedAt:1,replay:[]});await r._ensureBridge();return r}
const watchdog=setTimeout(()=>{console.error('TIMEOUT');process.exit(1)},30000);
(async()=>{
for(const variant of ['torn','newline'])await check('V01 failed '+variant+' repair refuses writes and recovers on retry',async()=>{
 let fail=false;const real=require('fs'),e=env({modules:{'node:fs':{...real,truncateSync:(...a)=>{if(fail)throw Error('EACCES');return real.truncateSync(...a)},appendFileSync:(...a)=>{if(fail)throw Error('EACCES');return real.appendFileSync(...a)}}}}),Store=e.load('src/history/session-store.ts').SessionStore,file=path.join(e.dir,'tree.jsonl'),s=new Store(file,{create:{cwd:e.dir,sessionId:'aaaaaa'}});await s.appendMessages([{role:'user',content:'first'}]);if(variant==='torn')fs.appendFileSync(file,'{"type":"message","id":');else fs.writeFileSync(file,fs.readFileSync(file,'utf8').trimEnd());const before=fs.readFileSync(file,'utf8');fail=true;let error;try{new Store(file)}catch(err){error=err}assert(error&&fs.readFileSync(file,'utf8')===before,'unsafe history opened or changed');fail=false;const restored=new Store(file);await restored.appendMessages([{role:'assistant',content:'second'}]);assert(new Store(file).buildMessages().length===2,'recovered append lost');
});
await check('V02 failed rename retry persists explicit title',async()=>{
 let fail=false;const real=require('fs'),{e,h,s}=await create({modules:{'node:fs':{...real,promises:{...real.promises,writeFile:async(file,...args)=>{if(fail&&String(file).endsWith('.meta.json.tmp'))throw Error('ENOSPC');return real.promises.writeFile(file,...args)}}}}});fail=true;let error;try{await h.updateTitle(req({title:'renamed'}),new Res(),s)}catch(err){error=err}fail=false;const retry=new Res();await h.updateTitle(req({title:'renamed'}),retry,s);const disk=JSON.parse(fs.readFileSync(path.join(e.dir,'hub-sessions',s.id+'.meta.json')));assert(error&&retry.statusCode===200&&disk.title==='renamed'&&disk.userTitle==='renamed'&&!s._titleDirty,'rename retry not persisted');
});
await check('V02 concurrent manual titles beat queued automatic titles',async()=>{
 const {e,h,s}=await create();await Promise.all([h.updateTitle(req({title:'first'}),new Res(),s),h.updateTitle(req({title:'last'}),new Res(),s)]);await h.setSessionTitle(s,'obsolete automatic');const disk=JSON.parse(fs.readFileSync(path.join(e.dir,'hub-sessions',s.id+'.meta.json')));assert(disk.title==='last'&&s.title==='last'&&disk.userTitle==='last','title order wrong');await h.updateTitle(req({title:'last'}),new Res(),s);
});
await check('V03 shutdown cancels pending creation without waiting for ready',async()=>{
 const e=env(),h=hub(e),ss=new Map();let release,started,closed=0;const gate=new Promise(r=>release=r),ready=new Promise(r=>started=r);const p=h.createSession(ss,{makeBridge:o=>{const b=new Bridge(o);b.ready=async()=>{started();await gate};b.close=()=>closed++;return b}},e.dir).then(()=>null,err=>err);await ready;await h.shutdownHub(undefined,ss);assert(await p,'pending creation succeeded');assert(ss.size===0&&closed===1,'backend escaped shutdown');release();await tick();assert(ss.size===0&&closed===1,'late ready revived backend');assert(!fs.readdirSync(path.join(e.dir,'hub-sessions')).some(n=>n.endsWith('.meta.json')||n.endsWith('.jsonl')),'partial new session files remain');
});
await check('V03 aborted lifecycle blocks subsequent backend creation',async()=>{
 const e=env(),h=hub(e),ss=new Map(),a=new AbortController();a.abort();let calls=0,error;try{await h.createSession(ss,{signal:a.signal,makeBridge:o=>{calls++;return new Bridge(o)}},e.dir)}catch(err){error=err}assert(error&&calls===0&&ss.size===0,'aborted hub created backend');
});
for(const mode of ['index','turn'])await check('V04 delayed '+mode+' rewind rejects stale or missing revision',async()=>{
 const {h,s}=await create();s.bridge.messages=[{role:'user',content:'old 0'},{role:'assistant',content:'old 1'},{role:'user',content:'old 2'}];await s.capture.flush();const rev=await revision(h,s),leaf=s.store.getActiveLeaf();const ids=await s.store.appendMessages([{role:'user',content:'new 0'},{role:'assistant',content:'new 1'},{role:'user',content:'new 2'}],s.store.getRootId());s.store.setActiveLeaf(leaf);const fn=mode==='index'?h.rewindContext:h.rewindToTurn,body=mode==='index'?{toIndex:1}:{turn:1};const q=new EventEmitter(),r=new Res(),p=fn(q,r,s);await h.forkEndpoint(req({entryId:ids.at(-1)}),new Res(),s);q.emit('data',Buffer.from(JSON.stringify({...body,revision:rev})));q.emit('end');await p;assert(r.statusCode===409&&s.bridge.messages.length===3,'stale rewind changed branch');const missing=new Res();await fn(req(body),missing,s);assert(missing.statusCode===409&&s.bridge.messages.length===3,'missing revision allowed');const fresh=new Res();await fn(req({...body,revision:await revision(h,s)}),fresh,s);assert(fresh.statusCode===200&&s.bridge.messages.length===(mode==='index'?1:2),'fresh rewind rejected');
});
await check('V04 stable entry rewind remains supported without index revision',async()=>{
 const {h,s}=await create();s.bridge.messages=[{role:'user',content:'one'},{role:'assistant',content:'two'},{role:'user',content:'three'}];await s.capture.flush();const ids=s.store.buildBranchWithIds().entryIds,r=new Res();await h.rewindToTurn(req({entryId:ids[2]}),r,s);assert(r.statusCode===200&&s.bridge.messages.length===2,'stable rewind broken');
});
await check('V04 UI refuses unaddressed legacy message and submits stable entry only',async()=>{
 const u=ui(),calls=[];Object.assign(u.e.context,{t:x=>x,fetch:async(url,opts)=>{calls.push(JSON.parse(opts.body));return{ok:true,json:async()=>({ok:true})}}});const fn=variable('web/js/actions.js','rewindToTurn',u.e.context);let error;try{await fn({sid:'aaaaaa',turn:2})}catch(err){error=err}assert(error&&calls.length===0,'legacy turn posted without revision');await fn({sid:'aaaaaa',turn:2,entryId:'stable'});assert(calls.length===1&&calls[0].entryId==='stable'&&!('turn' in calls[0]),'stable entry missing');
});
await check('V05 legacy empty tree retains shell history through next save',async()=>{
 const {e,h,s,ss}=await create();s.store.setActiveLeaf(s.store.getRootId());h.routeEvent(s,{name:'shell:command-start',payload:{command:'echo valuable'}});h.routeEvent(s,{name:'shell:command-done',payload:{stdout:'valuable output'}});await h.shutdownHub(undefined,ss);const checkpoint=path.join(e.dir,'hub-sessions',s.id+'.replay-state.json');fs.rmSync(checkpoint);const restored=await reload(h,s,ss,e);assert(restored.replay.some(f=>f.includes('valuable output')),'shell history lost');assert(JSON.parse(fs.readFileSync(checkpoint)).leaf===restored.store.getActiveLeaf(),'legacy checkpoint not migrated');await h.updateTitle(req({title:'saved again'}),new Res(),restored);await h.shutdownHub(undefined,ss);assert(fs.readFileSync(path.join(e.dir,'hub-sessions',s.id+'.replay.jsonl'),'utf8').includes('valuable output'),'shell history overwritten');
});
for(const asyncFailure of [false,true])await check('V06 command '+(asyncFailure?'asynchronous':'synchronous')+' failure returns HTTP error and SSE error',async()=>{
 const {h,s}=await create();s.bridge.execCommand=()=>{if(asyncFailure)return Promise.reject(Error('disk full'));throw Error('disk full')};const r=new Res();await h.execCommand(req({name:'/sa-budget',args:'{"type":"implement","budgetTokens":123}'}),r,s);assert(r.statusCode===500&&r.body.includes('disk full'),'HTTP error swallowed');assert(s.replay.some(f=>f.includes('ui:error')&&f.includes('disk full')),'SSE error missing');
});
function modelUi(){const u=ui(),wrap=new El(),label=new El(),types=new El(),card=new El();card.dataset.type='implement';label.closest=()=>card;label.parentElement=wrap;types.querySelectorAll=q=>q==='.sa-model-label'?[label]:wrap.children;Object.assign(u.e.context,{saTypes:types,saModelSeq:0,modelRefreshSeq:0,_optionsSig:'',agentInfo:{provider:'test'},currentSessionId:()=> 'aaaaaa',toast(){},t:x=>x,escape:x=>x,ensureOverrideOption(){},fetchModelsCatalog:async()=>({providers:[]})});variable('web/js/subagent-panel.js','buildModelSelects',u.e.context)();return{u,select:wrap.children[0],refresh:variable('web/js/subagent-panel.js','refreshModelDropdowns',u.e.context)}}
await check('V07 old refresh cannot overwrite successful model selection',async()=>{
 const {u,select,refresh}=modelUi();let release,saved='old';const pending=new Promise(r=>release=r);u.e.context.fetch=async(url,opts)=>{if(opts?.method==='PUT'){saved=JSON.parse(opts.body).model;return{ok:true}}return pending};refresh();await tick();select.value='new';select.dispatchEvent({type:'change'});await tick();release({ok:true,json:async()=>({models:{implement:'old'}})});await tick();assert(saved==='new'&&select.value==='new','stale refresh won');
});
await check('V07 latest refresh wins over older response',async()=>{
 const {u,select,refresh}=modelUi(),pending=[];u.e.context.fetch=()=>new Promise(r=>pending.push(r));refresh();refresh();pending[1]({ok:true,json:async()=>({models:{implement:'latest'}})});await tick();assert(select.value==='latest','normal refresh ignored');pending[0]({ok:true,json:async()=>({models:{implement:'old'}})});await tick();assert(select.value==='latest','older refresh won');
});
for(const raw of ['{','null','{"leaf":42}'])await check('V08 invalid checkpoint '+raw+' recovers valid history and preserves backups',async()=>{
 const {e,h,s,ss}=await create();await h.submit(req({query:'valid saved conversation'}),new Res(),s);await tick();await s.contextLock;await h.shutdownHub(undefined,ss);const dir=path.join(e.dir,'hub-sessions'),cp=path.join(dir,s.id+'.replay-state.json'),replay=path.join(dir,s.id+'.replay.jsonl'),before=fs.readFileSync(replay,'utf8');fs.writeFileSync(cp,raw);const restored=await reload(h,s,ss,e);assert(restored.bridge&&restored.store.buildMessages().length===1&&restored.replay.some(f=>f.includes('valid saved conversation')),'history not recovered');const backups=fs.readdirSync(dir).filter(n=>n.startsWith(s.id)&&n.includes('.recovery-'));assert(backups.length===2,'source backups missing');assert(fs.readFileSync(path.join(dir,backups.find(n=>n.includes('state'))),'utf8')===raw,'checkpoint backup differs');assert(fs.readFileSync(path.join(dir,backups.find(n=>n.includes('jsonl'))),'utf8')===before,'replay backup differs');assert(JSON.parse(fs.readFileSync(cp)).leaf===restored.store.getActiveLeaf(),'checkpoint not rebuilt');await h.shutdownHub(undefined,ss);const again=await reload(h,s,ss,e);assert(fs.readdirSync(dir).filter(n=>n.includes('.recovery-')).length===2,'recovery repeats');const r=new Res();await h.closeSession(r,ss,again.id);assert(r.statusCode===200&&!fs.readdirSync(dir).some(n=>n.startsWith(s.id)&&n!==s.id+'.deleted'),'delete left recovery backups');
});
await check('V08 checkpoint read I/O failure preserves original and remains retryable',async()=>{
 let fail=false;const real=require('fs'),{e,h,s,ss}=await create({modules:{'node:fs':{...real,promises:{...real.promises,readFile:async(file,...a)=>{if(fail&&String(file).endsWith('.replay-state.json'))throw Object.assign(Error('denied'),{code:'EACCES'});return real.promises.readFile(file,...a)}}}}});await h.submit(req({query:'saved'}),new Res(),s);await tick();await s.contextLock;await h.shutdownHub(undefined,ss);const file=path.join(e.dir,'hub-sessions',s.id+'.replay-state.json'),before=fs.readFileSync(file,'utf8');const restored=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir,{id:s.id,title:'saved',startedAt:1,replay:[]});fail=true;let error;try{await restored._ensureBridge()}catch(err){error=err}assert(error&&!restored.bridge&&fs.readFileSync(file,'utf8')===before,'read failure overwritten');fail=false;await restored._ensureBridge();assert(restored.bridge.messages.length===1,'retry failed');
});
await check('V01 unreadable history blocks restoration without changing source',async()=>{
 let fail=false;const real=require('fs'),{e,h,s,ss}=await create({modules:{'node:fs':{...real,readFileSync:(file,...a)=>{if(fail&&String(file).endsWith(s.id+'.jsonl'))throw Object.assign(Error('denied'),{code:'EACCES'});return real.readFileSync(file,...a)}}}});await h.submit(req({query:'saved'}),new Res(),s);await tick();await s.contextLock;await h.shutdownHub(undefined,ss);const file=path.join(e.dir,'hub-sessions',s.id+'.jsonl'),before=fs.readFileSync(file,'utf8');const restored=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir,{id:s.id,title:'saved',startedAt:1,replay:[]});fail=true;let error;try{await restored._ensureBridge()}catch(err){error=err}assert(error&&!restored.bridge&&fs.readFileSync(file,'utf8')===before,'unreadable history restored');fail=false;await restored._ensureBridge();assert(restored.bridge.messages.length===1,'history retry lost data');
});
await check('V05 missing checkpoint does not resurrect old conversation on empty tree',async()=>{
 const {e,h,s,ss}=await create();await h.submit(req({query:'removed'}),new Res(),s);await tick();await s.contextLock;await h.shutdownHub(undefined,ss);const Store=e.load('src/history/session-store.ts').SessionStore,tree=new Store(path.join(e.dir,'hub-sessions',s.id+'.jsonl'));tree.setActiveLeaf(tree.getRootId());fs.rmSync(path.join(e.dir,'hub-sessions',s.id+'.replay-state.json'));const restored=await reload(h,s,ss,e);assert(restored.bridge.messages.length===0&&!restored.replay.some(f=>f.includes('removed')),'stale legacy replay revived');
});
await check('V08 checkpoint repair survives backend startup failure',async()=>{
 const {e,h,s,ss}=await create();await h.submit(req({query:'saved'}),new Res(),s);await tick();await s.contextLock;await h.shutdownHub(undefined,ss);const cp=path.join(e.dir,'hub-sessions',s.id+'.replay-state.json');fs.writeFileSync(cp,'{');let fail=true;const restored=await h.createSession(ss,{makeBridge:o=>{const b=new Bridge(o);b.ready=async()=>{if(fail)throw Error('backend unavailable')};return b}},e.dir,{id:s.id,title:'saved',startedAt:1,replay:[]});let error;try{await restored._ensureBridge()}catch(err){error=err}assert(error&&JSON.parse(fs.readFileSync(cp)).leaf===restored.store.getActiveLeaf(),'checkpoint repair depended on backend');fail=false;await restored._ensureBridge();assert(restored.bridge.messages.length===1,'backend retry lost history');
});
await check('V08 deletion drains recovery backup writes and prevents backend revival',async()=>{
 let intercept=false,started,release;const ready=new Promise(r=>started=r),gate=new Promise(r=>release=r),real=require('fs');const {e,h,s,ss}=await create({modules:{'node:fs':{...real,promises:{...real.promises,writeFile:async(file,...a)=>{if(intercept&&String(file).endsWith('.deleted'))await new Promise(r=>setTimeout(r,30));return real.promises.writeFile(file,...a)},copyFile:async(...a)=>{if(intercept){started();await gate}return real.promises.copyFile(...a)}}}}});await h.submit(req({query:'saved'}),new Res(),s);await tick();await s.contextLock;await h.shutdownHub(undefined,ss);const dir=path.join(e.dir,'hub-sessions');fs.writeFileSync(path.join(dir,s.id+'.replay-state.json'),'{');const restored=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir,{id:s.id,title:'saved',startedAt:1,replay:[]});intercept=true;const restoring=restored._ensureBridge().then(()=>null,e=>e);await ready;const response=new Res(),deleting=h.closeSession(response,ss,s.id);try { const deadline=Date.now()+2000;while(!restored._closed&&Date.now()<deadline)await new Promise(r=>setTimeout(r,5));assert(restored._closed,'deletion did not start'); } finally { release();await deleting; }assert(await restoring,'deleted backend revived');assert(response.statusCode===200&&!fs.readdirSync(dir).some(n=>n.startsWith(s.id)&&n!==s.id+'.deleted'),'backup resurrected after deletion');
});
await check('V08 failed recovery backup preserves sources and allows retry',async()=>{
 let fail=false;const real=require('fs'),{e,h,s,ss}=await create({modules:{'node:fs':{...real,promises:{...real.promises,writeFile:async(file,...a)=>{if(fail&&String(file).includes('.recovery-'))throw Error('ENOSPC');return real.promises.writeFile(file,...a)}}}}});await h.submit(req({query:'saved'}),new Res(),s);await tick();await s.contextLock;await h.shutdownHub(undefined,ss);const dir=path.join(e.dir,'hub-sessions'),cp=path.join(dir,s.id+'.replay-state.json'),rp=path.join(dir,s.id+'.replay.jsonl');fs.writeFileSync(cp,'{');const before=fs.readFileSync(rp,'utf8');const restored=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir,{id:s.id,title:'saved',startedAt:1,replay:[]});fail=true;let error;try{await restored._ensureBridge()}catch(err){error=err}assert(error&&!restored.bridge&&fs.readFileSync(cp,'utf8')==='{'&&fs.readFileSync(rp,'utf8')===before,'backup failure overwrote sources');fail=false;await restored._ensureBridge();assert(restored.bridge.messages.length===1,'backup retry failed');
});
clearTimeout(watchdog);console.log(JSON.stringify({checks:findings.length,passed:findings.filter(f=>f.passed).length,failed:findings.filter(f=>!f.passed).length}));if(findings.some(f=>!f.passed))process.exitCode=1;
})().catch(e=>{clearTimeout(watchdog);console.error(e);process.exitCode=1});
