process.env.ASHUB_TEST_ROOT ||= require('path').resolve(__dirname,'..');
const {env,Res,req,Bridge,assert,ts,vm,fs,path,root}=require('./harness.cjs');
const {ui,El,signal}=require('./ui-harness.cjs');const {EventEmitter}=require('events');
const tick=()=>new Promise(r=>setImmediate(r));const findings=[];
function ast(file){return ts.createSourceFile(file,fs.readFileSync(path.join(root,file),'utf8'),ts.ScriptTarget.Latest,true)}
function find(sf,p){let out;function walk(n){if(!out&&p(n))out=n;if(!out)ts.forEachChild(n,walk)}walk(sf);assert(out,'AST missing');return out;}
function variable(file,name,ctx){const sf=ast(file),n=find(sf,n=>ts.isVariableDeclaration(n)&&n.name?.text===name);return vm.runInContext('('+n.initializer.getText(sf)+')',ctx)}
function method(file,name,ctx){const sf=ast(file),n=find(sf,n=>ts.isMethodDeclaration(n)&&n.name?.text===name);return vm.runInContext(ts.transpileModule('({'+n.getText(sf)+'})['+JSON.stringify(name)+']',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx)}
function callback(file,expression,event,ctx){const sf=ast(file),n=find(sf,n=>ts.isCallExpression(n)&&n.expression.getText(sf)===expression&&n.arguments[0]?.text===event);return vm.runInContext(ts.transpileModule('('+n.arguments[1].getText(sf)+')',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx)}
function hub(e){return e.load('src/hub.ts','export const audit={startHub,createSession,closeSession,forkEndpoint,rewindContext,saveSessionMeta,archiveSession,unarchiveSession,shutdownHub,_flushBuf,persistReplayFile,routeEvent,submit,dropContext,openSseMulti,getContext,setCwdEndpoint,updateConfig,setAutoApprove,uploadImage,serveUpload,readBody,updateTitle,flushPtyBuffer,setSubagentModel,setSubagentBudget,loadArchivedSessions,listSessions,restoreSessions,rewindToTurn,execCommand,tagLastQueryFrame,setSessionTitle,setModelEndpoint,uninstallSkill,listInstalledSkills,searchSkills,_writeLocks};').audit}
async function create(extra={}){const e=env(extra),h=hub(e),ss=new Map(),s=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir);return{e,h,ss,s}}
const frame=f=>JSON.parse(f.split('data: ')[1]);
async function check(id,fn){if(process.env.ONLY&&!process.env.ONLY.split(',').some(x=>id.startsWith(x)))return;try{const detail=await fn();findings.push({id,passed:true,detail});console.log('PASS',id,JSON.stringify(detail))}catch(e){findings.push({id,passed:false,error:e.stack});console.log('FAIL',id,e.stack)}}
const watchdog=setTimeout(()=>{console.error('TIMEOUT');process.exit(1)},30000);
(async()=>{
await check('AA01 continued edits during prompt save use updated commit baseline',async()=>{
 const u=ui(),values=new Map([['ash.prompts',JSON.stringify([{id:'p1',name:'initial',content:'old'}])]]),storage={get length(){return values.size},key:i=>[...values.keys()][i],getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};let release;const gate=new Promise(r=>release=r);u.e.context.localStorage=storage;u.e.context.crypto={randomUUID:()=> 'new-id'};let calls=0;u.e.context.navigator={locks:{request:async(k,fn)=>{if(++calls===1)await gate;return fn()}}};
 const m=u.e.load('web/js/prompt-manager.js','export const audit={startEdit,read:loadPrompts};');m.audit.startEdit('p1');const name=u.doc.getElementById('prompt-editor-name'),save=u.doc.getElementById('prompt-editor-save');name.value='first revision';const first=save.events.click[0]();name.value='continued revision';release();await first;await save.events.click[0]();const stored=m.audit.read();const detail={stored,notifications:u.toasts,draft:name.value};console.log('AA01 observed',JSON.stringify(detail));assert(stored.find(x=>x.id==='p1')?.name==='continued revision'&&u.toasts.length===0&&name.value==='','regression');return detail;
});
await check('AA02 cross-session global budget refresh resumes after new session saves another card',async()=>{
 const u=ui(),reads=[],puts=[];let budgets={implement:40000,review:10000};u.doc.getElementById('subagent-panel').hidden=true;const container=u.doc.getElementById('sa-types');let html='';Object.defineProperty(container,'innerHTML',{get:()=>html,set:v=>{html=v;container.children=[]}});container.querySelectorAll=sel=>sel==='.sa-card'?container.children:[];
 u.modules['./sse.js']={setModelCache(){}};u.modules['./state.js'].agentInfo={provider:'test'};
 u.e.context.fetch=async(url,opts)=>{if(opts?.method==='PUT'){const body=JSON.parse(opts.body);await new Promise(r=>puts.push(r));budgets[body.type]=body.budgetTokens;return{ok:true}}if(!url.endsWith('/sa-types'))return{ok:true,json:async()=>({models:{}})};const types=Object.entries(budgets).map(([type,budgetTokens])=>({type,budgetTokens,description:'test'}));return new Promise(r=>reads.push(()=>r({ok:true,json:async()=>({types})})));};
 const m=u.e.load('web/js/subagent-panel.js','export const audit={commitBudgetField};');m.setSgOpen(true);reads.shift()();await tick();m.audit.commitBudgetField(container.children[0],'budgetTokens',90000,()=>{});u.active.value={id:'bbbbbb',state:{}};reads.shift()();await tick();const review=container.children[1];m.audit.commitBudgetField(review,'budgetTokens',50000,()=>{});puts[0]();await tick();while(reads.length){reads.shift()();await tick()}puts[1]();await tick();assert(reads.length===1,'deferred read missing');reads.shift()();await tick();const detail={storedGlobal:budgets,displayedImplement:container.children[0]._saCfg.budgetTokens,newSessionSaveFinished:!review._budgetSaving.budgetTokens,pendingReads:reads.length};assert(detail.storedGlobal.implement===90000&&detail.displayedImplement===90000&&detail.newSessionSaveFinished&&reads.length===0,'regression');return detail;
});
await check('AA03 double-click file enables send button',async()=>{
 const u=ui();u.composer();const input=u.doc.getElementById('query'),send=u.doc.getElementById('send-btn');assert(input.value===''&&send.disabled,'composer baseline failed');u.doc.getElementById('files-panel').hasAttribute=()=>true;const panel=u.e.load('web/js/files-panel.js','export const audit={makeEntryEl};');const entry=panel.audit.makeEntryEl({kind:'file',name:'README.md'},'');entry.events.dblclick[0]();const detail={input:input.value,sendDisabled:send.disabled};input.dispatchEvent(new u.e.context.Event('input'));detail.enabledAfterManualInput=!send.disabled;assert(detail.input==='@README.md'&&!detail.sendDisabled&&detail.enabledAfterManualInput,'regression');return detail;
});
await check('AA04 at-mention directory cache invalidates on same-session cwd change',async()=>{
 const u=ui();let opts,calls=0,cwd='/projects/A';u.modules['./autocomplete.js']={attachAutocomplete:o=>{opts=o;return{}}};u.e.context.fetch=async()=>{calls++;return{ok:true,json:async()=>({files:[{name:cwd==='/projects/A'?'only-A.txt':'only-B.txt',kind:'file'}]})}};const input=new El();input.value='@';input.selectionStart=1;u.e.load('web/js/at-mention.js').attachAtMentionAutocomplete(input);const initial=await opts.fetcher();cwd='/projects/B';Object.assign(u.e.context,{activeSession:u.active,CustomEvent:class{constructor(type,opts){this.type=type;this.detail=opts?.detail}},refreshCwdChip(){},refreshFilesIfOpen(){}});method('web/js/sse.js','shell:cwd-change',u.e.context).call(u.active.peek(),{cwd});const after=await opts.fetcher();assert(initial[0].name==='only-A.txt'&&after[0].name==='only-B.txt'&&calls===2,'regression');u.e.clock(131000);const expired=await opts.fetcher();return{currentCwd:cwd,afterCwdChange:after.map(x=>x.name),networkRequestsBeforeTTL:2,afterTTL:expired.map(x=>x.name)};
});
await check('AA05 deleting legacy prompt frees full localStorage after per-id migration',async()=>{
 const u=ui(),values=new Map([['ash.prompts',JSON.stringify([{id:'legacy',name:'large saved prompt',content:'x'.repeat(10000)}])]]);const size=entries=>[...entries].reduce((n,[k,v])=>n+k.length+v.length,0),quota=size(values);u.e.context.localStorage={get length(){return values.size},key:i=>[...values.keys()][i],getItem:k=>values.get(k)??null,setItem:(k,v)=>{const next=new Map(values);next.set(k,v);if(size(next)>quota)throw Error('QuotaExceededError');values.set(k,v)}};const m=u.e.load('web/js/prompt-manager.js','export const audit={deletePrompt,read:loadPrompts};');await m.audit.deletePrompt('legacy');const detail={remainingPrompts:m.audit.read().length,storageCharacters:size(values),quota,notifications:u.toasts};console.log('AA05 observed',JSON.stringify(detail));assert(detail.remainingPrompts===0&&detail.storageCharacters<quota&&u.toasts.length===0,'regression');return detail;
});

function promptsEnv(){const u=ui(),values=new Map(),storage={get length(){return values.size},key:i=>[...values.keys()][i],getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v)};let id=0;u.e.context.localStorage=storage;u.e.context.crypto={randomUUID:()=> 'p-'+(++id)};const m=u.e.load('web/js/prompt-manager.js','export const audit={startAdd,startEdit,cancelEdit,deletePrompt,read:loadPrompts};');const name=u.doc.getElementById('prompt-editor-name'),content=u.doc.getElementById('prompt-editor-content'),save=()=>u.doc.getElementById('prompt-editor-save').events.click[0]();return{u,values,storage,m,name,content,save}}
await check('AA01 new prompt keeps allocated id when draft advances during save',async()=>{
 const p=promptsEnv();let release;const gate=new Promise(r=>release=r);p.u.e.context.navigator={locks:{request:async(k,fn)=>{await gate;return fn()}}};p.m.audit.startAdd();p.name.value='first';p.content.value='body';const first=p.save();p.name.value='continued';release();await first;assert(p.name.value==='continued','new draft overwritten');await p.save();const data=p.m.audit.read();assert(data.length===1&&data[0].id==='p-1'&&data[0].name==='continued'&&!p.u.toasts.length,'continued new prompt duplicated');
});
await check('AA01 save completion does not replace a different editor instance',async()=>{
 const p=promptsEnv();p.values.set('ash.prompts',JSON.stringify([{id:'a',name:'A',content:'one'},{id:'b',name:'B',content:'two'}]));let release;const gate=new Promise(r=>release=r);p.u.e.context.navigator={locks:{request:async(k,fn)=>{await gate;return fn()}}};p.m.audit.startEdit('a');p.name.value='saved A';const first=p.save();p.m.audit.startEdit('b');p.name.value='draft B';release();await first;assert(p.name.value==='draft B','other editor clobbered');await p.save();const data=p.m.audit.read();assert(data.find(x=>x.id==='a').name==='saved A'&&data.find(x=>x.id==='b').name==='draft B','other editor identity changed');
});
await check('AA01 failed write preserves original comparison baseline for retry',async()=>{
 const p=promptsEnv();p.values.set('ash.prompts',JSON.stringify([{id:'a',name:'A',content:'one'}]));p.m.audit.startEdit('a');p.name.value='retry';const write=p.storage.setItem;p.storage.setItem=()=>{throw Error('blocked')};await p.save();assert(p.m.audit.read()[0].name==='A'&&p.name.value==='retry','failed save changed baseline');p.storage.setItem=write;await p.save();assert(p.m.audit.read()[0].name==='retry'&&p.u.toasts.length===1,'retry rejected as conflict');
});
await check('AA05 successful edit reclaims legacy body without removing other prompts',async()=>{
 const p=promptsEnv();p.values.set('ash.prompts',JSON.stringify([{id:'a',name:'A',content:'x'.repeat(1000)},{id:'b',name:'B',content:'keep'}]));p.m.audit.startEdit('a');p.content.value='short';await p.save();const legacy=JSON.parse(p.values.get('ash.prompts'));assert(legacy.length===1&&legacy[0].id==='b'&&p.m.audit.read().length===2,'migration lost unrelated record');await p.m.audit.deletePrompt('a');assert(p.m.audit.read().length===1&&p.m.audit.read()[0].id==='b','deleted edit resurrected');
});
await check('AA05 quota deletion retains unrelated legacy and modern prompts',async()=>{
 const p=promptsEnv();p.values.set('ash.prompts',JSON.stringify([{id:'a',name:'A',content:'x'.repeat(1000)},{id:'b',name:'B',content:'keep'}]));p.values.set('ash.prompt.c',JSON.stringify({id:'c',name:'C',content:'modern'}));const size=m=>[...m].reduce((n,[k,v])=>n+k.length+v.length,0),quota=size(p.values);p.storage.setItem=(k,v)=>{const copy=new Map(p.values);copy.set(k,v);if(size(copy)>quota)throw Error('QuotaExceededError');p.values.set(k,v)};await p.m.audit.deletePrompt('a');const data=p.m.audit.read();assert(data.length===2&&data.some(x=>x.id==='b')&&data.some(x=>x.id==='c')&&!p.u.toasts.length&&size(p.values)<quota,'quota cleanup removed unrelated data');
});
function mentionEnv(){const u=ui();let opts,closes=0;const reads=[];u.modules['./autocomplete.js']={attachAutocomplete:o=>{opts=o;return{close:()=>closes++}}};u.e.context.fetch=()=>new Promise(r=>reads.push(r));const input=new El();input.value='@';input.selectionStart=1;u.e.load('web/js/at-mention.js').attachAtMentionAutocomplete(input);return{u,reads,input,get opts(){return opts},closes:()=>closes,change:(sid='aaaaaa')=>u.doc.dispatchEvent({type:'ash:cwd-change',detail:{sessionId:sid}})}}
const filesResponse=name=>({ok:true,json:async()=>({files:[{name,kind:'file'}]})});
await check('AA04 late old-directory response cannot replace current cache',async()=>{
 const x=mentionEnv(),old=x.opts.fetcher();x.change();const fresh=x.opts.fetcher();x.reads[1](filesResponse('new.txt'));const current=await fresh;x.reads[0](filesResponse('old.txt'));assert((await old).length===0,'old directory result displayed');const cached=await x.opts.fetcher();assert(cached[0].name==='new.txt'&&x.reads.length===2&&current[0].name==='new.txt','old response poisoned cache');
});
await check('AA04 cwd change closes suggestions and requests fresh input evaluation',async()=>{
 const x=mentionEnv();let inputEvents=0;x.input.addEventListener('input',()=>inputEvents++);const fetch=x.opts.fetcher();x.reads[0](filesResponse('old.txt'));const old=(await fetch)[0];x.change();x.opts.accept(old);assert(x.input.value==='@'&&x.closes()===1&&inputEvents===1,'stale suggestion accepted or list not refreshed');const fresh=x.opts.fetcher();x.reads[1](filesResponse('new.txt'));x.opts.accept((await fresh)[0]);assert(x.input.value==='@new.txt ','current suggestion not accepted');
});
await check('AA04 background cwd changes preserve active suggestions',async()=>{
 const x=mentionEnv(),fetch=x.opts.fetcher();x.reads[0](filesResponse('current.txt'));const item=(await fetch)[0];x.change('bbbbbb');x.opts.accept(item);assert(x.input.value==='@current.txt '&&x.closes()===0,'background event invalidated active suggestion');
});
await check('AA04 turn change invalidates in-flight listing as well as stored cache',async()=>{
 const x=mentionEnv(),pending=x.opts.fetcher();x.u.doc.dispatchEvent({type:'sse:processing-change',detail:{sessionId:'aaaaaa'}});x.reads[0](filesResponse('before-turn.txt'));assert((await pending).length===0,'inflight pre-turn cache survived');const next=x.opts.fetcher();assert(x.reads.length===2,'new turn reused old data');x.reads[1](filesResponse('after-turn.txt'));assert((await next)[0].name==='after-turn.txt','new turn failed');
});
function budgetEnv(){const u=ui(),reads=[],puts=[];let budgets={implement:40000,review:10000},editing=false;u.doc.getElementById('subagent-panel').hidden=true;const container=u.doc.getElementById('sa-types');Object.defineProperty(container,'innerHTML',{get:()=>'',set:()=>container.children=[]});container.querySelectorAll=sel=>sel==='.sa-card'?container.children:sel==='.sa-meta-input'&&editing?[new El()]:[];u.modules['./sse.js']={setModelCache(){}};u.modules['./state.js'].agentInfo={provider:'test'};u.e.context.fetch=async(url,opts)=>{if(opts?.method==='PUT'){const body=JSON.parse(opts.body);const ok=await new Promise(r=>puts.push(r));if(ok)budgets[body.type]=body.budgetTokens;return{ok}}if(!url.endsWith('/sa-types'))return{ok:true,json:async()=>({models:{}})};const types=Object.entries(budgets).map(([type,budgetTokens])=>({type,budgetTokens,description:'test'}));return new Promise(r=>reads.push(()=>r({ok:true,json:async()=>({types})})));};const m=u.e.load('web/js/subagent-panel.js','export const audit={commitBudgetField};');return{u,reads,puts,container,m,budgets,setEditing:v=>editing=v}}
await check('AA02 deferred refresh waits for active numeric draft then resumes on cancel',async()=>{
 const x=budgetEnv();x.m.setSgOpen(true);x.reads.shift()();await tick();x.m.audit.commitBudgetField(x.container.children[0],'budgetTokens',90000,()=>{});x.u.active.value={id:'bbbbbb',state:{}};x.reads.shift()();await tick();x.setEditing(true);x.puts[0](true);await tick();assert(x.reads.length===0&&x.container.children[0]._saCfg.budgetTokens===40000,'active draft rebuilt');x.setEditing(false);x.u.doc.dispatchEvent({type:'ash:subagent-budget-settled'});assert(x.reads.length===1,'deferred draft refresh lost');x.reads.shift()();await tick();assert(x.container.children[0]._saCfg.budgetTokens===90000,'draft cancel did not refresh');
});
await check('AA02 failed second save also releases deferred global refresh',async()=>{
 const x=budgetEnv();x.m.setSgOpen(true);x.reads.shift()();await tick();x.m.audit.commitBudgetField(x.container.children[0],'budgetTokens',90000,()=>{});x.u.active.value={id:'bbbbbb',state:{}};x.reads.shift()();await tick();x.m.audit.commitBudgetField(x.container.children[1],'budgetTokens',50000,()=>{});x.puts[0](true);await tick();x.puts[1](false);await tick();for(let i=0;x.reads.length&&i<5;i++){x.reads.shift()();await tick()}assert(x.container.children[0]._saCfg.budgetTokens===90000&&x.container.children[1]._saCfg.budgetTokens===10000&&x.reads.length===0,'failure stranded global refresh');
});
await check('AA02 same-session response arriving after completed write retries without another save',async()=>{
 const x=budgetEnv();x.m.setSgOpen(true);x.reads.shift()();await tick();x.m.audit.commitBudgetField(x.container.children[0],'budgetTokens',90000,()=>{});x.m.renderSubagentPanel();x.puts[0](true);await tick();x.reads.shift()();await tick();assert(x.reads.length===1,'stale read after settlement was stranded');x.reads.shift()();await tick();assert(x.container.children[0]._saCfg.budgetTokens===90000,'retry failed');
});

clearTimeout(watchdog);console.log(JSON.stringify({checks:findings.length,passed:findings.filter(x=>x.passed).length,failed:findings.filter(x=>!x.passed).length}));if(findings.some(x=>!x.passed))process.exitCode=1;
})().catch(e=>{clearTimeout(watchdog);console.error(e);process.exitCode=1});
