const {env,Res,req,assert,fs,path,check,results}=require('./harness.cjs');
const {ui,El,signal}=require('./ui-harness.cjs');
const tick=()=>new Promise(setImmediate);
const skill=(dir,name='demo')=>{fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'SKILL.md'),`---\nname: ${name}\ndescription: Test\n---\nBody\n`)};
const installed=async(h,cwd='')=>{const r=new Res();await h.listInstalledSkills(req({},'/api/skills/installed?cwd='+encodeURIComponent(cwd)),r);return r.json().installed};
function acUI(){const u=ui();u.doc.createElement=()=>{const el=new El();el.scrollIntoView=()=>{};return el};const list=u.doc.getElementById('autocomplete');Object.defineProperty(list,'innerHTML',{get:()=>'',set:()=>{list.children=[]}});return u}
const flush=async u=>{for(const [id,timer] of [...u.e.timers]){u.e.timers.delete(id);await timer.fn()}};
function mentions(){const u=ui();let opts;u.modules['./autocomplete.js']={attachAutocomplete:o=>{opts=o;return{close(){}}}};const input=new El();input.setSelectionRange=(a,b)=>{input.selectionStart=a;input.selectionEnd=b};u.e.load('web/js/at-mention.js').attachAtMentionAutocomplete(input);return{...u,input,get opts(){return opts},set:v=>{input.value=v;input.selectionStart=v.length}}}
(async()=>{
 await check('R20 project skill matches kernel and uninstall retains home copy',async()=>{const e=env(),h=e.hub(),cwd=path.join(e.os.homedir(),'project'),project=path.join(cwd,'.agents/skills/demo'),home=path.join(e.os.homedir(),'.agents/skills/demo');skill(project);skill(home);const kernel=e.load('node_modules/agent-sh/dist/agent/skills.js');const rows=await installed(h,cwd);assert(rows.length===1&&rows[0].path===kernel.discoverSkills(cwd)[0].baseDir&&rows[0].path===project);const r=new Res();await h.uninstallSkill(req({...rows[0],cwd}),r);assert(r.statusCode===200&&!fs.existsSync(project)&&fs.existsSync(home));assert((await installed(h,cwd))[0].path===home&&kernel.discoverSkills(cwd)[0].baseDir===home)});
 await check('R20 external workspaces exclude unrelated home skills',async()=>{const e=env(),h=e.hub(),cwd=path.join(e.dir,'external');fs.mkdirSync(cwd);skill(path.join(e.os.homedir(),'.agents/skills/demo'));const kernel=e.load('node_modules/agent-sh/dist/agent/skills.js');assert(kernel.discoverSkills(cwd).length===0&&(await installed(h,cwd)).length===0&&(await installed(h)).length===0)});
 await check('R20 global and configured skills retain kernel precedence over project skills',async()=>{const e=env(),h=e.hub(),cwd=path.join(e.os.homedir(),'project'),global=path.join(e.dir,'skills/demo'),extra=path.join(e.dir,'custom/demo');skill(global);skill(extra);skill(path.join(cwd,'.agents/skills/demo'));skill(path.join(e.os.homedir(),'.agents/skills/demo'));e.settings.getSettings=()=>({skillPaths:[path.dirname(extra)]});fs.writeFileSync(path.join(e.dir,'settings.json'),JSON.stringify(e.settings.getSettings()));const kernel=e.load('node_modules/agent-sh/dist/agent/skills.js');assert((await installed(h,cwd))[0].path===global&&kernel.discoverSkills(cwd)[0].baseDir===global);const r=new Res();await h.uninstallSkill(req({name:'demo',path:global,cwd}),r);kernel.invalidateGlobalSkillsCache();assert((await installed(h,cwd))[0].path===extra&&kernel.discoverSkills(cwd)[0].baseDir===extra)});
 await check('R20 nearest ancestor wins before home, independently for each cwd',async()=>{const e=env(),h=e.hub(),parent=path.join(e.os.homedir(),'parent'),child=path.join(parent,'child'),other=path.join(e.os.homedir(),'other');fs.mkdirSync(child,{recursive:true});fs.mkdirSync(other);const p=path.join(parent,'.agents/skills/demo'),home=path.join(e.os.homedir(),'.agents/skills/demo');skill(p);skill(home);assert((await installed(h,child))[0].path===p&&(await installed(h,other))[0].path===home)});
 await check('R20 spaced directory completes nested spaced file and preserves following prose',async()=>{const u=mentions(),calls=[];u.e.context.fetch=async url=>{calls.push(url);return{ok:true,json:async()=>({files:url.includes('subdir=')?[{name:'read me.md',kind:'file'}]:[{name:'My Project',kind:'dir'}]})}};u.set('@My');u.opts.accept((await u.opts.fetcher())[0]);assert(u.input.value==='@"My Project/"'&&u.opts.shouldOpen());u.input.value+=' continue';const items=await u.opts.fetcher();assert(calls.at(-1).includes('subdir=My%20Project'));u.opts.accept(items[0]);assert(u.input.value==='@"My Project/read me.md"  continue'&&!u.opts.shouldOpen())});
 for(const name of ['中文 目录','a"b','a\\b','normal'])await check('R20 quoted mention round trip '+name,()=>{const e=env(),m=e.load('web/js/file-mention.js'),formatted=m.formatFileMention(name,true),input={value:formatted.text,selectionStart:formatted.cursor};const token=m.getActiveAtToken(input);assert(token.query===name+'/'&&token.end===formatted.text.length);const file=m.formatFileMention(name);assert(m.getActiveAtToken({value:file.text,selectionStart:file.cursor})===null)});
 await check('R20 token boundaries exclude prose and emails and accept manual quoted paths',()=>{const m=env().load('web/js/file-mention.js');for(const value of ['hello@example.com','@file.md done','@"My Project/file" done'])assert(m.getActiveAtToken({value})===null);assert(m.getActiveAtToken({value:'read @"My Project/src'}).query==='My Project/src');assert(m.getActiveAtToken({value:'@first.txt @second'}).query==='second');assert(m.getActiveAtToken({value:'@"broken\\'} )===null)});
 await check('R20 file panel inserts quoted directory with cursor inside quotes',()=>{const u=ui();u.doc.getElementById('files-panel').hasAttribute=()=>true;const input=u.doc.getElementById('query');input.value='inspect';input.setSelectionRange=(a,b)=>{input.selectionStart=a};const m=u.e.load('web/js/files-panel.js','export const audit={makeEntryEl};'),entry=m.audit.makeEntryEl({name:'My Project',kind:'dir'},'');entry.dispatchEvent({type:'dblclick'});assert(input.value==='inspect @"My Project/"');const parser=u.e.load('web/js/file-mention.js');assert(parser.getActiveAtToken(input).query==='My Project/')});
 await check('R20 changed input immediately disables stale choices and network failure stays closed',async()=>{const u=acUI(),m=u.e.load('web/js/autocomplete.js'),input=new El();let offline=false,accepted=0;const ac=m.attachAutocomplete({inputEl:input,listEl:u.doc.getElementById('autocomplete'),shouldOpen:()=>true,fetcher:async()=>{if(offline)throw Error('offline');return[{name:'old'}]},accept:()=>accepted++});input.value='old';input.dispatchEvent({type:'input'});await flush(u);assert(ac.hasSelection());offline=true;input.value='new';input.dispatchEvent({type:'input'});assert(!ac.hasSelection());ac.acceptCurrent();assert(accepted===0);input.dispatchEvent({type:'input'});await flush(u);assert(!ac.hasSelection());offline=false;input.dispatchEvent({type:'input'});await flush(u);assert(ac.hasSelection())});
 await check('R20 stale rejected request cannot close a newer successful selection',async()=>{const u=acUI(),m=u.e.load('web/js/autocomplete.js'),input=new El();let rejectOld;const ac=m.attachAutocomplete({inputEl:input,listEl:u.doc.getElementById('autocomplete'),shouldOpen:()=>true,fetcher:buffer=>buffer==='old'?new Promise((_,r)=>rejectOld=r):Promise.resolve([{name:'new'}]),accept(){}});input.value='old';input.dispatchEvent({type:'input'});const pending=flush(u);input.value='new';input.dispatchEvent({type:'input'});await flush(u);assert(ac.hasSelection());rejectOld(Error('old failed'));await pending;assert(ac.hasSelection())});
 await check('R20 actual slash composer cannot replace new command with old suggestion',async()=>{const u=acUI();u.modules['./autocomplete.js']=u.e.load('web/js/autocomplete.js');let offline=false;u.e.context.fetch=async()=>{if(offline)throw Error('offline');return{ok:true,json:async()=>({items:[{name:'/help'}]})}};const m=u.e.load('web/js/composer.js','export const audit={slashAc};'),input=u.doc.getElementById('query');input.value='/he';input.dispatchEvent({type:'input'});await flush(u);assert(m.audit.slashAc.hasSelection());offline=true;input.value='/model';input.dispatchEvent({type:'input'});await flush(u);m.audit.slashAc.acceptCurrent();assert(input.value==='/model'&&!m.audit.slashAc.hasSelection())});
 await check('R20 successful file completion can reopen nested suggestions through shared autocomplete',async()=>{const u=acUI();delete u.modules['./autocomplete.js'];const input=u.doc.getElementById('query');input.setSelectionRange=(a,b)=>{input.selectionStart=a};u.e.context.fetch=async url=>({ok:true,json:async()=>({files:url.includes('subdir=')?[{name:'read me.md',kind:'file'}]:[{name:'My Project',kind:'dir'}]})});const ac=u.e.load('web/js/at-mention.js').attachAtMentionAutocomplete(input);input.value='@My';input.selectionStart=3;input.dispatchEvent({type:'input'});await flush(u);ac.acceptCurrent();await flush(u);assert(ac.hasSelection()&&input.value==='@"My Project/"');ac.acceptCurrent();assert(input.value==='@"My Project/read me.md" '&&!ac.hasSelection())});
 const exportUI=()=>{const u=ui();u.modules['./session-manager.js'].activeSessionId=signal('aaaaaa');return{u,m:u.e.load('web/js/export.js','export const audit={toMarkdown};').audit}};
 const meta={id:'aaaaaa',title:'Fixture'};const image={type:'image_url',image_url:{url:'data:image/png;base64,aGVsbG8='}};
 await check('R20 export retains image-only user turn before assistant reply',()=>{const {m}=exportUI();const md=m.toMarkdown(meta,[{role:'user',content:[image]},{role:'assistant',content:'Answer'}]);assert(md.includes('> ![export.image](<data:image/png;base64,aGVsbG8=>)')&&md.indexOf('data:image')<md.indexOf('Answer'))});
 await check('R20 mixed image and text export preserves order and strips context wrappers',()=>{const {m}=exportUI();const md=m.toMarkdown(meta,[{role:'user',content:[{type:'text',text:'<query_context>hidden</query_context>before'},image,{type:'text',text:'after'},image]}]);assert(!md.includes('hidden')&&md.indexOf('before')<md.indexOf('data:image')&&md.indexOf('after')>md.indexOf('data:image')&&md.match(/data:image/g).length===2)});
 for(const url of ['',undefined,'javascript:alert(1)','blob:expired'])await check('R20 unavailable image retains user message '+String(url),()=>{const {m}=exportUI();const md=m.toMarkdown(meta,[{role:'user',content:[{type:'image_url',image_url:{url}}]}]);assert(md.includes('> [export.image.unavailable]')&&!md.includes('javascript:'))});
 await check('R20 external image URL escapes Markdown delimiters without fetching',()=>{const {m,u}=exportUI();const md=m.toMarkdown(meta,[{role:'user',content:[{type:'image_url',image_url:{url:'https://example.invalid/a(b) c.png'}}]}]);assert(md.includes('<https://example.invalid/a(b)%20c.png>')&&u.calls.length===0)});
 await check('R20 text and tool summaries still export while system notes stay hidden',()=>{const {m}=exportUI();const md=m.toMarkdown(meta,[{role:'system',content:'hidden'},{role:'user',systemNote:true,content:'hidden'},{role:'user',content:'hello'},{role:'assistant',content:'reply',tool_calls:[{function:{name:'read',arguments:'{"path":"file"}'}}]}]);assert(md.includes('> hello')&&md.includes('reply')&&md.includes('[tool: read file]')&&!md.includes('hidden'))});
 await check('R20 export button downloads Markdown containing an image-only turn',async()=>{const {u}=exportUI();let blob,filename;u.e.context.Blob=Blob;u.e.context.URL=class extends URL{static createObjectURL(value){blob=value;return 'blob:fixture'}static revokeObjectURL(){}};u.doc.createElement=()=>{const el=new El();el.click=()=>{filename=el.download};return el};u.e.context.fetch=async url=>({ok:true,json:async()=>url==='/sessions'?[{instanceId:'aaaaaa',title:'Photo',kind:'agent'}]:{messages:[{role:'user',content:[image]},{role:'assistant',content:'Answer'}]}});await u.doc.getElementById('export-btn').events.click[0]();assert(filename==='Photo-aaaaaa.md'&&(await blob.text()).includes('data:image/png;base64,aGVsbG8=')&&!u.doc.getElementById('export-btn').disabled)});
 console.log(JSON.stringify({checks:results.length,passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length}));
})();
