// Error recovery and async ownership regressions confirmed in the October review.
const {env,Res,req,check,assert,results,root,ts,vm,fs,path}=require('./harness.cjs');
const {ui,El,signal}=require('./ui-harness.cjs');
const tick=()=>new Promise(setImmediate),response=data=>({ok:true,json:async()=>data});
const catalog={providers:[{name:'preview',models:[]}]};
function variable(file,name,ctx){const sf=ts.createSourceFile(file,fs.readFileSync(path.join(root,file),'utf8'),ts.ScriptTarget.Latest,true);let found;function visit(n){if(ts.isVariableDeclaration(n)&&n.name?.text===name)found=n.initializer;ts.forEachChild(n,visit)}visit(sf);assert(found,name);return vm.runInContext('('+found.getText(sf)+')',ctx)}
function callback(file,target,event,ctx){const sf=ts.createSourceFile(file,fs.readFileSync(path.join(root,file),'utf8'),ts.ScriptTarget.Latest,true);let found;function visit(n){if(ts.isCallExpression(n)&&n.expression.getText(sf)===target&&n.arguments[0]?.text===event)found=n.arguments[1];ts.forEachChild(n,visit)}visit(sf);assert(found,target);return vm.runInContext('('+found.getText(sf)+')',ctx)}
function config(){const u=ui();u.e.context.CustomEvent=u.e.context.Event;u.doc.getElementById('config-auto-approve').closest=()=>null;u.modules['./sse.js']={invalidateModelCache(){},getModelCacheGeneration(){},setModelCache(){}};u.e.context.fetch=async url=>response(url==='/api/models'?catalog:{defaultProvider:'preview',providers:{preview:{apiKey:'masked'}},custom:'keep'});const m=u.e.load('web/js/config-panel.js');return{...u,m,el:id=>u.doc.getElementById(id)}}
async function readConfig(e,h){const r=new Res(),done=new Promise(resolve=>r.on('finish',resolve));h.getConfig(r);await done;return r}
function template(){
 const u=ui(),button=new El(),panel=u.doc.getElementById('no-session-empty'),input=u.doc.getElementById('query'),id=signal('');let resolve,opens=[],submitted=[];
 button.dataset.queryZh='review this project';panel.querySelectorAll=()=>[button];input.disabled=true;input.form={requestSubmit(){submitted.push({id:id.peek(),query:input.value})}};
 const activate=(next)=>{id.value=next;u.active.value={id:next,state:{replaying:false},streamEl:{querySelector:()=>null}};input.disabled=!next};
 u.modules['./session-manager.js']={activeSessionId:id,activeSession:u.active,openTab(next){opens.push(next);activate(next)}};
 u.modules['./sidebar.js']={createSession:()=>new Promise(r=>resolve=r)};u.modules['./i18n.js'].lang={value:'zh'};
 u.modules['./config-panel.js']={loadProviderCatalog:async()=>catalog,providerLabel:x=>x,saveProviderApiKey:async()=>true};u.e.context.fetch=async()=>response({anyProviderConfigured:true});
 u.e.load('web/js/no-session.js');const poll=()=>[...u.e.timers.values()].find(x=>x.ms===100)?.fn();
 return{u,button,input,submitted,opens,activate,poll,resolve:value=>resolve(value)};
}
function panels(){const u=ui();delete u.modules['./panel-manager.js'];u.e.context.MutationObserver=class{observe(){}};const m=u.e.load('web/js/panel-manager.js'),els={};for(const n of ['a','b']){els[n]=u.doc.getElementById(n+'-panel');els[n].hidden=true}const register=n=>m.registerPanel(n,{toggleBtnId:n,panelId:n+'-panel',open(){els[n].hidden=false},close(){els[n].hidden=true}});let resolve;m.registerPanel('a',{toggleBtnId:'a',panelId:'a-panel',load:()=>new Promise(r=>resolve=()=>{register('a');r()})});register('b');return{u,m,els,resolve:()=>resolve(),click:n=>u.doc.getElementById(n).events.click[0]()}}
(async()=>{
 for(const code of ['EIO','EACCES'])await check('R15 config read '+code+' blocks saves without losing stored fields',async()=>{
  const real=require('node:fs'),e=env({modules:{'node:fs':{...real,readFile:(file,...args)=>String(file).endsWith('settings.json')?args.at(-1)(Object.assign(Error('failure'),{code})):real.readFile(file,...args)}}});
  const h=e.load('src/hub.ts','export const audit={getConfig};').audit,file=path.join(e.dir,'settings.json'),original={providers:{preview:{apiKey:'fixture-only'},second:{apiKey:'other-fixture'}},custom:'keep'};fs.writeFileSync(file,JSON.stringify(original));
  const r=await readConfig(e,h);assert(r.statusCode===500&&!r.body.includes('fixture-only'),'read failure reported success or leaked key');
  const u=config();let writes=0;u.e.context.fetch=async(url,opts)=>{if(opts?.method==='PUT')writes++;return url==='/api/models'?response(catalog):{ok:false,status:r.statusCode,json:async()=>r.json()}};await u.m.setConfigOpen(true);await u.el('config-save-simple').events.click[0]();await u.el('config-save').events.click[0]();
  assert(!writes&&u.el('config-save').disabled&&u.el('config-save-simple').disabled&&fs.readFileSync(file,'utf8')===JSON.stringify(original),'unsafe save allowed');
 });
 for(const value of ['broken','null','[]'])await check('R15 corrupt config '+value+' returns failure',async()=>{const e=env(),h=e.load('src/hub.ts','export const audit={getConfig};').audit;fs.writeFileSync(path.join(e.dir,'settings.json'),value);assert((await readConfig(e,h)).statusCode===500)});
 await check('R15 missing settings still support first run and valid keys stay masked',async()=>{const e=env(),h=e.load('src/hub.ts','export const audit={getConfig};').audit;assert((await readConfig(e,h)).statusCode===200);fs.writeFileSync(path.join(e.dir,'settings.json'),JSON.stringify({providers:{preview:{apiKey:'fixture-only-key'}},custom:'keep'}));const r=await readConfig(e,h);assert(r.statusCode===200&&r.json().custom==='keep'&&!r.body.includes('fixture-only-key'))});
 await check('R15 old settings save cannot close or replace a reopened draft',async()=>{
  const u=config();await u.m.setConfigOpen(true);let finish,count=0;u.e.context.fetch=async(url,opts)=>opts?.method==='PUT'?(count++,new Promise(r=>finish=r)):response(url==='/api/models'?catalog:{defaultProvider:'preview',providers:{preview:{apiKey:'masked'}}});
  const pending=u.el('config-save-simple').events.click[0]();assert(u.el('config-save-simple').disabled&&u.el('config-body-simple').inert);await u.el('config-save-simple').events.click[0]();assert(count===1,'duplicate PUT');
  await u.m.setConfigOpen(false);await u.m.setConfigOpen(true);u.el('config-editor').value='{"draft":"new draft"}';assert(!u.el('config-body-simple').inert&&u.el('config-save').disabled,'new draft readiness wrong');finish(response({}));await pending;
  assert(u.el('config-toggle').classList.contains('active')&&!u.el('config-save').disabled&&JSON.parse(u.el('config-editor').value).draft==='new draft','old save took over current opening');
 });
 await check('R15 failed settings save retains draft, unlocks retry, success closes owner',async()=>{
  const u=config();await u.m.setConfigOpen(true);u.el('config-mode-tabs').events.click[0]({target:{closest:()=>({dataset:{mode:'advanced'}})}});u.el('config-editor').value='{"custom":"draft"}';let fail=true;u.e.context.fetch=async()=>fail?{ok:false,text:async()=>'offline'}:response({});
  await u.el('config-save').events.click[0]();assert(!u.el('config-save').disabled&&!u.el('config-body-advanced').inert&&u.el('config-toggle').classList.contains('active')&&JSON.parse(u.el('config-editor').value).custom==='draft');fail=false;await u.el('config-save').events.click[0]();assert(!u.el('config-toggle').classList.contains('active'));
 });
 await check('R15 repeated advanced-mode click preserves edited key and malformed drafts',async()=>{
  const u=config();await u.m.setConfigOpen(true);const click=()=>u.el('config-mode-tabs').events.click[0]({target:{closest:()=>({dataset:{mode:'advanced'}})}});click();const draft=JSON.parse(u.el('config-editor').value);draft.providers.preview.apiKey='unsaved-fixture';u.el('config-editor').value=JSON.stringify(draft);click();assert(JSON.parse(u.el('config-editor').value).providers.preview.apiKey==='unsaved-fixture');u.el('config-editor').value='{ editing';click();assert(u.el('config-editor').value==='{ editing');
 });
 await check('R15 template waits for its creation result and submits only to that id',async()=>{
  const x=template(),pending=x.button.events.click[0]();x.activate('bbbbbb');x.poll();assert(!x.submitted.length,'submitted before creation');x.resolve('cccccc');await pending;x.poll();assert(x.opens.join()==='cccccc'&&x.submitted.length===1&&x.submitted[0].id==='cccccc');x.poll();assert(x.submitted.length===1,'submitted twice');
 });
 await check('R15 template gives up after navigation instead of sending to another empty session',async()=>{const x=template(),pending=x.button.events.click[0]();x.resolve('cccccc');await pending;x.activate('bbbbbb');x.poll();assert(!x.submitted.length)});
 await check('R15 template preserves text typed while the new session becomes ready',async()=>{const x=template(),pending=x.button.events.click[0]();x.resolve('cccccc');await pending;x.input.value='my own draft';x.poll();assert(!x.submitted.length&&x.input.value==='my own draft')});
 await check('R15 failed creation never arms a template or navigates',async()=>{const x=template(),pending=x.button.events.click[0]();x.resolve(null);await pending;x.activate('bbbbbb');x.poll();assert(!x.submitted.length&&!x.opens.length)});
 await check('R15 session creation can stay in SPA and normal creation still navigates',async()=>{
  const u=ui();Object.assign(u.e.context,{toast(){},t:x=>x,fetch:async()=>response({instanceId:'abcdef'})});const create=variable('web/js/sidebar.js','doCreateSession',u.e.context);assert(await create('/project',{navigate:false})==='abcdef'&&!u.e.context.window.location);u.e.context.window.location={};await create('/project');assert(u.e.context.window.location.href==='/abcdef/');
 });
 await check('R15 rapid lazy panel switch respects last selection and can reopen canceled panel',async()=>{const x=panels(),pending=x.click('a');await x.click('b');x.resolve();await pending;assert(x.els.a.hidden&&!x.els.b.hidden);await x.click('a');assert(!x.els.a.hidden&&x.els.b.hidden)});
 await check('R15 Escape cancels pending first panel load',async()=>{const x=panels(),pending=x.click('a');x.u.doc.dispatchEvent({type:'keydown',key:'Escape',stopImmediatePropagation(){}});x.resolve();await pending;assert(x.els.a.hidden&&!x.u.doc.getElementById('a').disabled)});
 await check('R15 programmatic panel switch invalidates older lazy open',async()=>{const x=panels(),pending=x.click('a');x.m.closeOtherPanels('b');x.els.b.hidden=false;x.resolve();await pending;assert(x.els.a.hidden&&!x.els.b.hidden)});
 await check('R15 empty subagent panel makes no request and blocks budget writes',async()=>{
  const u=ui(),urls=[];u.active.value=null;u.modules['./state.js']={currentSessionId:()=>'',agentInfo:{}};u.modules['./sse.js']={setModelCache(){}};u.doc.getElementById('subagent-panel').hidden=true;u.e.context.fetch=async url=>{urls.push(url);return response({})};
  const m=u.e.load('web/js/subagent-panel.js','export const audit={commitBudgetField,refreshModelDropdowns};');m.setSgOpen(true);const card=new El();card.dataset.type='plan';m.audit.commitBudgetField(card,'budgetTokens',1,()=>{});m.audit.refreshModelDropdowns();await tick();assert(!urls.length&&u.doc.getElementById('sa-types').innerHTML.includes('no.session.title'));
 });
 await check('R15 closing session invalidates pending subagent cards',async()=>{
  const u=ui();u.doc.getElementById('subagent-panel').hidden=true;u.modules['./sse.js']={setModelCache(){}};u.modules['./state.js'].agentInfo={};let finish;u.e.context.fetch=()=>new Promise(r=>finish=r);const m=u.e.load('web/js/subagent-panel.js');m.setSgOpen(true);u.active.value=null;finish(response({types:[{type:'old'}]}));await tick();assert(u.doc.getElementById('sa-types').innerHTML.includes('no.session.title'));
 });
 await check('R15 files list includes all entries beyond 200 and sorts directories first',async()=>{const e=env(),h=e.load('src/hub.ts','export const audit={listFiles};').audit,dir=path.join(e.dir,'large');fs.mkdirSync(dir);for(let i=0;i<205;i++)fs.writeFileSync(path.join(dir,'f'+String(i).padStart(3,'0')),'');fs.mkdirSync(path.join(dir,'z-dir'));const r=new Res();await h.listFiles(r,{cwd:dir});assert(r.statusCode===200&&r.json().files.length===206&&r.json().files[0].kind==='dir'&&r.json().files.some(f=>f.name==='f204'))});
 await check('R15 directory errors differ from an actually empty directory',async()=>{const e=env(),h=e.load('src/hub.ts','export const audit={listFiles};').audit,a=new Res(),b=new Res();await h.listFiles(a,{cwd:path.join(e.dir,'removed')});await h.listFiles(b,{cwd:e.dir});assert(a.statusCode===500&&a.json().error&&b.statusCode===200&&b.json().files.length===0)});
 await check('R15 root file HTTP errors show failure, never empty success',async()=>{const u=ui();u.doc.getElementById('files-panel').hidden=true;u.e.context.fetch=async()=>({ok:false,status:500,json:async()=>({error:'denied'})});const m=u.e.load('web/js/files-panel.js','export const audit={fetchFiles};');await m.audit.fetchFiles();assert(u.doc.getElementById('files-empty').innerHTML==='files.failed')});
 await check('R15 failed child directory expansion reports an error and remains retryable',async()=>{const u=ui(),row=new El(),dirs=new Map();row.dataset.path='src';Object.assign(u.e.context,{expandedDirs:()=>dirs,fetchSubdir:async()=>{throw Error('unreadable')},toast:(...args)=>u.toasts.push(args),t:x=>x});await variable('web/js/files-panel.js','toggleDir',u.e.context)(row);assert(u.toasts.length===1&&!dirs.has('src')&&!row.classList.contains('loading'))});
 await check('R15 new terminal network failure is caught, visible, and retryable',async()=>{const u=ui(),button=new El();let offline=true;Object.assign(u.e.context,{newTerminalBtn:button,getSession:()=>null,activeSessionId:{peek:()=>''},toast:(...args)=>u.toasts.push(args),t:x=>x,setSessionKind(){},fetch:async()=>{if(offline)throw Error('offline');return response({instanceId:'abcdef'})}});u.e.context.window.location={};const fn=callback('web/js/sidebar.js','newTerminalBtn?.addEventListener','click',u.e.context);await fn({});assert(u.toasts.length===1&&!button.disabled);offline=false;await fn({});assert(u.e.context.window.location.href==='/abcdef/'&&!button.disabled)});
 await check('R15 context clears metadata on empty session and failed refresh',async()=>{const u=ui();u.active.peek().context={selected:new Set(),activeRoles:new Set(['all']),currentMsgs:[],currentGroups:[]};u.e.context.fetch=async()=>response({messages:[],activeTokens:999,contextWindow:4000});const m=u.e.load('web/js/context-panel.js','export const audit={renderContext};');await m.audit.renderContext();assert(u.doc.getElementById('ctx-meta').textContent.includes('999'));u.e.context.fetch=async()=>{throw Error('offline')};await m.audit.renderContext();assert(u.doc.getElementById('ctx-meta').textContent==='');u.doc.getElementById('ctx-meta').textContent='old';u.active.value=null;await m.audit.renderContext();assert(u.doc.getElementById('ctx-meta').textContent===''&&u.doc.getElementById('ctx-drop').disabled)});
 console.log(JSON.stringify({checks:results.length,passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length}));
})();
