process.env.ASHUB_TEST_ROOT ||= require('path').resolve(__dirname,'..');
const {env,Res,req,Bridge,assert,ts,vm,fs,path,root}=require('./harness.cjs');
const {ui,El,signal}=require('./ui-harness.cjs');const {EventEmitter}=require('events');
const tick=()=>new Promise(r=>setImmediate(r));const findings=[];
function ast(file){return ts.createSourceFile(file,fs.readFileSync(path.join(root,file),'utf8'),ts.ScriptTarget.Latest,true)}
function find(sf,p){let out;function walk(n){if(!out&&p(n))out=n;if(!out)ts.forEachChild(n,walk)}walk(sf);assert(out,'AST missing');return out;}
function variable(file,name,ctx){const sf=ast(file),n=find(sf,n=>ts.isVariableDeclaration(n)&&n.name?.text===name);return vm.runInContext('('+n.initializer.getText(sf)+')',ctx)}
function method(file,name,ctx){const sf=ast(file),n=find(sf,n=>ts.isMethodDeclaration(n)&&n.name?.text===name);return vm.runInContext(ts.transpileModule('({'+n.getText(sf)+'})['+JSON.stringify(name)+']',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx)}
function callback(file,expression,event,ctx){const sf=ast(file),n=find(sf,n=>ts.isCallExpression(n)&&n.expression.getText(sf)===expression&&n.arguments[0]?.text===event);return vm.runInContext(ts.transpileModule('('+n.arguments[1].getText(sf)+')',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx)}
function hub(e){return e.load('src/hub.ts','export const audit={startHub,createSession,closeSession,forkEndpoint,rewindContext,saveSessionMeta,archiveSession,unarchiveSession,shutdownHub,_flushBuf,persistReplayFile,routeEvent,submit,dropContext,openSseMulti,getContext,setCwdEndpoint,updateConfig,setAutoApprove,uploadImage,serveUpload,readBody,updateTitle,flushPtyBuffer,setSubagentModel,setSubagentBudget,loadArchivedSessions,listSessions,restoreSessions,rewindToTurn,execCommand,tagLastQueryFrame,setSessionTitle,setModelEndpoint,uninstallSkill,listInstalledSkills,_writeLocks};').audit}
async function create(extra={}){const e=env(extra),h=hub(e),ss=new Map(),s=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir);return{e,h,ss,s}}
const frame=f=>JSON.parse(f.split('data: ')[1]);
async function check(id,fn){if(process.env.ONLY&&!process.env.ONLY.split(',').some(x=>id.startsWith(x)))return;try{const detail=await fn();findings.push({id,passed:true,detail});console.log('PASS',id,JSON.stringify(detail))}catch(e){findings.push({id,passed:false,error:e.stack});console.log('FAIL',id,e.stack)}}
function acp(){const calls=[],child=new EventEmitter();child.stdout=new EventEmitter();child.stdout.setEncoding=()=>{};child.kill=()=>{};child.stdin=Object.assign(new EventEmitter(),{writable:true,end(){},write:raw=>{const m=JSON.parse(raw);calls.push(m);if(m.method==='initialize'||m.method==='session/new'||m.method==='session/load'||m.method==='session/prompt')queueMicrotask(()=>child.stdout.emit('data',JSON.stringify({jsonrpc:'2.0',id:m.id,result:m.method==='initialize'?{protocolVersion:1,agentCapabilities:{loadSession:true}}:m.method==='session/new'?{sessionId:'remote'}:{stopReason:'end_turn'}})+'\n'));}});const e=env({modules:{'node:child_process':{spawn:()=>child}}}),A=e.load('src/bridges/acp.ts').AcpBridge;return{e,A,calls,child}}

function ashEnv(extra={}){
 let created=0,killed=0,shells=0,shellKilled=0;
 const noop=()=>{},core={handlers:{define:noop,advise:noop,call:noop},bus:{on:noop,emit:noop,emitPipe:(_,p)=>p},extensionContext:()=>({agent:{registerInstruction:noop,registerTool:noop,registerContextProducer:()=>noop}}),activateBackend:async()=>{},kill:()=>killed++};
 const e=env({...extra,modules:{'agent-sh':{createCore:()=>{created++;return core}},'agent-sh/agent':{activateAgent:noop},'agent-sh/extensions':{loadBuiltinExtensions:async()=>[]},'agent-sh/extension-loader':{loadExtensions:async()=>[]},'agent-sh/shell':{Shell:class{constructor(){shells++}onExit(){}kill(){shellKilled++}}},'agent-sh/shell/terminal':{headlessTerminal:()=>({})},...extra.modules}});const A=e.load('src/bridges/ash.ts').AshBridge;A.prototype.wire=noop;A.prototype.registerUserProviders=noop;A.prototype.gateImageToolResults=noop;return{e,A,core,stats:()=>({created,killed,shells,shellKilled})};
}
const watchdog=setTimeout(()=>{console.error('TIMEOUT');process.exit(1)},30000);
(async()=>{
await check('X01 rejected duplicate remains unaddressed and preserves earlier turns',async()=>{
 const {h,s}=await create();await h.submit(req({query:'same'}),new Res(),s);await tick();await s.contextLock;await h.submit(req({query:'keep this later turn'}),new Res(),s);await tick();await s.contextLock;
 const realAsh=env().load('src/bridges/ash.ts').AshBridge;s.bridge.submit=text=>realAsh.prototype.submit.call({initPromise:Promise.resolve(),core:{},backendRegistered:false},text);await h.submit(req({query:'same'}),new Res(),s);await tick();await s.contextLock;
 const qs=s.replay.map(frame).filter(f=>f.meta.name==='agent:query').map(f=>f.payload);assert(qs.length===3&&qs[0].entryId&&!qs[2].entryId,'failed query stole an older ID');const u=ui();let sent=false;Object.assign(u.e.context,{t:x=>x,fetch:async()=>{sent=true;return{ok:true,json:async()=>({})}}});let error;try{await variable('web/js/actions.js','rewindToTurn',u.e.context)({sid:s.id,entryId:qs[2].entryId})}catch(e){error=e}assert(error&&!sent&&s.bridge.messages.length===2,'unaddressed rewind changed history');return{queries:qs,remainingMessages:s.bridge.messages.length};
});
await check('X02 slow lazy restore leaves healthy SSE subscriptions responsive',async()=>{
 const {e,h,s,ss}=await create();let release,started;const gate=new Promise(r=>release=r),ready=new Promise(r=>started=r);const lazy=await h.createSession(ss,{makeBridge:o=>{const b=new Bridge(o);b.ready=()=>{started();return gate};return b}},e.dir,{id:'bbbbbb',title:'lazy',startedAt:1,replay:[]});const res=new Res(),rq=Object.assign(new EventEmitter(),{headers:{}});const opening=h.openSseMulti(rq,res,ss,lazy.id+':all,'+s.id+':all','');await ready;h.routeEvent(s,{name:'agent:response-chunk',payload:{blocks:[{type:'text',text:'live response from healthy session'}]}});const blocked={healthySubscribers:s.sseClients.size,healthyReplayDone:res.body.includes('"source":"'+s.id+'"'),healthyLiveReceived:res.body.includes('live response from healthy session')};release();await opening;assert(blocked.healthySubscribers===1&&blocked.healthyReplayDone&&blocked.healthyLiveReceived,'healthy session blocked');return{whileFirstSessionPending:blocked,afterReleaseSubscribers:s.sseClients.size};
});
await check('X03 unknown model rejects and preserves the displayed model',async()=>{
 const {e,h,s}=await create(),bus=new EventEmitter(),agent={activeModel:{id:'old',provider:'test'},pullModels:()=>[{id:'old',provider:'test'}],bus};
 // Execute installed agent-sh's actual rejection listener with its real lexical this.
 const sf=ast('node_modules/agent-sh/dist/agent/agent-loop.js'),n=find(sf,n=>ts.isCallExpression(n)&&n.expression.getText(sf)==='on'&&n.arguments[0]?.text==='config:switch-model');
 const handler=vm.runInContext('(function(){return '+n.arguments[1].getText(sf)+'})',e.context).call(agent);bus.on('config:switch-model',handler);const errors=[];bus.on('ui:error',p=>errors.push(p.message));
 const A=e.load('src/bridges/ash.ts').AshBridge,b=Object.create(A.prototype);b.core={handlers:{call:()=>agent.pullModels()},bus};s.bridge=b;s.model='old';const r=new Res();await h.setModelEndpoint(req({model:'removed',provider:'test'}),r,s);
 const u=ui(),sv={id:s.id,agentInfo:{model:'old',provider:'test',modalities:['image']}};u.active.value=sv;Object.assign(u.e.context,{activeSession:u.active,refreshModelChip(){},BALANCE_PROVIDERS:new Set(),t:x=>x,toast:()=>{},fetch:async()=>({ok:r.statusCode===200,status:r.statusCode})});await variable('web/js/sse.js','selectModel',u.e.context)(sv,'removed','test');
 assert(r.statusCode===500&&agent.activeModel.id==='old'&&sv.agentInfo.model==='old'&&r.body.includes('Unknown model'),'unknown model accepted');return{status:r.statusCode,backend:agent.activeModel.id,displayed:sv.agentInfo.model,backendError:errors[0]};
});
await check('X04 bridge exit during metadata save rejects creation and cleans files',async()=>{
 let release,started;const gate=new Promise(r=>release=r),ready=new Promise(r=>started=r),real=require('fs');const e=env({modules:{'node:fs':{...real,promises:{...real.promises,writeFile:async(file,...a)=>{if(String(file).endsWith('.meta.json.tmp')){started();await gate}return real.promises.writeFile(file,...a)}}}}}),h=hub(e),ss=new Map();let b;const creating=h.createSession(ss,{makeBridge:o=>(b=new Bridge(o))},e.dir);await ready;b.emit('closed');release();let error;try{await creating}catch(e){error=e}assert(error&&ss.size===0,'closed session returned as successful');assert(!fs.readdirSync(path.join(e.dir,'hub-sessions')).some(n=>n.endsWith('.meta.json')),'failed creation metadata survived');return{creationRejected:true,registeredSessions:ss.size};
});
await check('X05 budget rollback survives a second edit and cancel',async()=>{
 const u=ui(),card=new El();card.dataset.type='implement';let current=new El(),read,puts=0;current.dataset={field:'budgetTokens',value:'40000'};const fetchRead=new Promise(r=>read=r);
 function setup(el){el.select=()=>{};el.closest=()=>card;el.replaceWith=next=>{el.isConnected=false;current=next;setup(next)};return el;}setup(current);card.querySelector=()=>current.className==='sa-meta-btn'?current:null;u.doc.createElement=()=>setup(new El());
 Object.assign(u.e.context,{saBudgetSeq:0,currentSessionId:()=> 'aaaaaa',toast(){},t:x=>x,metaLabel:(f,v)=>String(v),fetch:async(url,opts)=>opts?.method==='PUT'?{ok:false,status:500}:fetchRead});
 u.e.context.commitBudgetField=variable('web/js/subagent-panel.js','commitBudgetField',u.e.context);u.e.context.makeMetaButton=variable('web/js/subagent-panel.js','makeMetaButton',u.e.context);u.e.context.startNumberEdit=variable('web/js/subagent-panel.js','startNumberEdit',u.e.context);
 u.e.context.startNumberEdit(current);current.value='90000';current.dispatchEvent({type:'keydown',key:'Enter',preventDefault(){}});await tick();u.e.context.startNumberEdit(current);read({ok:true,json:async()=>({types:[{type:'implement',budgetTokens:40000}]})});await tick();current.dispatchEvent({type:'keydown',key:'Escape',preventDefault(){},stopPropagation(){}});assert(current.dataset.value==='40000','failed budget remained visible');return{backendBudget:40000,displayedAfterCancel:Number(current.dataset.value)};
});
await check('X06 stale initial card fetch cannot overwrite a confirmed edit',async()=>{
 const u=ui(),reads=[];let stored=40000,displayed=40000;Object.assign(u.e.context,{saTypes:new El(),panelRenderSeq:0,saModelSeq:0,_renderedSid:'aaaaaa',_optionsSig:'',saBudgetSeq:0,FALLBACK_TYPES:{},currentSessionId:()=> 'aaaaaa',renderCards:list=>{displayed=list[0].budgetTokens},toast(){},t:x=>x,fetch:async(url,opts)=>{if(opts?.method==='PUT'){stored=JSON.parse(opts.body).budgetTokens;return{ok:true}}return new Promise(r=>reads.push(r))}});
 const render=variable('web/js/subagent-panel.js','renderSubagentPanel',u.e.context),commit=variable('web/js/subagent-panel.js','commitBudgetField',u.e.context);render();render();reads[0]({ok:true,json:async()=>({types:[{type:'implement',budgetTokens:40000}]})});await tick();const card=new El();card.dataset.type='implement';displayed=90000;commit(card,'budgetTokens',90000,v=>displayed=v.budgetTokens);await tick();reads[1]({ok:true,json:async()=>({types:[{type:'implement',budgetTokens:40000}]})});await tick();assert(stored===90000&&displayed===90000,'stale render overwrote confirmed budget');return{storedBudget:stored,displayedBudget:displayed};
});
await check('X07 delayed auto-approve read cannot reset a confirmed enabled toggle',async()=>{
 const {e,h,ss}=await create(),u=ui(),toggle=new El();let release;const readGate=new Promise(r=>release=r);Object.assign(u.e.context,{autoApproveToggle:toggle,autoApproveSeq:0,autoApproveSaving:false,autoApproveConfirmed:null,toast(){},t:x=>x,fetch:async(url,opts)=>{if(!opts)return readGate;const r=new Res();await h.setAutoApprove(req(JSON.parse(opts.body)),r,ss);return{ok:r.statusCode===200,status:r.statusCode,text:async()=>r.body}}});const loading=variable('web/js/config-panel.js','loadAutoApprove',u.e.context)();toggle.checked=true;await variable('web/js/config-panel.js','putAutoApprove',u.e.context)(true);release({ok:true,json:async()=>({autoApprove:false})});await loading;const stored=JSON.parse(fs.readFileSync(path.join(e.dir,'settings.json'),'utf8'))['ashub.permissions.autoApprove'];assert(stored===true&&toggle.checked===true&&!toggle.disabled,'stale approval state displayed');return{storedAutoApprove:stored,displayedToggle:toggle.checked};
});
await check('X08 old-project skill response and stale uninstall action are discarded',async()=>{
 const e=env(),h=hub(e),cwdA=path.join(e.dir,'projects','A'),cwdB=path.join(e.dir,'projects','B'),skillPath=path.join(cwdA,'.agents','skills','project-only');fs.mkdirSync(skillPath,{recursive:true});fs.mkdirSync(cwdB,{recursive:true});fs.writeFileSync(path.join(skillPath,'SKILL.md'),'test skill');const listed=new Res();await h.listInstalledSkills(req({},'/api/skills/installed?cwd='+encodeURIComponent(cwdA),'GET'),listed);const u=ui();let release,status;const oldRead=new Promise(r=>release=r),sent=[];Object.assign(u.e.context,{activeSession:u.active,skillsCwd:()=>u.active.peek()?.state?.cwd||'',installedFetchSeq:0,installedCwd:null,installedList:new El(),installed:new Set(),installedPaths:new Map(),installedSources:new Map(),skillsSearch:new El(),renderSkills(){},esc:String,t:x=>x,toast(){},fetch:async(url,opts)=>{sent.push({url,body:opts?.body&&JSON.parse(opts.body)});if(opts){const r=new Res();await h.uninstallSkill(req(JSON.parse(opts.body)),r);status=r.statusCode;return{ok:r.statusCode===200,text:async()=>r.body}}return oldRead}});u.active.value={id:'aaaaaa',state:{cwd:cwdA}};const refreshing=variable('web/js/skills-panel.js','refreshInstalled',u.e.context)();u.active.value={id:'bbbbbb',state:{cwd:cwdB}};release({ok:true,json:async()=>listed.json()});await refreshing;const changed=await variable('web/js/skills-panel.js','uninstall',u.e.context)('project-only',{path:skillPath,cwd:cwdA});assert(changed===false&&!sent.some(x=>x.body)&&!u.e.context.installed.has('project-only')&&fs.existsSync(skillPath),'stale project action accepted');return{staleActionSent:false,sourcePreserved:true};
});

await check('X01 successful identical submissions have distinct IDs across flushes',async()=>{
 const {h,s}=await create();for(let i=0;i<3;i++){await h.submit(req({query:'same'}),new Res(),s);await tick();await s.contextLock}const ids=s.replay.map(frame).filter(f=>f.meta.name==='agent:query').map(f=>f.payload.entryId);assert(ids.every(Boolean)&&new Set(ids).size===3,'valid duplicate query lost its ID');
});
await check('X01 failed duplicate cannot claim a later successful retry',async()=>{
 const {h,s}=await create();await h.submit(req({query:'same'}),new Res(),s);await tick();await s.contextLock;const original=s.bridge.submit.bind(s.bridge);s.bridge.submit=async()=>{throw Error('unavailable')};await h.submit(req({query:'same'}),new Res(),s);await tick();await s.contextLock;s.bridge.submit=original;await h.submit(req({query:'same'}),new Res(),s);await tick();await s.contextLock;const q=s.replay.map(frame).filter(f=>f.meta.name==='agent:query').map(f=>f.payload);assert(q[0].entryId&&!q[1].entryId&&q[2].entryId&&q[0].entryId!==q[2].entryId,'failed duplicate stole retry ID');
});
await check('X02 disconnect removes healthy subscribers while another restore waits',async()=>{
 const {e,h,s,ss}=await create();let release,started;const ready=new Promise(r=>started=r),gate=new Promise(r=>release=r);const lazy=await h.createSession(ss,{makeBridge:o=>{const b=new Bridge(o);b.ready=()=>{started();return gate};return b}},e.dir,{id:'bbbbbb',title:'saved',startedAt:1,replay:[]});const res=new Res(),rq=Object.assign(new EventEmitter(),{headers:{}}),p=h.openSseMulti(rq,res,ss,lazy.id+':all,'+s.id+':all,'+s.id+':all','');await ready;assert(s.sseClients.size===1,'healthy subscriber missing');rq.emit('close');assert(s.sseClients.size===0,'healthy subscriber leaked');release();await p;assert(lazy.sseClients.size===0,'late restore attached disconnected client');
});
await check('X02 failed restoration does not prevent healthy replay completion',async()=>{
 const {e,h,s,ss}=await create();const lazy=await h.createSession(ss,{makeBridge:o=>{const b=new Bridge(o);b.ready=async()=>{throw Error('unavailable')};return b}},e.dir,{id:'bbbbbb',title:'saved',startedAt:1,replay:[]});const res=new Res();await h.openSseMulti(Object.assign(new EventEmitter(),{headers:{}}),res,ss,lazy.id+':all,'+s.id+':all','');assert(s.sseClients.has(res)&&res.body.includes('ui:error')&&res.body.includes('hub:replay-done'),'healthy replay blocked by failure');
});
await check('X03 known model requires confirmed identity after dispatch',async()=>{
 const e=env(),A=e.load('src/bridges/ash.ts').AshBridge,b=Object.create(A.prototype);let active={model:'old',provider:'test'},apply=true;const bus=new EventEmitter();bus.on('config:switch-model',m=>{if(apply)active={model:m.id,provider:m.provider}});b.core={handlers:{call:n=>n==='agent:get-models'?[{id:'new',provider:'test'},{id:'ignored',provider:'test'}]:active},bus};b.execCommand('/model','new@test');assert(active.model==='new','valid model switch failed');apply=false;let error;try{b.execCommand('/model','ignored@test')}catch(e){error=e}assert(error&&active.model==='new','ignored switch reported success');
});
await check('X04 early bridge close rejects even when ready never resolves',async()=>{
 const e=env(),h=hub(e),ss=new Map();let b;const pending=h.createSession(ss,{makeBridge:o=>{b=new Bridge(o);b.ready=()=>new Promise(()=>{});return b}},e.dir).then(()=>null,e=>e);b.emit('closed');const result=await pending;assert(result&&ss.size===0,'closed initialization hung or published');
});
await check('X04 closed lazy backend remains retryable without losing saved history',async()=>{
 const {e,h,s,ss}=await create();await h.submit(req({query:'saved'}),new Res(),s);await tick();await s.contextLock;await h.shutdownHub(undefined,ss);let b,first=true,started;const ready=new Promise(r=>started=r);const restored=await h.createSession(ss,{makeBridge:o=>{b=new Bridge(o);if(first){first=false;b.ready=()=>{started();return new Promise(()=>{})}}return b}},e.dir,{id:s.id,title:'saved',startedAt:1,replay:[]});const pending=restored._ensureBridge().then(()=>null,e=>e);await ready;b.emit('closed');assert(await pending,'closed lazy backend reported ready');await restored._ensureBridge();assert(ss.has(s.id)&&restored.bridge.messages[0].content==='saved','retry lost saved history');
});
await check('X05 rollback after second editor closes updates current button',async()=>{
 const u=ui(),card=new El();card.dataset.type='implement';let current=new El(),release;current.dataset={field:'budgetTokens',value:'40000'};const gate=new Promise(r=>release=r);function setup(el){el.select=()=>{};el.closest=()=>card;el.replaceWith=next=>{el.isConnected=false;current=next;setup(next)};return el}setup(current);card.querySelector=()=>current.className==='sa-meta-btn'?current:null;u.doc.createElement=()=>setup(new El());Object.assign(u.e.context,{saBudgetSeq:0,currentSessionId:()=> 'aaaaaa',toast(){},t:x=>x,metaLabel:(f,v)=>String(v),fetch:async(url,opts)=>opts?.method==='PUT'?{ok:false,status:500}:gate});for(const n of ['commitBudgetField','makeMetaButton','startNumberEdit'])u.e.context[n]=variable('web/js/subagent-panel.js',n,u.e.context);u.e.context.startNumberEdit(current);current.value='90000';current.dispatchEvent({type:'keydown',key:'Enter',preventDefault(){}});await tick();u.e.context.startNumberEdit(current);current.dispatchEvent({type:'keydown',key:'Escape',preventDefault(){},stopPropagation(){}});release({ok:true,json:async()=>({types:[{type:'implement',budgetTokens:40000}]})});await tick();assert(current.dataset.value==='40000','rollback updated obsolete button');
});
await check('X06 latest initial render wins over reordered same-session reads',async()=>{
 const u=ui(),reads=[];let shown;Object.assign(u.e.context,{saTypes:new El(),panelRenderSeq:0,saBudgetSeq:0,saModelSeq:0,_renderedSid:null,_optionsSig:'',FALLBACK_TYPES:{},currentSessionId:()=> 'aaaaaa',renderCards:list=>shown=list[0].budgetTokens,fetch:()=>new Promise(r=>reads.push(r))});const render=variable('web/js/subagent-panel.js','renderSubagentPanel',u.e.context);render();render();reads[1]({ok:true,json:async()=>[{type:'implement',budgetTokens:60000}]});await tick();reads[0]({ok:true,json:async()=>[{type:'implement',budgetTokens:40000}]});await tick();assert(shown===60000,'older render overwrote new cards');
});
await check('X06 card reads during a pending budget save do not rebuild controls',async()=>{
 const u=ui(),card=new El(),types=new El();card.dataset.type='implement';types.querySelectorAll=s=>s==='.sa-card'?[card]:[];let save,renders=0;const gate=new Promise(r=>save=r);Object.assign(u.e.context,{saTypes:types,panelRenderSeq:0,saBudgetSeq:0,saModelSeq:0,_renderedSid:'aaaaaa',_optionsSig:'',FALLBACK_TYPES:{},currentSessionId:()=> 'aaaaaa',renderCards:()=>renders++,toast(){},t:x=>x,fetch:async(url,opts)=>opts?.method==='PUT'?gate:{ok:true,json:async()=>[{type:'implement',budgetTokens:40000}]}});variable('web/js/subagent-panel.js','commitBudgetField',u.e.context)(card,'budgetTokens',90000,()=>{});const render=variable('web/js/subagent-panel.js','renderSubagentPanel',u.e.context);render();await tick();assert(renders===0,'pending edit was replaced');save({ok:true});await tick();u.e.context.fetch=async()=>({ok:true,json:async()=>[{type:'implement',budgetTokens:90000}]});render();await tick();assert(renders===1&&!card._budgetSaving.budgetTokens,'normal rendering failed after save');
});
await check('X07 failed save restores confirmed value and unlocks toggle',async()=>{
 const u=ui(),toggle=new El();toggle.checked=false;Object.assign(u.e.context,{autoApproveToggle:toggle,autoApproveSeq:0,autoApproveSaving:false,autoApproveConfirmed:true,toast(){},t:x=>x,fetch:async()=>({ok:false,status:500,text:async()=> 'disk full'})});await variable('web/js/config-panel.js','putAutoApprove',u.e.context)(false);assert(toggle.checked&&!toggle.disabled&&!u.e.context.autoApproveSaving,'failed save stranded permission toggle');
});
await check('X07 approval loads during save are skipped and newer reads win',async()=>{
 const u=ui(),toggle=new El(),reads=[];Object.assign(u.e.context,{autoApproveToggle:toggle,autoApproveSeq:0,autoApproveSaving:false,autoApproveConfirmed:null,fetch:()=>new Promise(r=>reads.push(r))});const load=variable('web/js/config-panel.js','loadAutoApprove',u.e.context),a=load(),b=load();reads[1]({ok:true,json:async()=>({autoApprove:true})});await b;reads[0]({ok:true,json:async()=>({autoApprove:false})});await a;assert(toggle.checked===true,'old approval read applied');u.e.context.autoApproveSaving=true;await load();assert(reads.length===2,'approval read started during write');
});
await check('X08 current project uninstall uses its bound path and works',async()=>{
 const e=env(),h=hub(e),cwd=path.join(e.dir,'project'),dest=path.join(cwd,'.agents','skills','demo');fs.mkdirSync(dest,{recursive:true});fs.writeFileSync(path.join(dest,'SKILL.md'),'demo');const u=ui();Object.assign(u.e.context,{skillsCwd:()=>cwd,toast(){},fetch:async(url,opts)=>{const r=new Res();await h.uninstallSkill(req(JSON.parse(opts.body)),r);return{ok:r.statusCode===200,text:async()=>r.body}}});const done=await variable('web/js/skills-panel.js','uninstall',u.e.context)('demo',{path:dest,cwd});assert(done&&!fs.existsSync(dest),'valid project uninstall failed');
});
await check('X08 newest installed-list request wins within one project',async()=>{
 const u=ui(),reads=[];Object.assign(u.e.context,{skillsCwd:()=> '/A',installedFetchSeq:0,installedCwd:null,installed:new Set(),installedPaths:new Map(),installedSources:new Map(),installedList:new El(),skillsSearch:new El(),renderSkills(){},t:x=>x,esc:String,fetch:()=>new Promise(r=>reads.push(r))});const refresh=variable('web/js/skills-panel.js','refreshInstalled',u.e.context),a=refresh(),b=refresh();reads[1]({ok:true,json:async()=>({installed:[{name:'new',path:'/A/.agents/skills/new'}]})});await b;reads[0]({ok:true,json:async()=>({installed:[{name:'old',path:'/A/.agents/skills/old'}]})});await a;assert(u.e.context.installed.has('new')&&!u.e.context.installed.has('old'),'older skill read won');
});

await check('X06 other-session save completion does not discard initial cards',async()=>{
 const u=ui(),types=new El();types.innerHTML='old project controls';let release,shown;Object.assign(u.e.context,{saTypes:types,panelRenderSeq:0,saBudgetSeq:1,saModelSeq:0,_renderedSid:'aaaaaa',_optionsSig:'',FALLBACK_TYPES:{},currentSessionId:()=> 'bbbbbb',renderCards:list=>shown=list[0].budgetTokens,fetch:()=>new Promise(r=>release=r)});variable('web/js/subagent-panel.js','renderSubagentPanel',u.e.context)();assert(types.innerHTML==='','old project controls remained editable');u.e.context.saBudgetSeq++;release({ok:true,json:async()=>[{type:'implement',budgetTokens:50000}]});await tick();assert(shown===undefined,'stale global snapshot was applied');release({ok:true,json:async()=>[{type:'implement',budgetTokens:90000}]});await tick();assert(shown===90000,'fresh retry suppressed new project cards');
});
await check('X08 full skills module rejects A to B to A stale replies',async()=>{
 const u=ui(),reads=[];u.doc.getElementById('skills-overlay').hidden=true;u.active.value={id:'aaaaaa',state:{cwd:'/A'}};u.e.context.fetch=(url)=>new Promise(resolve=>reads.push({url,resolve}));const m=u.e.load('web/js/skills-panel.js','export const audit={get:()=>({installed:[...installed],paths:[...installedPaths],cwd:installedCwd,skills:allSkills}),refreshInstalled};');m.setSkillsOpen(true);u.active.value={id:'bbbbbb',state:{cwd:'/B'}};u.active.value={id:'aaaaaa',state:{cwd:'/A'}};assert(reads.length===6,'project switches did not refresh both lists');for(const x of reads.slice(-2))x.resolve({ok:true,json:async()=>x.url.includes('/installed')?{installed:[{name:'latest',path:'/A/.agents/skills/latest'}]}:{skills:[{id:'github:new/latest',name:'latest'}]}});await tick();for(const x of reads.slice(0,-2))x.resolve({ok:true,json:async()=>x.url.includes('/installed')?{installed:[{name:'stale',path:'/A/.agents/skills/stale'}]}:{skills:[{id:'github:old/stale',name:'stale'}]}});await tick();const state=m.audit.get();assert(state.cwd==='/A'&&state.installed.join()==='latest'&&state.skills[0].name==='latest','stale project or catalog response applied');
});
await check('X08 catalog source mismatch cannot redraw previous source cards',async()=>{
 const u=ui(),list=new El();list.innerHTML='loading new source';Object.assign(u.e.context,{skillsList:list,skillsCount:new El(),catalogSource:'gitee',currentSource:'github'});variable('web/js/skills-panel.js','renderSkills',u.e.context)('');assert(list.innerHTML==='loading new source','old catalog appeared under new source');
});

clearTimeout(watchdog);console.log(JSON.stringify({checks:findings.length,passed:findings.filter(x=>x.passed).length,failed:findings.filter(x=>!x.passed).length}));if(findings.some(x=>!x.passed))process.exitCode=1;
})().catch(e=>{clearTimeout(watchdog);console.error(e);process.exitCode=1});
