process.env.ASHUB_TEST_ROOT ||= require('path').resolve(__dirname,'..');
const {env,Res,req,Bridge,assert,ts,vm,fs,path,root}=require('./harness.cjs');
const {ui,El,signal}=require('./ui-harness.cjs');const {EventEmitter}=require('events');
const tick=()=>new Promise(r=>setImmediate(r));const findings=[];
function ast(file){return ts.createSourceFile(file,fs.readFileSync(path.join(root,file),'utf8'),ts.ScriptTarget.Latest,true)}
function find(sf,p){let out;function walk(n){if(!out&&p(n))out=n;if(!out)ts.forEachChild(n,walk)}walk(sf);assert(out,'AST missing');return out;}
function variable(file,name,ctx){const sf=ast(file),n=find(sf,n=>ts.isVariableDeclaration(n)&&n.name?.text===name);return vm.runInContext('('+n.initializer.getText(sf)+')',ctx)}
function method(file,name,ctx){const sf=ast(file),n=find(sf,n=>ts.isMethodDeclaration(n)&&n.name?.text===name);return vm.runInContext(ts.transpileModule('({'+n.getText(sf)+'})['+JSON.stringify(name)+']',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx)}
function callback(file,expression,event,ctx){const sf=ast(file),n=find(sf,n=>ts.isCallExpression(n)&&n.expression.getText(sf)===expression&&n.arguments[0]?.text===event);return vm.runInContext(ts.transpileModule('('+n.arguments[1].getText(sf)+')',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx)}
function hub(e){return e.load('src/hub.ts','export const audit={startHub,createSession,closeSession,forkEndpoint,rewindContext,saveSessionMeta,archiveSession,unarchiveSession,shutdownHub,_flushBuf,persistReplayFile,routeEvent,submit,dropContext,openSseMulti,getContext,setCwdEndpoint,updateConfig,setAutoApprove,uploadImage,serveUpload,readBody,updateTitle,flushPtyBuffer,setSubagentModel,setSubagentBudget,loadArchivedSessions,listSessions,restoreSessions,_writeLocks};').audit}
async function create(extra={}){const e=env(extra),h=hub(e),ss=new Map(),s=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir);return{e,h,ss,s}}
const frame=f=>JSON.parse(f.split('data: ')[1]);
async function check(id,fn){try{const detail=await fn();findings.push({id,passed:true,detail});console.log('PASS',id,JSON.stringify(detail))}catch(e){findings.push({id,passed:false,error:e.stack});console.log('FAIL',id,e.stack)}}
function acp(){const calls=[],child=new EventEmitter();child.stdout=new EventEmitter();child.stdout.setEncoding=()=>{};child.kill=()=>{};child.stdin=Object.assign(new EventEmitter(),{writable:true,end(){},write:raw=>{const m=JSON.parse(raw);calls.push(m);if(m.method==='initialize'||m.method==='session/new'||m.method==='session/load'||m.method==='session/prompt')queueMicrotask(()=>child.stdout.emit('data',JSON.stringify({jsonrpc:'2.0',id:m.id,result:m.method==='initialize'?{protocolVersion:1,agentCapabilities:{loadSession:true}}:m.method==='session/new'?{sessionId:'remote'}:{stopReason:'end_turn'}})+'\n'));}});const e=env({modules:{'node:child_process':{spawn:()=>child}}}),A=e.load('src/bridges/acp.ts').AcpBridge;return{e,A,calls,child}}
const watchdog=setTimeout(()=>{console.error('AUDIT TIMEOUT');process.exit(1)},30000);
(async()=>{
await check('U01 empty rewind does not restore stale replay',async()=>{
 let fail=false;const real=require('fs');const {e,h,s,ss}=await create({modules:{'node:fs':{...real,promises:{...real.promises,writeFile:async(file,...args)=>{if(fail&&String(file).endsWith('.replay.jsonl.tmp'))throw Error('ENOSPC');return real.promises.writeFile(file,...args)}}}}});
 await h.submit(req({query:'removed private query'}),new Res(),s);await tick();await s.contextLock;await h.persistReplayFile(s.id,s.replay);fail=true;const r=new Res();const context=new Res();await h.getContext(context,s);await h.rewindContext(req({toIndex:0,revision:JSON.parse(context.body).revision}),r,s);assert(r.statusCode===200&&s.store.buildMessages().length===0,'rewind failed');await h.shutdownHub(undefined,ss);fail=false;
 const restored=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir,{id:s.id,title:'saved',startedAt:1,replay:[]});await restored._ensureBridge();const queries=restored.replay.map(frame).filter(f=>f.meta.name==='agent:query').map(f=>f.payload.query);assert(restored.store.buildMessages().length===0&&!queries.includes('removed private query'),'stale replay returned');return{contextCount:restored.bridge.messages.length,visibleQueries:queries};
});
await check('U02 partial append rollback preserves retry on reload',async()=>{
 let fail=false;const real=require('fs/promises'),e=env({modules:{'node:fs/promises':{...real,appendFile:async(file,data,...args)=>{if(fail){await real.appendFile(file,data.slice(0,15),...args);throw Error('ENOSPC partial append')}return real.appendFile(file,data,...args)}}}}),Store=e.load('src/history/session-store.ts').SessionStore,file=path.join(e.dir,'tree.jsonl'),s=new Store(file,{create:{cwd:e.dir,sessionId:'aaaaaa'}});await s.appendMessages([{role:'user',content:'one'}]);fail=true;try{await s.appendMessages([{role:'assistant',content:'two'}])}catch{}fail=false;await s.appendMessages([{role:'assistant',content:'two'}]);const loaded=new Store(file);assert(s.buildMessages().length===2&&loaded.buildMessages().length===2,'partial append corrupted retry');return{live:s.buildMessages().map(m=>m.content),reloaded:loaded.buildMessages().map(m=>m.content)};
});
await check('U03 legacy upgrade preserves rich event history',async()=>{
 const {e,h,s,ss}=await create();await h.submit(req({query:'question'}),new Res(),s);await tick();await s.contextLock;h.routeEvent(s,{name:'shell:command-start',payload:{command:'echo rich-history'}});h.routeEvent(s,{name:'shell:command-done',payload:{stdout:'important output'}});await h.shutdownHub(undefined,ss);fs.unlinkSync(path.join(e.dir,'hub-sessions',s.id+'.replay-state.json'));
 const restored=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir,{id:s.id,title:'legacy',startedAt:1,replay:[]});await restored._ensureBridge();assert(restored.replay.some(f=>f.includes('important output')),'legacy rich history lost');await h.updateTitle(req({title:'renamed'}),new Res(),restored);await h.shutdownHub(undefined,ss);assert(fs.readFileSync(path.join(e.dir,'hub-sessions',s.id+'.replay.jsonl'),'utf8').includes('important output'),'old replay overwritten');return{legacyShellOutputLost:false};
});
await check('U04 ACP stream errors are handled',async()=>{
 const {A,child}=acp(),b=new A({extra:{command:'fake'}});b.onError(()=>{});await b.ready();let error;try{child.stdin.emit('error',Object.assign(Error('write EPIPE'),{code:'EPIPE'}))}catch(e){error=e.message}assert(!error&&child.stdin.listenerCount('error')===1,'stdin error escaped');return{uncaught:error,stdinErrorListeners:child.stdin.listenerCount('error')};
});
await check('U05 initializing session observes disabled auto approval',async()=>{
 const e=env(),h=hub(e),ss=new Map(),file=path.join(e.dir,'settings.json');fs.writeFileSync(file,JSON.stringify({'ashub.permissions.autoApprove':true}));let release,started,b;const gate=new Promise(r=>release=r),ready=new Promise(r=>started=r);
 Object.assign(e.context,{fs,path,CONFIG_DIR:e.dir});const sf=ast('src/bridges/ash.ts'),init=find(sf,n=>ts.isMethodDeclaration(n)&&n.name?.text==='init');const initializeApproval=vm.runInContext('(async function(){'+init.body.statements[0].getText(sf)+'})',e.context);const creating=h.createSession(ss,{makeBridge:o=>{b=new Bridge(o);b.autoApprove=false;b.setAutoApprove=v=>b.autoApprove=v;b.ready=async()=>{await initializeApproval.call(b);started();await gate};return b}},e.dir);await ready;const r=new Res();await h.setAutoApprove(req({autoApprove:false}),r,ss);release();await creating;assert(r.statusCode===200&&b.autoApprove===false&&JSON.parse(fs.readFileSync(file))['ashub.permissions.autoApprove']===false,'startup approval state synchronized');return{acknowledged:false,newSessionApproval:b.autoApprove};
});
await check('U06 shutdown prevents late startup listening',async()=>{
 let release,started,blocked=false,listens=0,listened;const listening=new Promise(r=>listened=r);const gate=new Promise(r=>release=r),ready=new Promise(r=>started=r),real=require('fs');const http={createServer:()=>({close:f=>f(),listen(){listens++;listened()}})};
 const e=env({modules:{'node:http':http,'node:fs':{...real,promises:{...real.promises,readdir:async(...a)=>{if(!blocked){blocked=true;started();await gate}return real.promises.readdir(...a)}}}}});const h=hub(e),app=h.startHub({host:'127.0.0.1',port:0,webRoot:path.join(root,'web'),makeBridge:o=>new Bridge(o)});await ready;const shuttingDown=app.shutdown();assert(listens===0,'already listening');release();await shuttingDown;assert(listens===0,'shutdown allowed late listen');return{listensAfterShutdown:listens};
});
await check('U07 failed unarchive rolls back and can retry',async()=>{
 let fail=false;const real=require('fs'),{e,h,s,ss}=await create({modules:{'node:fs':{...real,promises:{...real.promises,rename:async(from,to)=>{if(fail&&String(to).includes('archived'))throw Error('EACCES');return real.promises.rename(from,to)}}}}});await h.archiveSession(req({id:s.id}),new Res(),ss);fail=true;const r=new Res();await h.unarchiveSession(req({id:s.id}),r,ss,{makeBridge:o=>new Bridge(o)});assert(r.statusCode===500&&!ss.has(s.id)&&(await h.loadArchivedSessions()).has(s.id),'unarchive rollback missing');fail=false;const retry=new Res();await h.unarchiveSession(req({id:s.id}),retry,ss,{makeBridge:o=>new Bridge(o)});assert(retry.statusCode===200&&ss.has(s.id)&&!(await h.loadArchivedSessions()).has(s.id),'retry failed');return{firstStatus:r.statusCode,retryStatus:retry.statusCode,activeAndArchived:false};
});
await check('U08 failed subagent settings return failure',async()=>{
 const {e,h,s}=await create();Object.assign(e.context,{path,CONFIG_DIR:e.dir,updateSettingsFile:()=>{throw Error('ENOSPC')},reloadSettings(){},SUBAGENT_TYPES:{implement:{}},REASONING_LEVELS:new Set(['high'])});const handler=callback('src/bridges/ash.ts','core.handlers.define','subagent:set-budget',e.context);s.bridge.execCommand=(name,args)=>handler(JSON.parse(args));const r=new Res();await h.setSubagentBudget(req({type:'implement',budgetTokens:10000}),r,s);assert(r.statusCode===500&&!fs.existsSync(path.join(e.dir,'settings.json')),'write failure hidden');return{status:r.statusCode,fileExists:false};
});
await check('U09 ACP image requests are explicitly rejected',async()=>{
 const {e,A,calls}=acp(),h=hub(e),s=await h.createSession(new Map(),{makeBridge:o=>new A({...o,extra:{command:'fake'}})},e.dir),r=new Res();await h.submit(req({query:'describe image',images:[{data:'YQ==',mimeType:'image/png'}]}),r,s);await tick();const prompt=calls.find(c=>c.method==='session/prompt');assert(r.statusCode===409&&!prompt,'images silently dropped');return{status:r.statusCode,remotePrompt:prompt};
});
await check('U10 auto approval rejects non-boolean input',async()=>{
 const {e,h,ss}=await create();const r=new Res();await h.setAutoApprove(req({autoApprove:'false'}),r,ss);assert(r.statusCode===400&&!fs.existsSync(path.join(e.dir,'settings.json')),'invalid boolean accepted');return{status:r.statusCode};
});
await check('U11 incompatible backend restoration is rejected',async()=>{
 const {e,A}=acp(),h=hub(e),ss=new Map(),s=await h.createSession(ss,{makeBridge:o=>new A({...o,extra:{command:'fake'}})},e.dir);await h.submit(req({query:'important earlier conversation'}),new Res(),s);await tick();await h.shutdownHub(undefined,ss);
 const meta=JSON.parse(fs.readFileSync(path.join(e.dir,'hub-sessions',s.id+'.meta.json')));const restored=await h.createSession(ss,{makeBridge:o=>Object.assign(new Bridge(o),{backendId:'ash'})},e.dir,{...meta,replay:[]});let rejected=false;try{await restored._ensureBridge()}catch{rejected=true}assert(rejected&&!restored.bridge&&restored.replay.some(f=>f.includes('important earlier conversation')),'incompatible backend migration accepted');return{rejected,oldHistoryRetained:true};
});
await check('U12 stale context deletion is rejected',async()=>{
 const {h,s}=await create();s.bridge.messages=[{role:'user',content:'old 0'},{role:'assistant',content:'old 1'},{role:'user',content:'old 2'}];await s.capture.flush();const context=new Res();await h.getContext(context,s);const revision=context.json().revision;const oldLeaf=s.store.getActiveLeaf();const other=await s.store.appendMessages([{role:'user',content:'new 0'},{role:'assistant',content:'new 1'},{role:'user',content:'new 2'}],s.store.getRootId());s.store.setActiveLeaf(oldLeaf);const q=new EventEmitter(),r=new Res(),dropping=h.dropContext(q,r,s);await h.forkEndpoint(req({entryId:other.at(-1)}),new Res(),s);q.emit('data',Buffer.from(JSON.stringify({indices:[2],revision})));q.emit('end');await dropping;assert(r.statusCode===409&&s.bridge.messages.some(m=>m.content==='new 2'),'stale drop accepted');return{intendedToDrop:'old 2',actuallyDropped:null,status:r.statusCode};
});
await check('U13 show key preserves unsaved edits',async()=>{
 const u=ui(),provider=new El(),key=new El(),toggle=new El();provider.value='A';key.value='FAKE-NEW-UNSAVED-KEY';Object.assign(u.e.context,{configProvider:provider,configApikey:key,configApikeyToggle:toggle,apiKeyVisible:false,apiKeyRequest:0,_maskedApiKey:'',_revealedApiKey:'',originalApiKey:'masked old',fetch:async()=>({ok:true,json:async()=>({apiKey:'FAKE-OLD-STORED-KEY'})})});await callback('web/js/config-panel.js','configApikeyToggle?.addEventListener','click',u.e.context)();assert(key.value==='FAKE-NEW-UNSAVED-KEY','unsaved key overwritten');return{typed:'FAKE-NEW-UNSAVED-KEY',afterReveal:key.value};
});
await check('U14 closed-session context response is ignored',async()=>{
 const u=ui(),body=new El(),meta=new El(),ctx={selected:new Set(),currentMsgs:[],currentGroups:[]};let sid='aaaaaa',release;const response=new Promise(r=>release=r);Object.assign(u.e.context,{ctx:()=>sid?ctx:null,currentSessionId:()=>sid,ctxBody:body,ctxMeta:meta,ctxFetchAbort:null,ctxFetchSeq:0,t:x=>x,escape:x=>x,updateDropButton(){},computeGroups:()=>[],currentGroupsArr:()=>[],fmtTok:x=>x,fetch:()=>response});const render=variable('web/js/context-panel.js','renderContext',u.e.context),first=render();sid='';await render();const empty=body.innerHTML;release({ok:true,json:async()=>({messages:[]})});await first;assert(empty==='\u003cdiv class="p-empty">ctx.no.session\u003c/div>'&&body.innerHTML===empty,'stale result accepted');return{afterClosing:empty,afterOldResponse:body.innerHTML};
});
await check('U15 terminal deletion failure preserves tab and reports error',async()=>{
 const u=ui();u.modules['./store.js']={activeSessionId:signal('aaaaaa'),openTabs:signal(['aaaaaa'])};u.e.context.fetch=async()=>({ok:false,status:500,text:async()=>'delete failed'});const view=new El(),m={sessions:new Map([['aaaaaa',view]]),sessionKinds:new Map([['aaaaaa','terminal']]),openTabs:signal(['aaaaaa']),activeSessionId:signal('aaaaaa')};Object.assign(u.e.context,{...m,switchTo(){},closingTerminals:new Set(),toast:msg=>u.toasts.push(msg)});await variable('web/js/session-manager.js','closeTab',u.e.context)('aaaaaa');assert(!view.removed&&m.openTabs.peek().includes('aaaaaa')&&u.toasts.length===1,'failed terminal deletion hidden');return{viewRemoved:view.removed,remainingTabs:m.openTabs.peek(),errorsShown:u.toasts.length};
});

await check('U16 failed startup preserves history and supports retry',async()=>{
 let fail=false;const real=require('fs'),e=env({modules:{'node:fs':{...real,promises:{...real.promises,writeFile:async(file,...args)=>{if(fail&&String(file).endsWith('.meta.json.tmp'))throw Error('ENOSPC');return real.promises.writeFile(file,...args)}}}}}),h=hub(e),dir=path.join(e.dir,'hub-sessions');fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'aaaaaa.meta.json'),JSON.stringify({id:'aaaaaa',title:'',cwd:e.dir,kind:'agent',startedAt:1}));const Store=e.load('src/history/session-store.ts').SessionStore,store=new Store(path.join(dir,'aaaaaa.jsonl'),{create:{cwd:e.dir,sessionId:'aaaaaa'},metaPath:path.join(dir,'aaaaaa.meta.json')});await store.appendMessages([{role:'user',content:'valuable existing conversation'}]);fail=true;const sessions=new Map();await h.restoreSessions(sessions,{makeBridge:o=>new Bridge(o)});assert(fs.existsSync(path.join(dir,'aaaaaa.jsonl'))&&fs.existsSync(path.join(dir,'aaaaaa.meta.json')),'failed restore deleted history');fail=false;await h.restoreSessions(sessions,{makeBridge:o=>new Bridge(o)});assert(sessions.has('aaaaaa'),'restore retry failed');return{historyDeleted:false,activeSessions:sessions.size};
});
await check('U17 terminal cleanup failure does not abort other restores',async()=>{
 const real=require('fs'),e=env({modules:{'node:fs':{...real,promises:{...real.promises,unlink:async(file)=>{if(String(file).endsWith('aaaaaa.meta.json'))throw Object.assign(Error('EACCES'),{code:'EACCES'});return real.promises.unlink(file)}}}}}),h=hub(e),dir=path.join(e.dir,'hub-sessions');fs.mkdirSync(dir,{recursive:true});for(const [id,kind,time] of [['aaaaaa','terminal',2],['bbbbbb','agent',1]])fs.writeFileSync(path.join(dir,id+'.meta.json'),JSON.stringify({id,kind,title:id,cwd:e.dir,startedAt:time,lastModified:time}));const sessions=new Map();let error;try{await h.restoreSessions(sessions,{makeBridge:o=>new Bridge(o)})}catch(e){error=e.message}assert(!error&&sessions.has('bbbbbb')&&fs.existsSync(path.join(dir,'bbbbbb.meta.json')),'cleanup failure prevented restoration');return{error,agentRestored:true,agentDataStillExists:true};
});
await check('U18 late folder expansion cannot cross sessions',async()=>{
 const u=ui(),a=new Map(),b=new Map(),row=new El();let active=a,release;row.dataset.path='src';row.after=el=>row.added=el;u.doc.createDocumentFragment=()=>new El();const response=new Promise(r=>release=r);Object.assign(u.e.context,{expandedDirs:()=>active,fetchSubdir:()=>response,makeEntryEl:()=>new El()});const expand=variable('web/js/files-panel.js','toggleDir',u.e.context);const p=expand(row);active=b;row.isConnected=false;release({files:[{name:'A-private-file',kind:'file'}]});await p;assert(!b.has('src')&&!a.has('src'),'expansion crossed sessions');return{originHasExpansion:a.has('src'),otherSessionHasStaleExpansion:b.has('src')};
});

await check('U02 concurrent appends commit sequentially and survive reload',async()=>{
 const e=env(),Store=e.load('src/history/session-store.ts').SessionStore,file=path.join(e.dir,'tree.jsonl'),s=new Store(file,{create:{cwd:e.dir,sessionId:'aaaaaa'}});await Promise.all([s.appendMessages([{role:'user',content:'one'}]),s.appendMessages([{role:'assistant',content:'two'}])]);assert(new Store(file).buildMessages().map(m=>m.content).join('|')==='one|two','concurrent append lost a message');
});
await check('U02 failed compaction append rolls back and remains retryable',async()=>{
 let fail=false;const real=require('fs/promises'),e=env({modules:{'node:fs/promises':{...real,appendFile:async(file,data,...args)=>{if(fail){await real.appendFile(file,data.slice(0,20),...args);throw Error('partial')}return real.appendFile(file,data,...args)}}}}),Store=e.load('src/history/session-store.ts').SessionStore,file=path.join(e.dir,'tree.jsonl'),s=new Store(file,{create:{cwd:e.dir,sessionId:'aaaaaa'}});const ids=await s.appendMessages([{role:'user',content:'one'},{role:'assistant',content:'two'}]);const before=fs.readFileSync(file,'utf8');fail=true;try{await s.appendCompaction(ids[1])}catch{}assert(fs.readFileSync(file,'utf8')===before,'failed compaction changed durable history');fail=false;await s.appendCompaction(ids[1]);assert(JSON.stringify(s.buildMessages())===JSON.stringify(new Store(file).buildMessages()),'compaction retry diverged');
});
await check('U02 failed truncation refuses queued and subsequent writes',async()=>{
 let fail=false;const real=require('fs/promises'),e=env({modules:{'node:fs/promises':{...real,appendFile:async(file,data,...args)=>{if(fail){await real.appendFile(file,data.slice(0,20),...args);throw Error('partial')}return real.appendFile(file,data,...args)},truncate:async()=>{throw Error('cannot rollback')}}}}),Store=e.load('src/history/session-store.ts').SessionStore,file=path.join(e.dir,'tree.jsonl'),s=new Store(file,{create:{cwd:e.dir,sessionId:'aaaaaa'}});await s.appendMessages([{role:'user',content:'one'}]);fail=true;const outcomes=await Promise.allSettled([s.appendMessages([{role:'assistant',content:'two'}]),s.appendMessages([{role:'user',content:'three'}])]);assert(outcomes.every(r=>r.status==='rejected'),'queued append accepted after failed rollback');let rejected=false;try{await s.appendMessages([{role:'user',content:'four'}])}catch{rejected=true}assert(rejected,'poisoned store accepted append');
});
await check('U04 transport failure rejects pending and future ACP requests',async()=>{
 const {A,child}=acp(),b=new A({extra:{command:'fake'}});await b.ready();child.stdin.write=()=>{};const pending=b.submit('waiting').then(()=>false,()=>true);await tick();child.stdin.emit('error',Error('EPIPE'));assert(await pending,'pending request hung');assert(await b.submit('later').then(()=>false,()=>true),'future request accepted');
});
await check('U08 actual command dispatch propagates both settings failures',async()=>{
 const {e,h,s}=await create();Object.assign(e.context,{path,CONFIG_DIR:e.dir,updateSettingsFile:()=>{throw Error('ENOSPC')},reloadSettings(){},SUBAGENT_TYPES:{implement:{}},REASONING_LEVELS:new Set(['high'])});const handlers={};for(const event of ['subagent:set-model','subagent:set-budget'])handlers[event]=callback('src/bridges/ash.ts','core.handlers.define',event,e.context);s.bridge.core={handlers:{call:(name,arg)=>handlers[name](arg)}};s.bridge.execCommand=method('src/bridges/ash.ts','execCommand',e.context);for(const [fn,body] of [[h.setSubagentModel,{type:'implement',model:'test'}],[h.setSubagentBudget,{type:'implement',budgetTokens:100}]]){const r=new Res();await fn(req(body),r,s);assert(r.statusCode===500,'command dispatcher swallowed settings error');}
});
await check('U09 direct ACP image submission rejects without sending prompt',async()=>{
 const {A,calls}=acp(),b=new A({extra:{command:'fake'}});await b.ready();const rejected=await b.submit(JSON.stringify({query:'image',images:[{data:'YQ==',mimeType:'image/png'}]})).then(()=>false,()=>true);assert(rejected&&!calls.some(c=>c.method==='session/prompt'),'direct submit lost images');await b.submit('ordinary text');assert(calls.at(-1).params.prompt[0].text==='ordinary text','text submit broken');
});
await check('U11 compatible ACP restore retains original backend identity',async()=>{
 const {e,A}=acp(),h=hub(e),ss=new Map(),s=await h.createSession(ss,{makeBridge:o=>new A({...o,extra:{command:'fake'}})},e.dir);await h.submit(req({query:'prior'}),new Res(),s);await tick();await h.shutdownHub(undefined,ss);const meta=JSON.parse(fs.readFileSync(path.join(e.dir,'hub-sessions',s.id+'.meta.json')));assert(meta.backendId==='acp','backend identity not saved');const restored=await h.createSession(ss,{makeBridge:o=>new A({...o,extra:{command:'fake'}})},e.dir,{...meta,replay:[]});await restored._ensureBridge();assert(restored.bridge.backendId==='acp'&&restored.replay.some(f=>f.includes('prior')),'compatible history lost');
});
await check('U11 mismatched bridge constructors refuse before initialization',async()=>{
 const {A,calls}=acp();let rejected=false;try{new A({restoreBackend:'ash',extra:{command:'fake'}})}catch{rejected=true}assert(rejected&&calls.length===0,'ACP child initialized for Ash history');const e=env(),sf=ast('src/bridges/ash.ts'),ctor=find(sf,n=>ts.isConstructorDeclaration(n));const js=ts.transpileModule('(class extends Object {backendId="ash";'+ctor.getText(sf)+'})',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,C=vm.runInContext(js,e.context);rejected=false;try{new C({restoreBackend:'acp'})}catch(err){rejected=err.message.includes('another backend')}assert(rejected,'Ash initialized for ACP history');
});
await check('U12 current revision succeeds and missing or stale revisions are refused',async()=>{
 const {h,s}=await create();s.bridge.messages=[{role:'user',content:'one'},{role:'assistant',content:'two'}];await s.capture.flush();const context=new Res();await h.getContext(context,s);const revision=context.json().revision;const missing=new Res();await h.dropContext(req({indices:[0]}),missing,s);assert(missing.statusCode===409,'missing revision accepted');s.bridge.messages.push({role:'user',content:'three'});const stale=new Res();await h.dropContext(req({indices:[0],revision}),stale,s);assert(stale.statusCode===409,'same-branch changed context accepted');const fresh=new Res();await h.getContext(fresh,s);const ok=new Res();await h.dropContext(req({indices:[0],revision:fresh.json().revision}),ok,s);assert(ok.statusCode===200&&s.bridge.messages.some(m=>m.content==='three'),'fresh deletion failed');
});
await check('U13 unchanged placeholder still reveals saved key and hides it again',async()=>{
 const u=ui(),provider=new El(),key=new El(),toggle=new El();provider.value='A';key.value='masked';Object.assign(u.e.context,{configProvider:provider,configApikey:key,configApikeyToggle:toggle,apiKeyVisible:false,apiKeyRequest:0,_maskedApiKey:'',_revealedApiKey:'',originalApiKey:'masked',fetch:async()=>({ok:true,json:async()=>({apiKey:'FAKE-KEY'})})});const reveal=callback('web/js/config-panel.js','configApikeyToggle?.addEventListener','click',u.e.context);await reveal();assert(key.value==='FAKE-KEY'&&key.type==='text','saved key no longer revealed');await reveal();assert(key.value==='masked'&&key.type==='password','hide failed');
});
await check('U15 terminal delete deduplicates and success preserves newly active tab',async()=>{
 const u=ui(),view=new El();let release,calls=0;const response=new Promise(r=>release=r),m={sessions:new Map([['aaaaaa',view]]),sessionKinds:new Map([['aaaaaa','terminal']]),openTabs:signal(['aaaaaa','bbbbbb']),activeSessionId:signal('aaaaaa')};Object.assign(u.e.context,{...m,closingTerminals:new Set(),switchTo:id=>m.activeSessionId.value=id,toast:msg=>u.toasts.push(msg),fetch:()=>{calls++;return response}});const close=variable('web/js/session-manager.js','closeTab',u.e.context),p=close('aaaaaa');await close('aaaaaa');assert(calls===1&&m.openTabs.peek().includes('aaaaaa'),'terminal close duplicate or premature');m.activeSessionId.value='bbbbbb';release({ok:true});await p;assert(view.removed&&m.activeSessionId.peek()==='bbbbbb'&&m.openTabs.peek().join()==='bbbbbb','success changed another tab');
});
await check('U18 same-session folder expansion and collapse still work',async()=>{
 const u=ui(),cache=new Map(),row=new El();row.dataset.path='src';row.after=el=>row.added=el;u.doc.createDocumentFragment=()=>new El();Object.assign(u.e.context,{expandedDirs:()=>cache,fetchSubdir:async()=>({files:[{name:'file',kind:'file'}]}),makeEntryEl:()=>new El()});const expand=variable('web/js/files-panel.js','toggleDir',u.e.context);await expand(row);assert(cache.has('src'),'folder not expanded');await expand(row);assert(!cache.has('src')&&row.added.removed,'folder not collapsed');
});

await check('U09 JSON literals remain valid ACP text prompts',async()=>{
 const {A,calls}=acp(),b=new A({extra:{command:'fake'}});await b.ready();for(const text of ['null','42','false','{"query":"just text"}']){await b.submit(text);assert(calls.at(-1).params.prompt[0].text===text,'JSON text was misclassified');}
});
await check('U15 closing an unopened terminal is a no-op',async()=>{
 const u=ui();let calls=0;Object.assign(u.e.context,{openTabs:signal([]),closingTerminals:new Set(),sessionKinds:new Map([['aaaaaa','terminal']]),fetch:()=>{calls++}});await variable('web/js/session-manager.js','closeTab',u.e.context)('aaaaaa');assert(calls===0,'closed an unopened terminal');
});

clearTimeout(watchdog);console.log(JSON.stringify({checks:findings.length,passed:findings.filter(f=>f.passed).length}));if(findings.some(f=>!f.passed))process.exitCode=1;
})().catch(e=>{clearTimeout(watchdog);console.error(e);process.exitCode=1});
