const {ui,El,signal}=require('./ui-harness.cjs');
const {assert,check,results}=require('./harness.cjs');
const {deepStrictEqual}=require('node:assert');
const tick=()=>new Promise(setImmediate), response=x=>({ok:true,json:async()=>x});
const prove=check;
const cfg={defaultProvider:'custom',providers:{custom:{apiKey:'masked',baseURL:'http://localhost/v1',models:['private-model'],defaultModel:'private-model'}},custom:'keep'};
function config(){const u=ui();u.e.context.CustomEvent=u.e.context.Event;u.doc.getElementById('config-auto-approve').closest=()=>null;u.modules['./sse.js']={invalidateModelCache(){},getModelCacheGeneration(){},setModelCache(){}};u.e.context.fetch=async url=>response(url==='/api/models'?{providers:[{name:'custom',models:[{id:'private-model'}]}]}:structuredClone(cfg));const m=u.e.load('web/js/config-panel.js');const el=id=>u.doc.getElementById(id);const mode=x=>el('config-mode-tabs').events.click[0]({target:{closest:()=>({dataset:{mode:x}})}});return{...u,m,el,mode};}
(async()=>{
 await prove('R16 simple save preserves custom model definitions',async()=>{const u=config();await u.m.setConfigOpen(true);let written;u.e.context.fetch=async(url,opts)=>{written=JSON.parse(opts.body);return response({})};await u.el('config-save-simple').events.click[0]();deepStrictEqual(written.providers,cfg.providers);return {before:cfg.providers.custom,after:written.providers.custom};});
 await prove('R16 incomplete advanced JSON stays in editor on attempted mode switch',async()=>{const u=config();await u.m.setConfigOpen(true);u.mode('advanced');const draft='{"custom":"unfinished';u.el('config-editor').value=draft;u.mode('simple');u.mode('advanced');const actual=u.el('config-editor').value;assert(actual===draft&&!u.el('config-invalid').hidden);return {before:draft,after:actual};});
 await prove('R16 terminal file directories expand and collapse',async()=>{const u=ui();u.doc.getElementById('files-panel').hasAttribute=()=>true;u.doc.createDocumentFragment=()=>new El();u.active.value={id:'bbbbbb'};let urls=[];u.e.context.fetch=async url=>{urls.push(url);return response({files:[{name:'child.txt',kind:'file'}]})};const m=u.e.load('web/js/files-panel.js','export const audit={toggleDir,expandedDirs};');const row=new El();row.dataset.path='src';row.after=x=>row.inserted=x;await m.audit.toggleDir(row);assert(row.classList.contains('expanded')&&row.inserted&&m.audit.expandedDirs()===m.audit.expandedDirs());await m.audit.toggleDir(row);assert(!row.classList.contains('expanded')&&row.inserted.removed);return{urls,expanded:row.classList.contains('expanded'),stableState:m.audit.expandedDirs()===m.audit.expandedDirs()};});
 await prove('R16 file load failure clears previous session cwd',async()=>{const u=ui();u.doc.getElementById('files-panel').hidden=true;u.active.peek().files={expandedDirs:new Map()};u.e.context.fetch=async()=>response({cwd:'/project-A',files:[]});const m=u.e.load('web/js/files-panel.js','export const audit={fetchFiles};');await m.audit.fetchFiles();u.active.value={id:'bbbbbb',files:{expandedDirs:new Map()}};u.e.context.fetch=async()=>({ok:false,status:500});await m.audit.fetchFiles();assert(u.doc.getElementById('files-cwd').textContent===''&&u.doc.getElementById('files-cwd').title==='');return {activeSession:'bbbbbb',displayedCwd:u.doc.getElementById('files-cwd').textContent,error:u.doc.getElementById('files-empty').innerHTML};});
 await prove('R16 tree confirmation cannot submit old entry to newly active session',async()=>{const u=ui();u.doc.getElementById('tree-panel').hidden=true;let resolve;u.e.context.fetch=()=>new Promise(r=>resolve=r);const m=u.e.load('web/js/tree-panel.js','export const audit={refresh,confirmFork};');const body=u.doc.getElementById('tree-body');body.innerHTML='rows from A';const row=new El();row.dataset.entryId='entry-from-A';m.audit.confirmFork(row,'entry-from-A','aaaaaa',0);u.active.value={id:'bbbbbb',state:{isProcessing:false}};m.audit.refresh();assert(body.innerHTML!=='rows from A');let sent;u.e.context.fetch=async(url,opts)=>{sent={url,body:opts.body};return{ok:false,text:async()=>'entry not found'}};m.audit.confirmFork(row,'entry-from-A','aaaaaa',0);await tick();assert(!sent);return {sent:false};});
 await prove('R16 onboarding follows saves and rejects stale config/catalog responses',async()=>{
 const u=ui(),panel=u.doc.getElementById('no-session-empty'),templates=panel.querySelector('.stream-empty-templates'),button=new El();let inserts=0;
 templates.querySelectorAll=()=>[button];templates.after=()=>inserts++;
 u.modules['./session-manager.js']={activeSessionId:signal(''),activeSession:u.active,openTab(){}};u.modules['./sidebar.js']={createSession:async()=>null};u.modules['./i18n.js'].lang=signal('zh');
 u.modules['./config-panel.js']={loadProviderCatalog:async()=>({providers:[{name:'custom'}]}),providerLabel:x=>x,saveProviderApiKey:async()=>true};let configured=false;
 const fetchConfig=async()=>response({anyProviderConfigured:configured});u.e.context.fetch=fetchConfig;
 const m=u.e.load('web/js/no-session.js','export const audit={getOnboarding:()=>onboardingEl,checkFirstRun};');await tick();assert(button.disabled&&m.audit.getOnboarding());
 configured=true;u.doc.dispatchEvent({type:'ash:models-changed'});await tick();assert(!button.disabled&&!m.audit.getOnboarding());
 let finish;u.e.context.fetch=()=>new Promise(r=>finish=r);const old=m.audit.checkFirstRun();u.e.context.fetch=fetchConfig;await m.audit.checkFirstRun();finish(response({anyProviderConfigured:false}));await old;assert(!button.disabled&&!m.audit.getOnboarding());
 let catalogReady;u.modules['./config-panel.js'].loadProviderCatalog=()=>new Promise(r=>catalogReady=r);configured=false;const pending=m.audit.checkFirstRun();await tick();configured=true;await m.audit.checkFirstRun();catalogReady({providers:[]});await pending;assert(!button.disabled&&!m.audit.getOnboarding()&&inserts===1);
 u.modules['./config-panel.js'].loadProviderCatalog=async()=>({providers:[]});configured=false;await m.audit.checkFirstRun();assert(button.disabled&&m.audit.getOnboarding()&&inserts===2);
 });
 await check('R16 valid settings roundtrip preserves model capabilities and advanced edits',async()=>{const u=config();await u.m.setConfigOpen(true);u.mode('advanced');const draft=JSON.parse(u.el('config-editor').value);draft.providers.custom.models=[{id:'vision',modalities:['text','image'],contextWindow:32000}];draft.custom='edited';u.el('config-editor').value=JSON.stringify(draft);u.mode('simple');u.mode('advanced');const actual=JSON.parse(u.el('config-editor').value);assert(JSON.stringify(actual.providers)===JSON.stringify(draft.providers)&&actual.custom==='edited');});
 for(const draft of ['null','[]']) await check('R16 nonobject settings cannot replace simple form: '+draft,async()=>{const u=config();await u.m.setConfigOpen(true);u.mode('advanced');u.el('config-editor').value=draft;u.mode('simple');u.mode('advanced');assert(u.el('config-editor').value===draft&&!u.el('config-invalid').hidden);let writes=0;u.e.context.fetch=async()=>{writes++;return response({})};await u.el('config-save').events.click[0]();assert(!writes);});
 await check('R16 fresh settings load recovers after closing an incomplete draft',async()=>{const u=config();await u.m.setConfigOpen(true);u.mode('advanced');u.el('config-editor').value='{bad';await u.m.setConfigOpen(false);await u.m.setConfigOpen(true);assert(!u.el('config-body-simple').inert&&u.el('config-body-simple').hidden===undefined&&JSON.parse(u.el('config-editor').value).custom==='keep');});
 await check('R16 terminal pending expansion ignores a different view',async()=>{const u=ui();u.doc.getElementById('files-panel').hasAttribute=()=>true;const m=u.e.load('web/js/files-panel.js','export const audit={toggleDir,expandedDirs};');u.active.value={id:'bbbbbb'};const row=new El();row.dataset.path='src';row.after=x=>row.inserted=x;const oldMap=m.audit.expandedDirs();let finish;u.e.context.fetch=()=>new Promise(r=>finish=r);const pending=m.audit.toggleDir(row);u.active.value={id:'cccccc'};assert(m.audit.expandedDirs()!==oldMap);finish(response({files:[]}));await pending;assert(!row.inserted&&!row.classList.contains('loading'));});
 await check('R16 file path clears while loading and recovers after retry',async()=>{const u=ui();u.doc.getElementById('files-panel').hasAttribute=()=>true;const m=u.e.load('web/js/files-panel.js','export const audit={fetchFiles};');u.doc.getElementById('files-cwd').textContent='/old';let finish;u.e.context.fetch=()=>new Promise(r=>finish=r);const pending=m.audit.fetchFiles();assert(u.doc.getElementById('files-cwd').textContent==='');finish(response({cwd:'/new',files:[]}));await pending;assert(u.doc.getElementById('files-cwd').textContent==='/new');});
 await check('R16 valid tree row submits rendered session and leaf',async()=>{const u=ui();let sent;u.e.context.fetch=async(url,opts)=>{if(opts?.method==='POST')sent={url,body:JSON.parse(opts.body)};return{ok:false,status:404,text:async()=>'fixture'}};const body=u.doc.getElementById('tree-body'),row=new El();row.dataset.entryId='leaf';body.querySelectorAll=()=>[row];const m=u.e.load('web/js/tree-panel.js','export const audit={render};');m.audit.render({rootId:'root',leafId:'root',entries:[{id:'root',type:'session'},{id:'leaf',parentId:'root',role:'user',preview:'branch'}]},'aaaaaa',0);row.events.click[0]();row.events.click[0]();await tick();assert(sent.url==='/aaaaaa/fork'&&sent.body.entryId==='leaf');});
 await check('R16 stale tree row is blocked after A to B to A navigation',async()=>{const u=ui(),m=u.e.load('web/js/tree-panel.js','export const audit={refresh,confirmFork};');const row=new El();row.dataset.entryId='old';m.audit.confirmFork(row,'old','aaaaaa',0);u.active.value={id:'bbbbbb'};u.e.context.fetch=async()=>({ok:false,status:404});await m.audit.refresh();u.active.value={id:'aaaaaa'};let writes=0;u.e.context.fetch=async()=>{writes++;return response({})};m.audit.confirmFork(row,'old','aaaaaa',0);assert(!writes);});
 console.log(JSON.stringify({checks:results.length,passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length}));
})();
