const {env,Res,req,assert,fs,path,check,results}=require('./harness.cjs');
const {ui,El}=require('./ui-harness.cjs');
const tick=()=>new Promise(setImmediate);
const skill=(dir,name)=>{fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'SKILL.md'),`---\nname: ${name}\ndescription: fixture\n---\nFixture body\n`)};
const response=(data,ok=true)=>({ok,status:ok?200:503,json:async()=>data,text:async()=>JSON.stringify(data)});
function realSkills(){const modules={},e=env({modules}),settings=e.load('node_modules/agent-sh/dist/core/settings.js');Object.assign(e.settings,{getSettings:settings.getSettings,reloadSettings:settings.reloadSettings});const kernel=e.load('node_modules/agent-sh/dist/agent/skills.js');modules['agent-sh/skills']=kernel;return{e,settings,kernel,h:e.hub()}}
const list=async(h)=>{const r=new Res();await h.listInstalledSkills(req({},'/api/skills/installed'),r);return r.json().installed};
function market(){const e=env(),h=e.load('src/hub.ts','export const audit={searchSkills};').audit;return{e,search:async(source)=>{const r=new Res();await h.searchSkills(req({},'/api/skills?'+(source?'source='+source:'')),r);return r}}}
function lifecycle(){const u=ui();let suspend,resume,paused=false,count=0;u.modules['./session-manager.js']={pauseSSE(){paused=true},resumeSSE(){paused=false;count++}};u.e.context.window.electronAPI={onSuspend:f=>suspend=f,onResume:f=>resume=f};u.e.load('web/js/lifecycle.js');return{u,suspend:()=>suspend(),resume:()=>resume(),state:()=>({paused,count}),flush:()=>{for(const [id,t] of [...u.e.timers]){u.e.timers.delete(id);t.fn()}}}}
(async()=>{
 await check('R19 saved skill paths immediately update real kernel and panel in both directions',async()=>{const {e,kernel,h}=realSkills(),dir=path.join(e.dir,'extra');skill(path.join(dir,'demo'),'demo');assert(kernel.discoverGlobalSkills().length===0);for(const [paths,count] of [[[dir],1],[[],0],[[dir],1]]){const r=new Res();await h.updateConfig(req({skillPaths:paths}),r,new Map());assert(r.statusCode===200);assert(kernel.discoverGlobalSkills().length===count);assert((await list(h)).length===count)}});
 await check('R19 invalid config preserves working skill settings',async()=>{const {e,kernel,h}=realSkills();skill(path.join(e.dir,'skills','demo'),'demo');assert(kernel.discoverGlobalSkills().length===1);const r=new Res();await h.updateConfig(req({skillPaths:[null]}),r,new Map());assert(r.statusCode===400&&kernel.discoverGlobalSkills().length===1)});
 for(const mode of ['absolute','tilde','relative','spaces'])await check('R19 standalone skill '+mode+' lists and uninstalls exact root',async()=>{const {e,kernel,h}=realSkills(),dir=path.join(e.os.homedir(),mode==='spaces'?'My Skill':'standalone');skill(dir,'fixture');const configured=mode==='tilde'?'~/standalone':mode==='relative'?path.relative(process.cwd(),dir):dir;fs.writeFileSync(path.join(e.dir,'settings.json'),JSON.stringify({skillPaths:[configured]}));assert(kernel.discoverGlobalSkills().length===1);const entries=await list(h);assert(entries.length===1&&entries[0].path===dir);const r=new Res();await h.uninstallSkill(req({name:entries[0].name,path:entries[0].path}),r);assert(r.statusCode===200&&!fs.existsSync(dir));assert(kernel.discoverGlobalSkills().length===0&&(await list(h)).length===0)});
 await check('R19 container deletion and traversal stay rejected',async()=>{const {e,h}=realSkills(),dir=path.join(e.dir,'extra');skill(path.join(dir,'demo'),'demo');fs.writeFileSync(path.join(e.dir,'settings.json'),JSON.stringify({skillPaths:[dir]}));for(const [name,target,status] of [['extra',dir,403],['..',path.dirname(dir),400],['../extra',dir,400],['a/b',dir,400],['a\\b',dir,400],['bad\0name',dir,400],['C:',dir,400]]){const r=new Res();await h.uninstallSkill(req({name,path:target}),r);assert(r.statusCode===status&&fs.existsSync(dir))}assert((await list(h))[0].name==='demo')});
 await check('R19 standalone uninstall retains source identity guard',async()=>{const {e,h}=realSkills(),dir=path.join(e.dir,'standalone');skill(dir,'demo');fs.writeFileSync(path.join(e.dir,'settings.json'),JSON.stringify({skillPaths:[dir]}));fs.writeFileSync(path.join(dir,'.ashub-source.json'),JSON.stringify({url:'https://github.com/owner/standalone.git',subdir:''}));assert((await list(h))[0].sourceId==='github:owner/standalone');const r=new Res();await h.uninstallSkill(req({name:'standalone',path:dir,sourceId:'github:other/standalone'}),r);assert(r.statusCode===409&&fs.existsSync(dir))});
 for(const source of ['gitee','github']){
  for(const failure of ['network','http'])await check('R19 '+source+' '+failure+' outage returns 502 without snapshot',async()=>{const m=market();m.e.context.fetch=async()=>{if(failure==='network')throw Error('offline');return response({},false)};const r=await m.search(source);assert(r.statusCode===502&&r.json().error&&!('skills' in r.json()))});
  await check('R19 '+source+' empty success is cached',async()=>{const m=market();let calls=0;m.e.context.fetch=async()=>{calls++;return response([])};const first=await m.search(source),n=calls;assert(first.statusCode===200&&first.json().skills.length===0&&!first.json().cached);await m.search(source);assert(calls===n)});
  await check('R19 '+source+' stale snapshot survives outage and retries',async()=>{const m=market();let offline=false,calls=0;m.e.context.fetch=async url=>{calls++;if(offline)throw Error('offline');return String(url).includes('api.github.com')?response([{name:'demo',type:'dir'}]):source==='gitee'?response([{name:'demo'}]):{ok:true,text:async()=>'---\nname: demo\ndescription: Test\n---\nBody'}};const initial=await m.search(source);assert(initial.json().skills.length>0);m.e.clock(3700001);offline=true;const stale=await m.search(source);assert(stale.statusCode===200&&stale.json().cached&&stale.json().skills.length===initial.json().skills.length);const n=calls;offline=false;const fresh=await m.search(source);assert(!fresh.json().cached&&calls>n)});
 }
 await check('R19 another source cache cannot hide requested-source failure',async()=>{const m=market();m.e.context.fetch=async url=>{if(String(url).includes('gitee.com'))return response([{name:'demo'}]);throw Error('offline')};await m.search('gitee');assert((await m.search('github')).statusCode===502);const mixed=await m.search();assert(mixed.statusCode===200&&mixed.json().cached&&mixed.json().skills.length===1)});
 await check('R19 GitHub total file failure does not become empty success',async()=>{const m=market();m.e.context.fetch=async url=>String(url).includes('api.github.com')?response([{name:'demo',type:'dir'}]):response({},false);assert((await m.search('github')).statusCode===502);m.e.context.fetch=async()=>response([]);assert((await m.search('github')).statusCode===200)});
 await check('R19 market failure survives installed-list completion and retry recovers',async()=>{const u=ui();u.doc.getElementById('skills-overlay').hidden=true;let online=false,installed;u.e.context.fetch=async url=>url.includes('/installed')?new Promise(r=>installed=r):response({skills:[]},online);const m=u.e.load('web/js/skills-panel.js','export const audit={refreshSkills};'),el=u.doc.getElementById('skills-list');await m.audit.refreshSkills();assert(el.innerHTML.includes('skills.load.failed')&&!el.innerHTML.includes('skills.empty'));installed(response({installed:[]}));await tick();assert(el.innerHTML.includes('skills.load.failed'));online=true;await el.querySelector('.sk-retry').events.click.at(-1)();assert(el.innerHTML.includes('skills.empty'))});
 await check('R19 stale market data is labelled and offers retry',async()=>{const u=ui();u.doc.getElementById('skills-overlay').hidden=true;u.e.context.fetch=async url=>response(url.includes('/installed')?{installed:[]}:{skills:[],cached:true});const m=u.e.load('web/js/skills-panel.js','export const audit={refreshSkills};');await m.audit.refreshSkills();assert(u.doc.getElementById('skills-list').innerHTML.includes('skills.catalog.partial')&&u.doc.getElementById('skills-list').querySelector('.sk-retry').events.click.length)});
 for(const level of ['off','low','medium','high','xhigh'])await check('R19 reasoning '+level+' displays and persists',async()=>{const u=ui();u.doc.getElementById('subagent-panel').hidden=true;u.modules['./sse.js']={setModelCache(){}};let saved;u.e.context.fetch=async(url,opts)=>{saved=JSON.parse(opts.body);return response({})};const m=u.e.load('web/js/subagent-panel.js','export const audit={makeReasoningSelect};'),select=m.audit.makeReasoningSelect('implement',level),card=new El();card.dataset.type='implement';select.closest=()=>card;assert(select.value===level&&select.innerHTML.includes(`value="${level}"`));select.dispatchEvent({type:'change'});await tick();assert(saved.reasoning===level)});
 await check('R19 failed reasoning write restores effective xhigh',async()=>{const u=ui();u.doc.getElementById('subagent-panel').hidden=true;u.modules['./sse.js']={setModelCache(){}};u.e.context.fetch=async(url,opts)=>opts?response({},false):response({types:[{type:'implement',reasoning:'xhigh'}]});const m=u.e.load('web/js/subagent-panel.js','export const audit={makeReasoningSelect};'),select=m.audit.makeReasoningSelect('implement','xhigh'),card=new El();card.dataset.type='implement';select.closest=()=>card;select.value='off';select.dispatchEvent({type:'change'});await tick();await tick();assert(select.value==='xhigh')});
 await check('R19 second suspend cancels pending resume and next wake reconnects once',()=>{const x=lifecycle();x.suspend();x.resume();assert(x.u.e.timers.size===1);const old=[...x.u.e.timers.values()][0];x.suspend();assert(x.u.e.timers.size===0);old.fn();assert(x.state().paused&&x.state().count===0);x.resume();x.resume();x.flush();assert(!x.state().paused&&x.state().count===1)});
 await check('R19 pagehide cancels pending wake and bfcache restore reconnects',()=>{const x=lifecycle();x.suspend();x.resume();x.u.e.context.window.dispatchEvent({type:'pagehide'});x.flush();assert(x.state().paused&&x.state().count===0);x.u.e.context.window.dispatchEvent({type:'pageshow',persisted:true});x.flush();assert(!x.state().paused&&x.state().count===1)});
 console.log(JSON.stringify({checks:results.length,passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length}));
})();
