process.env.ASHUB_TEST_ROOT ||= require('path').resolve(__dirname,'..');
const {env,Res,req,Bridge,assert,ts,vm,fs,path,root}=require('./harness.cjs');
const {ui,El,signal}=require('./ui-harness.cjs');const {EventEmitter}=require('events');
const tick=()=>new Promise(r=>setImmediate(r));const findings=[];
function ast(file){return ts.createSourceFile(file,fs.readFileSync(path.join(root,file),'utf8'),ts.ScriptTarget.Latest,true)}
function find(sf,p){let out;function walk(n){if(!out&&p(n))out=n;if(!out)ts.forEachChild(n,walk)}walk(sf);assert(out,'AST missing');return out;}
function variable(file,name,ctx){const sf=ast(file),n=find(sf,n=>ts.isVariableDeclaration(n)&&n.name?.text===name);return vm.runInContext('('+n.initializer.getText(sf)+')',ctx)}
function method(file,name,ctx){const sf=ast(file),n=find(sf,n=>ts.isMethodDeclaration(n)&&n.name?.text===name);return vm.runInContext(ts.transpileModule('({'+n.getText(sf)+'})['+JSON.stringify(name)+']',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx)}
function callback(file,expression,event,ctx){const sf=ast(file),n=find(sf,n=>ts.isCallExpression(n)&&n.expression.getText(sf)===expression&&n.arguments[0]?.text===event);return vm.runInContext(ts.transpileModule('('+n.arguments[1].getText(sf)+')',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx)}
function hub(e){return e.load('src/hub.ts','export const audit={startHub,createSession,closeSession,forkEndpoint,rewindContext,saveSessionMeta,archiveSession,unarchiveSession,shutdownHub,_flushBuf,persistReplayFile,routeEvent,submit,dropContext,openSseMulti,getContext,setCwdEndpoint,updateConfig,setAutoApprove,uploadImage,serveUpload,readBody,updateTitle,flushPtyBuffer,setSubagentModel,setSubagentBudget,loadArchivedSessions,listSessions,restoreSessions,rewindToTurn,execCommand,tagLastQueryFrame,setSessionTitle,setModelEndpoint,uninstallSkill,listInstalledSkills,_writeLocks};').audit}
async function create(extra={}){const e=env(extra),h=hub(e),ss=new Map(),s=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir);return{e,h,ss,s}}
const frame=f=>JSON.parse(f.split('data: ')[1]);
async function check(id,fn){if(process.env.ONLY&&!process.env.ONLY.split(',').some(x=>id.startsWith(x)))return;try{const detail=await fn();findings.push({id,passed:true,detail});console.log('PASS',id,JSON.stringify(detail))}catch(e){findings.push({id,passed:false,error:e.stack});console.log('FAIL',id,e.stack)}}
function acp(){const calls=[],child=new EventEmitter();child.stdout=new EventEmitter();child.stdout.setEncoding=()=>{};child.kill=()=>{};child.stdin=Object.assign(new EventEmitter(),{writable:true,end(){},write:raw=>{const m=JSON.parse(raw);calls.push(m);if(m.method==='initialize'||m.method==='session/new'||m.method==='session/load'||m.method==='session/prompt')queueMicrotask(()=>child.stdout.emit('data',JSON.stringify({jsonrpc:'2.0',id:m.id,result:m.method==='initialize'?{protocolVersion:1,agentCapabilities:{loadSession:true}}:m.method==='session/new'?{sessionId:'remote'}:{stopReason:'end_turn'}})+'\n'));}});const e=env({modules:{'node:child_process':{spawn:()=>child}}}),A=e.load('src/bridges/acp.ts').AcpBridge;return{e,A,calls,child}}

function ashEnv(extra={}){
 let created=0,killed=0,shells=0,shellKilled=0;
 const noop=()=>{},core={handlers:{define:noop,advise:noop,call:noop},bus:{on:noop,emit:noop,emitPipe:(_,p)=>p},extensionContext:()=>({agent:{registerInstruction:noop,registerTool:noop,registerContextProducer:()=>noop}}),activateBackend:async()=>{},kill:()=>killed++};
 const e=env({...extra,modules:{'agent-sh':{createCore:()=>{created++;return core}},'agent-sh/agent':{activateAgent:noop},'agent-sh/extensions':{loadBuiltinExtensions:async()=>[]},'agent-sh/extension-loader':{loadExtensions:async()=>[]},'agent-sh/shell':{Shell:class{constructor(){shells++}onExit(){}kill(){shellKilled++}}},'agent-sh/shell/terminal':{headlessTerminal:()=>({})},...extra.modules}});const A=e.load('src/bridges/ash.ts').AshBridge;A.prototype.wire=noop;A.prototype.registerUserProviders=noop;A.prototype.gateImageToolResults=noop;return{e,A,core,stats:()=>({created,killed,shells,shellKilled})};
}
const watchdog=setTimeout(()=>{console.error('TIMEOUT');process.exit(1)},30000);
(async()=>{
await check('Y01 failed duplicate cannot steal successful retry query ID',async()=>{
 const {e,h,s}=await create();const boxes=[];const tag=method('web/js/sse.js','agent:query-tagged',e.context);
 const consumer={state:{replaying:false},streamEl:{querySelectorAll:()=>boxes.filter(b=>!b.dataset.entryId)}};

 // Deliver raw live frames at push time, before server patching can add the ID to the query.
 const client=new Res();client.write=raw=>{const f=frame(raw);if(f.meta.name==='agent:query')boxes.push({_queryText:f.payload.query,dataset:{turn:String(boxes.length+1),queryId:f.payload.queryId}});if(f.meta.name==='agent:query-tagged')tag.call(consumer,f.payload);return true};s.sseClients.add(client);
 const original=s.bridge.submit.bind(s.bridge);s.bridge.submit=async()=>{throw Error('backend unavailable')};await h.submit(req({query:'repeat me'}),new Res(),s);await tick();await s.contextLock;s.bridge.submit=original;
 await h.submit(req({query:'intervening turn'}),new Res(),s);await tick();await s.contextLock;
 await h.submit(req({query:'repeat me'}),new Res(),s);await tick();await s.contextLock;
 const queries=s.replay.map(frame).filter(x=>x.meta.name==='agent:query').map(x=>x.payload);
 assert(!queries[0].entryId&&queries[2].entryId&&!boxes[0].dataset.entryId&&boxes[2].dataset.entryId===queries[2].entryId,'regression');
 const beforeRewind=JSON.parse(JSON.stringify(boxes));s.sseClients.delete(client);const res=new Res();await h.rewindToTurn(req({entryId:boxes[2].dataset.entryId}),res,s);
 return{serverQueries:queries,displayedBoxes:beforeRewind,rewindStatus:res.statusCode,remainingMessages:s.bridge.messages};
});
await check('Y02 A to B to A during budget save rebuilds subagent panel',async()=>{
 const u=ui(),reads=[];let sid='aaaaaa',resolvePut;const gate=new Promise(r=>resolvePut=r),container=new El();container.innerHTML='A cards';
 Object.assign(u.e.context,{saTypes:container,panelRenderSeq:0,saModelSeq:0,saBudgetSeq:0,_renderedSid:sid,_optionsSig:'',FALLBACK_TYPES:{},currentSessionId:()=>sid,renderCards:list=>{container.innerHTML='restored A cards'},toast(){},t:x=>x,fetch:async(url,opts)=>opts?.method==='PUT'?gate:new Promise(r=>reads.push({url,resolve:r}))});
 const render=variable('web/js/subagent-panel.js','renderSubagentPanel',u.e.context),commit=variable('web/js/subagent-panel.js','commitBudgetField',u.e.context),card=new El();card.dataset.type='implement';commit(card,'budgetTokens',90000,()=>{});
 sid='bbbbbb';render();sid='aaaaaa';render();resolvePut({ok:true});await tick();for(const r of reads)r.resolve({ok:true,json:async()=>({types:[{type:'implement',budgetTokens:90000}]})});await tick();assert(reads.length===3,'stale budget read was not retried');reads[2].resolve({ok:true,json:async()=>({types:[{type:'implement',budgetTokens:90000}]})});await tick();
 assert(container.innerHTML==='restored A cards','regression');return{activeSession:sid,panelHTML:container.innerHTML,requests:reads.map(r=>r.url),budgetSaveCompleted:!card._budgetSaving.budgetTokens};
});
await check('Y03 previous session model save triggers new dropdown re-read',async()=>{
 const u=ui();let sid='aaaaaa',resolvePut,resolveGet;const put=new Promise(r=>resolvePut=r),get=new Promise(r=>resolveGet=r),wrapper=new El(),label=new El();label.closest=()=>({dataset:{type:'implement'}});label.parentElement=wrapper;const saTypes=new El();saTypes.querySelectorAll=s=>s==='.sa-model-label'?[label]:[currentSelect];let currentSelect;
 Object.assign(u.e.context,{saTypes,saModelSeq:0,modelRefreshSeq:0,_optionsSig:'',agentInfo:{provider:'test'},currentSessionId:()=>sid,toast(){},t:x=>x,escape:String,ensureOverrideOption(){},fetchModelsCatalog:async()=>({providers:[{name:'test',models:[{id:'saved'}]}]}),fetch:async(url,opts)=>opts?.method==='PUT'?put:get});
 variable('web/js/subagent-panel.js','buildModelSelects',u.e.context)();const old=wrapper.children[0];old.value='saved@test';old.dispatchEvent({type:'change'});
 sid='bbbbbb';currentSelect=new El();currentSelect.dataset.type='implement';currentSelect.value='inherit';variable('web/js/subagent-panel.js','refreshModelDropdowns',u.e.context)();resolvePut({ok:true});await tick();resolveGet({ok:true,json:async()=>({models:{implement:'saved@test'}})});await tick();
 assert(currentSelect.value==='saved@test','regression');return{activeSession:sid,storedOverride:'saved@test',displayedOverride:currentSelect.value};
});
await check('Y04 skill deletion invalidates earlier scans and cached results',async()=>{
 const real=require('node:fs');let release,reached,gatePath,hold=true;const gate=new Promise(r=>release=r),ready=new Promise(r=>reached=r);
 const e=env({modules:{'node:fs':{...real,promises:{...real.promises,readdir:async(p,...args)=>{if(hold&&p===gatePath){hold=false;reached();await gate}return real.promises.readdir(p,...args)}}}}}),h=hub(e);
 const skill=path.join(e.dir,'skills','sample');fs.mkdirSync(skill,{recursive:true});fs.writeFileSync(path.join(skill,'SKILL.md'),'sample');gatePath=path.join(e.os.homedir(),'.agents','skills');e.settings.getSettings=()=>({skillPaths:[gatePath]});
 const first=new Res(),loading=h.listInstalledSkills(req({},'/api/skills/installed','GET'),first);await ready;
 const removal=new Res();await h.uninstallSkill(req({name:'sample',path:skill}),removal);assert(removal.statusCode===200&&!fs.existsSync(skill),'delete failed');release();await loading;
 const later=new Res();await h.listInstalledSkills(req({},'/api/skills/installed','GET'),later);
 assert(!later.json().installed.some(x=>x.name==='sample')&&!first.json().installed.length,'regression');e.clock(116000);const expired=new Res();await h.listInstalledSkills(req({},'/api/skills/installed','GET'),expired);
 return{deleteStatus:removal.statusCode,pathExists:fs.existsSync(skill),freshGet:later.json(),afterTTL:expired.json()};
});
await check('Y05 changing cwd within same session reloads project skills',async()=>{
 const u=ui(),a={id:'aaaaaa',state:{cwd:'/projects/A'}};u.active.value=a;u.doc.getElementById('skills-overlay').hidden=true;const calls=[];
 u.e.context.fetch=async(url,opts)=>{calls.push({url,opts});return{ok:true,json:async()=>url.startsWith('/api/skills/installed')?{installed:[{name:url.includes('%2FB')?'only-B':'only-A',path:url.includes('%2FB')?'/projects/B/.agents/skills/only-B':'/projects/A/.agents/skills/only-A'}]}:{skills:[]}}};
 const mod=u.e.load('web/js/skills-panel.js','export const audit={cwd:()=>installedCwd,uninstall};');mod.setSkillsOpen(true);await tick();const originalCalls=calls.length;
 Object.assign(u.e.context,{activeSession:u.active,CustomEvent:class{constructor(type,opts){this.type=type;this.detail=opts?.detail}},refreshCwdChip(){},refreshFilesIfOpen(){}});method('web/js/sse.js','shell:cwd-change',u.e.context).call(a,{cwd:'/projects/B'});await tick();
 const sent=await mod.audit.uninstall('only-A',{path:'/projects/A/.agents/skills/only-A',cwd:'/projects/A'});
 assert(a.state.cwd==='/projects/B'&&mod.audit.cwd()==='/projects/B'&&calls.length===originalCalls+2&&sent===false,'regression');return{activeCwd:a.state.cwd,displayedSkillsCwd:mod.audit.cwd(),newRequests:calls.length-originalCalls,oldRowActionSent:sent,listHTML:u.doc.getElementById('skills-installed-list').innerHTML};
});

await check('Y06 sidebar terminal deletion reports failure and keeps backend',async()=>{
 const real=require('node:fs');let fail=false;const e=env({modules:{'node:fs':{...real,promises:{...real.promises,writeFile:async(p,...args)=>{if(fail&&String(p).endsWith('.deleted'))throw Error('EACCES tombstone');return real.promises.writeFile(p,...args)}}}}}),h=hub(e),ss=new Map();let closed=0;const s=await h.createSession(ss,{makeBridge:o=>{const b=new Bridge(o);b.close=()=>{closed++};return b}},e.dir,undefined,'terminal');fail=true;
 const u=ui(),list=new El(),warnings=[];let status,refreshes=0;
 Object.assign(u.e.context,{terminalList:list,terminalsHash:null,allSessions:{value:[{instanceId:s.id,kind:'terminal',title:'background shell'}]},activeSessionId:{peek:()=>''},openTabs:{peek:()=>[]},toast:x=>warnings.push(x),sideBody:String,t:x=>x,closeTab:()=>{throw Error('not open')},renderSessions:async()=>{refreshes++},fetch:async()=>{const r=new Res();await h.closeSession(r,ss,s.id);status=r.statusCode;return{ok:r.statusCode===200,status:r.statusCode,text:async()=>r.body}}});
 u.e.context.renderTerminals=variable('web/js/sidebar.js','renderTerminals',u.e.context);u.e.context.renderTerminals();const button=list.children[0].children[1];button.classList.add('confirming');await button.events.click[0]({preventDefault(){},stopPropagation(){}});
 assert(status===500&&ss.has(s.id)&&closed===0&&warnings.length===1&&refreshes===0,'regression');return{status,backendStillRegistered:ss.has(s.id),backendCloseCalls:closed,errorNotifications:warnings.length,listRefreshes:refreshes};
});
await check('Y07 failed tab title save restores confirmed state and reports error',async()=>{
 const real=require('node:fs');let fail=false;const {e,h,s}=await create({modules:{'node:fs':{...real,promises:{...real.promises,writeFile:async(p,...args)=>{if(fail&&String(p).endsWith('.meta.json.tmp'))throw Error('EACCES metadata');return real.promises.writeFile(p,...args)}}}}});await h.setSessionTitle(s,'original',true);fail=true;const u=ui(),meta={title:'original'},label=new El(),btn=new El(),notifications=[];let input,status;
 label.textContent='original';label.replaceWith=x=>input=x;btn.querySelector=()=>label;u.doc.createElement=()=>{const el=new El();el.select=()=>{};return el};
 Object.assign(u.e.context,{editingId:null,openTabs:{peek:()=>['aaaaaa']},getSession:()=>meta,render(){},toast:x=>notifications.push(x),fetch:async(url,opts)=>{const r=new Res();try{await h.updateTitle(req(JSON.parse(opts.body)),r,s)}catch(err){r.writeHead(500);r.end(String(err))}status=r.statusCode;return{ok:status===200,status,text:async()=>r.body}}});variable('web/js/tabs.js','startRename',u.e.context)(btn,'aaaaaa');input.value='unsaved name';await input.events.blur[0]();
 assert(status===500&&meta.title==='original'&&s.title==='original'&&notifications.length===1,'regression');return{httpStatus:status,persistedTitle:JSON.parse(fs.readFileSync(path.join(e.dir,'hub-sessions',s.id+'.meta.json'),'utf8')).title,serverMemoryTitle:s.title,displayedTitle:meta.title,errorNotifications:notifications.length};
});

await check('Y01 live and optimistic user boxes keep exact query correlation',async()=>{
 const u=ui(),boxes=[],rootEl={querySelector:()=>null,querySelectorAll:()=>boxes.filter(b=>b.classList.contains('pending'))};
 const session={state:{currentTurn:0,replaying:false},streamEl:rootEl};Object.assign(u.e.context,{CSS:{escape:String},closeReply(){},finalizeThinking(){},finalizeLiveOutput(){},resetCompletedTools(){},startNewSegment(){},renderTurnSep(){},createUserBox:q=>{const b=new El();b._queryText=q;return b},append:(s,b)=>boxes.push(b)});
 const query=method('web/js/sse.js','agent:query',u.e.context),tag=method('web/js/sse.js','agent:query-tagged',u.e.context);query.call(session,{query:'same',queryId:'first'});const optimistic=new El();optimistic._queryText='same';optimistic.classList.add('pending');boxes.push(optimistic);query.call(session,{query:'same',queryId:'second'});
 rootEl.querySelectorAll=()=>boxes.filter(b=>!b.dataset.entryId);tag.call(session,{query:'same',queryId:'second',entryId:'good'});assert(!boxes[0].dataset.entryId&&optimistic.dataset.entryId==='good'&&optimistic.dataset.queryId==='second','tag matched by text');tag.call(session,{query:'same',entryId:'legacy'});assert(!boxes[0].dataset.entryId,'legacy tag stole failed box');
});
await check('Y01 replay and reconnect preserve query IDs and confirmed entry IDs',async()=>{
 const {e,h,s,ss}=await create();for(const query of ['same','same']){await h.submit(req({query}),new Res(),s);await tick();await s.contextLock}const before=s.replay.map(frame).filter(f=>f.meta.name==='agent:query').map(f=>f.payload);await h.shutdownHub(undefined,ss);const restored=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir,{id:s.id,title:'saved',startedAt:1,replay:[]});const res=new Res();await h.openSseMulti(Object.assign(new EventEmitter(),{headers:{}}),res,ss,s.id+':all','');const after=restored.replay.map(frame).filter(f=>f.meta.name==='agent:query').map(f=>f.payload);assert(after.length===2&&after.every((p,i)=>p.queryId===before[i].queryId&&p.entryId===before[i].entryId),'query identity changed');
});
await check('Y02 full module handles quick A to B to A while save completes',async()=>{
 const u=ui(),reads=[];let releasePut;const put=new Promise(r=>releasePut=r);u.doc.getElementById('subagent-panel').hidden=true;const container=u.doc.getElementById('sa-types');let html='';Object.defineProperty(container,'innerHTML',{get:()=>html,set:v=>{html=v;container.children=[]}});u.modules['./sse.js']={setModelCache(){}};u.modules['./state.js'].agentInfo={provider:'test'};
 u.e.context.fetch=async(url,opts)=>opts?.method==='PUT'?put:new Promise(r=>reads.push({url,resolve:r}));const mod=u.e.load('web/js/subagent-panel.js','export const audit={commitBudgetField};');mod.setSgOpen(true);reads.shift().resolve({ok:true,json:async()=>({types:[{type:'implement',description:'test',budgetTokens:40000}]})});await tick();assert(container.children.length===1,'initial cards failed');const card=new El();card.dataset.type='implement';mod.audit.commitBudgetField(card,'budgetTokens',90000,()=>{});u.active.value={id:'bbbbbb',state:{}};u.active.value={id:'aaaaaa',state:{}};releasePut({ok:true});await tick();for(const r of [...reads])r.resolve({ok:true,json:async()=>r.url.endsWith('/sa-types')?{types:[{type:'implement',description:'test',budgetTokens:90000}]}:{models:{}}});await tick();const retry=reads[reads.length-1];assert(retry.url.endsWith('/sa-types'),'missing budget retry');retry.resolve({ok:true,json:async()=>({types:[{type:'implement',description:'test',budgetTokens:90000}]})});await tick();assert(container.children.length===1&&container.children[0]._saCfg.budgetTokens===90000,'new panel stayed empty');
});
await check('Y05 cwd changes while hidden defer loads and background changes do not refresh active skills',async()=>{
 const u=ui();u.doc.getElementById('skills-overlay').hidden=true;const calls=[];u.e.context.fetch=async url=>{calls.push(url);return{ok:true,json:async()=>({skills:[],installed:[]})}};const mod=u.e.load('web/js/skills-panel.js');u.doc.dispatchEvent({type:'ash:cwd-change',detail:{sessionId:'bbbbbb'}});assert(!calls.length,'background event loaded active skills');u.active.peek().state.cwd='/new';u.doc.dispatchEvent({type:'ash:cwd-change',detail:{sessionId:'aaaaaa'}});assert(!calls.length,'hidden overlay loaded');mod.setSkillsOpen(true);await tick();assert(calls.some(s=>s.includes('cwd=%2Fnew')),'reopen used old cwd');const n=calls.length;u.doc.dispatchEvent({type:'ash:cwd-change',detail:{sessionId:'bbbbbb'}});assert(calls.length===n,'background cwd refreshed active panel');
});
for(const offline of [false,true])await check('Y06 terminal '+(offline?'network failure preserves tab':'success closes tab without duplicate DELETE'),async()=>{
 const u=ui(),list=new El(),tabs=signal(['aaaaaa']),kinds=new Map([['aaaaaa','terminal']]),notices=[];let deletes=0,removed=0;
 Object.assign(u.e.context,{terminalList:list,terminalsHash:null,allSessions:{value:[{instanceId:'aaaaaa',kind:'terminal',title:'terminal'}]},activeSessionId:signal('aaaaaa'),openTabs:tabs,sessionKinds:kinds,closingTerminals:new Set(),sessions:new Map([['aaaaaa',{remove:()=>removed++}]]),switchTo(){},toast:x=>notices.push(x),sideBody:String,t:x=>x,renderSessions:async()=>{},fetch:async()=>{deletes++;if(offline)throw Error('offline');return{ok:true}}});u.e.context.closeTab=variable('web/js/session-manager.js','closeTab',u.e.context);u.e.context.renderTerminals=variable('web/js/sidebar.js','renderTerminals',u.e.context);u.e.context.renderTerminals();const b=list.children[0].children[1];b.classList.add('confirming');await b.events.click[0]({preventDefault(){},stopPropagation(){}});assert(deletes===1,'duplicate delete');if(offline)assert(tabs.peek().length===1&&removed===0&&notices.length===1,'failed close discarded tab');else assert(tabs.peek().length===0&&removed===1&&!kinds.has('aaaaaa'),'successful close left tab state');
});
for(const ok of [false,true])await check('Y07 sidebar title '+(ok?'success requests confirmed refresh':'failure is visible without optimistic label'),async()=>{
 const u=ui(),li=new El(),title=li.querySelector('.session-title');title.textContent='original';let input,refreshes=0;title.insertAdjacentElement=(where,el)=>input=el;u.doc.createElement=()=>{const e=new El();e.select=()=>{};return e};const warnings=[];Object.assign(u.e.context,{editingId:null,sessionList:new El(),toast:x=>warnings.push(x),renderSessions:()=>refreshes++,fetch:async()=>({ok,status:500,text:async()=> 'write failed'})});variable('web/js/sidebar.js','startTitleEdit',u.e.context)(li,'aaaaaa','original');input.value='new';await input.events.blur[0]();assert(title.textContent==='original'&&refreshes===1&&warnings.length===(ok?0:1),'title UI lied about saved state');
});
await check('Y07 title failure can retry and subsequent serialized rename wins',async()=>{
 const real=require('fs');let fail=false;const {e,h,s}=await create({modules:{'node:fs':{...real,promises:{...real.promises,writeFile:async(p,...args)=>{if(fail&&String(p).endsWith('.meta.json.tmp'))throw Error('full');return real.promises.writeFile(p,...args)}}}}});await h.setSessionTitle(s,'original',true);fail=true;await h.setSessionTitle(s,'failed',true).catch(()=>{});assert(s.title==='original'&&s.userTitle==='original','failed name stuck');fail=false;await Promise.all([h.setSessionTitle(s,'retry',true),h.setSessionTitle(s,'latest',true)]);const saved=JSON.parse(fs.readFileSync(path.join(e.dir,'hub-sessions',s.id+'.meta.json'),'utf8'));assert(saved.title==='latest'&&s.title==='latest'&&!s._titleDirty,'retry/serialized title lost');
});
await check('Y07 tab successful save requests shared title refresh',async()=>{
 const u=ui(),meta={title:'original'},label=new El(),btn=new El();let input,refreshed=0;label.textContent='original';label.replaceWith=x=>input=x;btn.querySelector=()=>label;u.doc.createElement=()=>{const e=new El();e.select=()=>{};return e};u.doc.addEventListener('sse:title',()=>refreshed++);Object.assign(u.e.context,{editingId:null,openTabs:{peek:()=>['aaaaaa']},getSession:()=>meta,render(){},toast(){throw Error('unexpected failure')},fetch:async()=>({ok:true})});variable('web/js/tabs.js','startRename',u.e.context)(btn,'aaaaaa');input.value='new';await input.events.blur[0]();assert(refreshed===1&&meta.title==='original','title refresh missing');
});

await check('Y03 completed new-panel read is refreshed when old-session global save finishes',async()=>{
 const u=ui(),panel=u.doc.getElementById('subagent-panel'),types=u.doc.getElementById('sa-types'),label=new El(),wrap=new El();panel.hidden=true;let sid='aaaaaa',select,release,saved='old@test';const gate=new Promise(r=>release=r);label.closest=()=>({dataset:{type:'implement'}});label.parentElement=wrap;types.querySelectorAll=q=>q==='.sa-model-label'?[label]:select?[select]:[];u.modules['./state.js'].currentSessionId=()=>sid;u.modules['./state.js'].agentInfo={provider:'test'};u.modules['./sse.js']={setModelCache(){}};
 u.e.context.fetch=async(url,opts)=>{if(opts?.method==='PUT'){await gate;saved=JSON.parse(opts.body).model;return{ok:true}}return{ok:true,json:async()=>url==='/api/models'?{providers:[{name:'test',models:[{id:'old'},{id:'saved'}]}]}:{models:{implement:saved}}}};
 const mod=u.e.load('web/js/subagent-panel.js','export const audit={buildModelSelects,refreshModelDropdowns};');mod.audit.buildModelSelects();select=wrap.children[0];select.options=[];select.value='saved@test';select.dispatchEvent({type:'change'});
 sid='bbbbbb';select=new El();select.dataset.type='implement';select.options=[];select.value='inherit';panel.hidden=false;mod.audit.refreshModelDropdowns();await tick();assert(select.value==='old@test','initial B read failed');release();await tick();assert(select.value==='saved@test','B retained global override from before A save');
});

clearTimeout(watchdog);console.log(JSON.stringify({checks:findings.length,passed:findings.filter(x=>x.passed).length,failed:findings.filter(x=>!x.passed).length}));if(findings.some(x=>!x.passed))process.exitCode=1;
})().catch(e=>{clearTimeout(watchdog);console.error(e);process.exitCode=1});
