process.env.ASHUB_TEST_ROOT ||= require('path').resolve(__dirname,'..');
const {env,Res,req,Bridge,assert,ts,vm,fs,path,root}=require('./harness.cjs');
const {ui,El,signal}=require('./ui-harness.cjs');const {EventEmitter}=require('events');
const tick=()=>new Promise(r=>setImmediate(r));const findings=[];
function ast(file){return ts.createSourceFile(file,fs.readFileSync(path.join(root,file),'utf8'),ts.ScriptTarget.Latest,true)}
function find(sf,p){let out;function walk(n){if(!out&&p(n))out=n;if(!out)ts.forEachChild(n,walk)}walk(sf);assert(out,'AST missing');return out;}
function variable(file,name,ctx){const sf=ast(file),n=find(sf,n=>ts.isVariableDeclaration(n)&&n.name?.text===name);return vm.runInContext('('+n.initializer.getText(sf)+')',ctx)}
function method(file,name,ctx){const sf=ast(file),n=find(sf,n=>ts.isMethodDeclaration(n)&&n.name?.text===name);return vm.runInContext(ts.transpileModule('({'+n.getText(sf)+'})['+JSON.stringify(name)+']',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx)}
function callback(file,expression,event,ctx){const sf=ast(file),n=find(sf,n=>ts.isCallExpression(n)&&n.expression.getText(sf)===expression&&n.arguments[0]?.text===event);return vm.runInContext(ts.transpileModule('('+n.arguments[1].getText(sf)+')',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,ctx)}
function hub(e){return e.load('src/hub.ts','export const audit={startHub,createSession,closeSession,forkEndpoint,rewindContext,saveSessionMeta,archiveSession,unarchiveSession,shutdownHub,_flushBuf,persistReplayFile,routeEvent,submit,dropContext,openSseMulti,getContext,setCwdEndpoint,updateConfig,setAutoApprove,uploadImage,serveUpload,readBody,updateTitle,flushPtyBuffer,setSubagentModel,setSubagentBudget,loadArchivedSessions,listSessions,restoreSessions,rewindToTurn,execCommand,tagLastQueryFrame,setSessionTitle,setModelEndpoint,migrateLegacyQueryTags,_writeLocks};').audit}
async function create(extra={}){const e=env(extra),h=hub(e),ss=new Map(),s=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir);return{e,h,ss,s}}
const frame=f=>JSON.parse(f.split('data: ')[1]);
async function check(id,fn){if(process.env.ONLY&&!process.env.ONLY.split(',').some(x=>id.startsWith(x)))return;try{const detail=await fn();findings.push({id,passed:true,detail});console.log('PASS',id,JSON.stringify(detail))}catch(e){findings.push({id,passed:false,error:e.stack});console.log('FAIL',id,e.stack)}}
function acp(){const calls=[],child=new EventEmitter();child.stdout=new EventEmitter();child.stdout.setEncoding=()=>{};child.kill=()=>{};child.stdin=Object.assign(new EventEmitter(),{writable:true,end(){},write:raw=>{const m=JSON.parse(raw);calls.push(m);if(m.method==='initialize'||m.method==='session/new'||m.method==='session/load'||m.method==='session/prompt')queueMicrotask(()=>child.stdout.emit('data',JSON.stringify({jsonrpc:'2.0',id:m.id,result:m.method==='initialize'?{protocolVersion:1,agentCapabilities:{loadSession:true}}:m.method==='session/new'?{sessionId:'remote'}:{stopReason:'end_turn'}})+'\n'));}});const e=env({modules:{'node:child_process':{spawn:()=>child}}}),A=e.load('src/bridges/acp.ts').AcpBridge;return{e,A,calls,child}}

function ashEnv(extra={}){
 let created=0,killed=0,shells=0,shellKilled=0;
 const noop=()=>{},core={handlers:{define:noop,advise:noop,call:noop},bus:{on:noop,emit:noop,emitPipe:(_,p)=>p},extensionContext:()=>({agent:{registerInstruction:noop,registerTool:noop,registerContextProducer:()=>noop}}),activateBackend:async()=>{},kill:()=>killed++};
 const e=env({...extra,modules:{'agent-sh':{createCore:()=>{created++;return core}},'agent-sh/agent':{activateAgent:noop},'agent-sh/extensions':{loadBuiltinExtensions:async()=>[]},'agent-sh/extension-loader':{loadExtensions:async()=>[]},'agent-sh/shell':{Shell:class{constructor(){shells++}onExit(){}kill(){shellKilled++}}},'agent-sh/shell/terminal':{headlessTerminal:()=>({})},...extra.modules}});const A=e.load('src/bridges/ash.ts').AshBridge;A.prototype.wire=noop;A.prototype.registerUserProviders=noop;A.prototype.gateImageToolResults=noop;return{e,A,core,stats:()=>({created,killed,shells,shellKilled})};
}
const watchdog=setTimeout(()=>{console.error('TIMEOUT');process.exit(1)},30000);
(async()=>{
await check('W01 closed AshBridge does not create late resources',async()=>{
 let release,started;const gate=new Promise(r=>release=r),ready=new Promise(r=>started=r),real=require('fs');const {e,A,stats}=ashEnv({modules:{'node:fs':{...real,promises:{...real.promises,readFile:async(file,...a)=>{if(String(file).endsWith('settings.json')){started();await gate;return '{}'}return real.promises.readFile(file,...a)}}}}});const h=hub(e),ss=new Map();let b;const spawning=h.createSession(ss,{makeBridge:o=>(b=new A(o))},e.dir).catch(e=>e);await ready;await h.shutdownHub(undefined,ss);await spawning;const atShutdown=stats();release();let error;try{await b.ready()}catch(e){error=e}b.close();const after=stats();assert(error&&after.created===0&&after.shells===0,'late resources created');return{atShutdown,after,registeredSessions:ss.size,closed:b.closed};
});
await check('W02 shutdown cancels actual lazy AshBridge initialization',async()=>{
 let delay=false,release,started,snapshotStarted;const gate=new Promise(r=>release=r),ready=new Promise(r=>started=r),snapshotGate=new Promise(r=>snapshotStarted=r),real=require('fs');const {e,A,stats}=ashEnv({modules:{'node:fs':{...real,promises:{...real.promises,readFile:async(file,...a)=>{if(delay&&String(file).endsWith('settings.json')){started();await gate;return '{}'}return real.promises.readFile(file,...a)}}}}});const h=hub(e),ss=new Map(),s=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir);await h.submit(req({query:'saved'}),new Res(),s);await tick();await s.contextLock;await h.shutdownHub(undefined,ss);delay=true;let b,closed=0;const restored=await h.createSession(ss,{makeBridge:o=>{b=new A(o);const snap=b.snapshot.bind(b),close=b.close.bind(b);b.snapshot=(...a)=>{snapshotStarted();return snap(...a)};b.close=()=>{closed++;close()};return b}},e.dir,{id:s.id,title:'saved',startedAt:1,replay:[]});const restoring=restored._ensureBridge().catch(e=>e);await ready;let finished=false;const stopping=h.shutdownHub(undefined,ss).then(()=>finished=true);await stopping;const before={shutdownFinished:finished,closeCalls:closed};release();await restoring;await b.ready().catch(()=>{});assert(before.shutdownFinished&&before.closeCalls===1&&stats().created===0,'pending lazy backend not cancelled');return{beforeRelease:before,afterRelease:stats()};
});
await check('W03 mixed legacy replay migrates valid old messages and supports rewind',async()=>{
 const {e,h,s,ss}=await create();for(const query of ['first','second']){await h.submit(req({query}),new Res(),s);await tick();await s.contextLock;}await h.shutdownHub(undefined,ss);const rp=path.join(e.dir,'hub-sessions',s.id+'.replay.jsonl');const frames=fs.readFileSync(rp,'utf8').split('\n\n').filter(Boolean).map(f=>f+'\n\n').filter(f=>!(f.includes('agent:query-tagged')&&f.includes('first'))).map(f=>{if(f.includes('agent:query')&&f.includes('first')){const lines=f.split('\n'),i=lines.findIndex(l=>l.startsWith('data: ')),d=JSON.parse(lines[i].slice(6));delete d.payload.entryId;lines[i]='data: '+JSON.stringify(d);return lines.join('\n')}return f});fs.writeFileSync(rp,frames.join(''));const restored=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir,{id:s.id,title:'saved',startedAt:1,replay:[]});await restored._ensureBridge();const response=new Res();await h.openSseMulti(Object.assign(new EventEmitter(),{headers:{}}),response,ss,s.id+':all','');const q=restored.replay.map(frame).filter(f=>f.meta.name==='agent:query').map(f=>({query:f.payload.query,entryId:f.payload.entryId??null}));assert(q[0].entryId&&q[1].entryId&&q[0].entryId!==q[1].entryId,'legacy IDs missing');assert(fs.readFileSync(rp,'utf8').includes(q[0].entryId),'migration not persisted');const u=ui();Object.assign(u.e.context,{t:x=>x,fetch:async(url,opts)=>{const r=new Res();await h.rewindToTurn(req(JSON.parse(opts.body)),r,restored);return{ok:r.statusCode===200,json:async()=>r.json(),text:async()=>r.body}}});await variable('web/js/actions.js','rewindToTurn',u.e.context)({sid:s.id,turn:0,entryId:q[0].entryId});assert(restored.bridge.messages.length===0,'migrated rewind failed');
});
await check('W04 replay read failure preserves history and retries safely',async()=>{
 let fail=false;const real=require('fs'),{e,h,s,ss}=await create({modules:{'node:fs':{...real,promises:{...real.promises,readFile:async(file,...a)=>{if(fail&&String(file).endsWith('.replay.jsonl'))throw Object.assign(Error('EACCES'),{code:'EACCES'});return real.promises.readFile(file,...a)}}}}});s.store.setActiveLeaf(s.store.getRootId());h.routeEvent(s,{name:'shell:command-start',payload:{command:'echo valuable'}});h.routeEvent(s,{name:'shell:command-done',payload:{stdout:'valuable output'}});await h.shutdownHub(undefined,ss);const rp=path.join(e.dir,'hub-sessions',s.id+'.replay.jsonl');assert(fs.readFileSync(rp,'utf8').includes('valuable output'),'setup failed');const restored=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir,{id:s.id,title:'saved',startedAt:1,replay:[]});fail=true;let error;try{await restored._ensureBridge()}catch(e){error=e}assert(error&&!restored.bridge&&restored._needsRestore,'read failure accepted');assert(fs.readFileSync(rp,'utf8').includes('valuable output'),'failed restore changed source');fail=false;await restored._ensureBridge();await h.updateTitle(req({title:'changed'}),new Res(),restored);await h.shutdownHub(undefined,ss);const after=fs.readFileSync(rp,'utf8');assert(after.includes('valuable output'),'history lost after retry');
});
function modelUi(){const u=ui(),wrap=new El(),label=new El(),types=new El(),card=new El();card.dataset.type='implement';label.closest=()=>card;label.parentElement=wrap;types.querySelectorAll=q=>q==='.sa-model-label'?[label]:wrap.children;Object.assign(u.e.context,{saTypes:types,saModelSeq:0,modelRefreshSeq:0,_optionsSig:'',agentInfo:{provider:'test'},currentSessionId:()=> 'aaaaaa',toast(){},t:x=>x,escape:x=>x,ensureOverrideOption(){},fetchModelsCatalog:async()=>({providers:[]})});variable('web/js/subagent-panel.js','buildModelSelects',u.e.context)();return{u,select:wrap.children[0],refresh:variable('web/js/subagent-panel.js','refreshModelDropdowns',u.e.context)}}
await check('W05 refresh during model PUT cannot overwrite saved selection',async()=>{
 const {u,select,refresh}=modelUi();let release,saved='old';const gate=new Promise(r=>release=r);u.e.context.fetch=async(url,opts)=>{if(opts?.method==='PUT'){const model=JSON.parse(opts.body).model;await gate;saved=model;return{ok:true}}return{ok:true,json:async()=>({models:{implement:saved}})}};select.value='new';select.dispatchEvent({type:'change'});refresh();await tick();release();await tick();assert(saved==='new'&&select.value==='new','pending PUT refresh guarded');return{saved,displayed:select.value};
});
await check('W06 rejected and offline model switches retain confirmed state and report errors',async()=>{
 const {e,A}=acp(),h=hub(e),ss=new Map(),s=await h.createSession(ss,{makeBridge:o=>new A({...o,extra:{command:'fake-acp'}})},e.dir);s.model='old';const r=new Res();await h.setModelEndpoint(req({model:'new',provider:'test'}),r,s);assert(r.statusCode===409&&r.body.includes('does not support model switching'),'unsupported switch not rejected');const u=ui();Object.assign(u.e.context,{refreshModelChip(){},BALANCE_PROVIDERS:new Set(),toast:(...a)=>u.toasts.push(a),t:x=>x,activeSession:u.active,fetch:async()=>({ok:false,status:r.statusCode})});const uiSession={id:s.id,agentInfo:{model:'old',provider:'test',modalities:['image']}};variable('web/js/sse.js','selectModel',u.e.context)(uiSession,'new','test');await tick();assert(uiSession.agentInfo.model==='old'&&s.model==='old'&&uiSession.agentInfo.modalities[0]==='image','failed switch reverted');u.e.context.fetch=async()=>{throw Error('offline')};variable('web/js/sse.js','selectModel',u.e.context)(uiSession,'offline-choice','test');await tick();assert(uiSession.agentInfo.model==='old'&&s.model==='old'&&u.toasts.length===2,'network failure reverted or reported');return{httpStatus:r.statusCode,backend:s.model,displayedAfterNetworkFailure:uiSession.agentInfo.model,errorToasts:u.toasts.length};
});
await check('W07 capture realignment retry preserves current branch after fallback compaction',async()=>{
 let failLeaf=false;const real=require('fs'),e=env({modules:{'node:fs':{...real,appendFileSync:(file,...a)=>{if(failLeaf)throw Error('ENOSPC');return real.appendFileSync(file,...a)}}}}),Store=e.load('src/history/session-store.ts').SessionStore,file=path.join(e.dir,'tree.jsonl'),store=new Store(file,{create:{cwd:e.dir,sessionId:'aaaaaa'}}),b=new Bridge();b.messages=Array.from({length:12},(_,i)=>[{role:'user',content:'question '+i+' '+ 'x'.repeat(16000)},{role:'assistant',content:'answer '+i+' '+ 'y'.repeat(16000)}]).flat();const capture=e.load('src/history/capture.ts').createCapture(b,()=>store);await capture.flush();const strategy=e.load('src/history/compaction-strategy.ts').createCompactionStrategy(()=>store,()=>capture);const make=e.load(path.join(root,'node_modules/agent-sh/dist/agent/extensions/rolling-history/strategy.js')).makeCompactAdvisor,tokens=()=>JSON.stringify(b.messages).length/4;const advisor=make({iid:'test',store:{append:async()=>{},readRecent:async()=>[]},getMessages:()=>b.messages,replaceMessages:m=>b.messages=m,estimatePromptTokens:tokens,estimateTokens:tokens});store.appendCompaction=async()=>{throw Error('ENOSPC')};await strategy({getMessages:()=>b.messages,replaceMessages:m=>b.messages=m,estimatePromptTokens:tokens},{target:4000,force:true},opts=>advisor(()=>null,opts));assert(b.messages.length<24,'fallback did not compact');const beforeLeaf=store.getActiveLeaf();failLeaf=true;let error;try{await capture.flush()}catch(e){error=e}failLeaf=false;const truncatedCapture=capture.length();assert(store.getActiveLeaf()===beforeLeaf&&truncatedCapture===24,'failed realignment mutated capture');await capture.flush();const loaded=new Store(file);assert(error&&JSON.stringify(loaded.buildMessages())===JSON.stringify(b.messages),'retry remained aligned');return{liveMessages:b.messages.length,captureAfterFailedCommit:truncatedCapture,persistedMessages:loaded.buildMessages().length,oldLeafWasRetainedBeforeRetry:!!beforeLeaf,removedQuestionRestored:loaded.buildMessages().some(m=>String(m.content).startsWith('question 1 '))};
});
await check('W08 unrelated budget field edits do not suppress failed field rollback',async()=>{
 const u=ui();let release;const pending=new Promise(r=>release=r);let shownBudget=90000,shownIterations=50;Object.assign(u.e.context,{saBudgetSeq:0,currentSessionId:()=> 'aaaaaa',toast(){},t:x=>x,fetch:async(url,opts)=>{if(opts?.method==='PUT'){const b=JSON.parse(opts.body);return {ok:b.maxIterations!==undefined,status:b.maxIterations!==undefined?200:500}}return pending}});const commit=variable('web/js/subagent-panel.js','commitBudgetField',u.e.context),card=new El();card.dataset.type='implement';commit(card,'budgetTokens',90000,c=>shownBudget=c.budgetTokens);await tick();commit(card,'maxIterations',50,c=>shownIterations=c.maxIterations);await tick();release({ok:true,json:async()=>[{type:'implement',budgetTokens:40000,maxIterations:50}]});await tick();assert(shownBudget===40000&&shownIterations===50,'failed field reverted');return{storedBudget:40000,displayedBudget:shownBudget,otherFieldSaved:shownIterations};
});
for(const boundary of ['builtin','backend'])await check('W01 close during '+boundary+' loading prevents late Shell creation',async()=>{
 let started,release;const ready=new Promise(r=>started=r),gate=new Promise(r=>release=r);const opts=boundary==='builtin'?{modules:{'agent-sh/extensions':{loadBuiltinExtensions:async()=>{started();await gate;return[]}}}}:{};const {e,A,core,stats}=ashEnv(opts);if(boundary==='backend')core.activateBackend=async()=>{started();await gate};const b=new A({cwd:e.dir});const initializing=b.ready().then(()=>null,e=>e);await ready;b.close();release();assert(await initializing,'closed initialization succeeded');assert(stats().shells===0&&stats().killed>=1,'closed initialization allocated resources');
});
await check('W01 normal initialization and repeated close remain safe',async()=>{
 const {e,A,stats}=ashEnv(),b=new A({cwd:e.dir});await b.ready();assert(stats().created===1&&stats().shells===1,'normal startup failed');b.close();b.close();assert(stats().killed===1&&stats().shellKilled===1,'normal close duplicated or missed cleanup');
});
await check('W02 delete cancels a pending lazy backend and drains session files',async()=>{
 const {e,h,s,ss}=await create();await h.submit(req({query:'saved'}),new Res(),s);await tick();await s.contextLock;await h.shutdownHub(undefined,ss);let started,release,closed=0;const ready=new Promise(r=>started=r),gate=new Promise(r=>release=r);const restored=await h.createSession(ss,{makeBridge:o=>{const b=new Bridge(o);b.ready=async()=>{started();await gate};b.snapshot=async()=>{await gate;return{messages:b.messages}};b.close=()=>closed++;return b}},e.dir,{id:s.id,title:'saved',startedAt:1,replay:[]});const restoring=restored._ensureBridge().then(()=>null,e=>e);await ready;const r=new Res();await h.closeSession(r,ss,s.id);assert(r.statusCode===200&&closed>=1&&await restoring,'delete did not cancel pending backend');release();await tick();assert(!fs.readdirSync(path.join(e.dir,'hub-sessions')).some(n=>n.startsWith(s.id)&&!n.endsWith('.deleted')),'deleted session recreated');
});
await check('W02 cancelled restore remains retryable if archive itself fails',async()=>{
 let fail=false,release,started,first=true;const gate=new Promise(r=>release=r),ready=new Promise(r=>started=r),real=require('fs'),{e,h,s,ss}=await create({modules:{'node:fs':{...real,promises:{...real.promises,writeFile:async(file,...a)=>{if(fail&&String(file).endsWith('archived.json.tmp'))throw Error('ENOSPC');return real.promises.writeFile(file,...a)}}}}});await h.submit(req({query:'saved'}),new Res(),s);await tick();await s.contextLock;await h.shutdownHub(undefined,ss);const restored=await h.createSession(ss,{makeBridge:o=>{const b=new Bridge(o);if(first){first=false;b.ready=async()=>{started();await gate}}return b}},e.dir,{id:s.id,title:'saved',startedAt:1,replay:[]});const restoring=restored._ensureBridge().catch(e=>e);await ready;fail=true;let error;try{await h.archiveSession(req({id:s.id}),new Res(),ss)}catch(e){error=e}assert(error&&!restored._closing&&!restored._closed&&await restoring,'archive failure stranded session');fail=false;await restored._ensureBridge();release();await tick();assert(restored.bridge.messages.length===1&&ss.get(s.id)===restored,'retry lost live session');
});
await check('W03 duplicate legacy queries receive distinct positional IDs',async()=>{
 const {h,s}=await create();s.bridge.messages=[{role:'user',content:'same'},{role:'assistant',content:'answer'},{role:'user',content:'same'}];await s.capture.flush();const ids=s.store.buildBranchWithIds().entryIds;s.replay=[`id: 1\ndata: ${JSON.stringify({meta:{name:'agent:query'},payload:{query:'same'}})}\n\n`,`id: 2\ndata: ${JSON.stringify({meta:{name:'agent:query'},payload:{query:'same',entryId:ids[2]}})}\n\n`];assert(h.migrateLegacyQueryTags(s),'legacy sequence not migrated');assert(frame(s.replay[0]).payload.entryId===ids[0]&&frame(s.replay[1]).payload.entryId===ids[2],'duplicate matched wrong entry');assert(!h.migrateLegacyQueryTags(s),'migration not idempotent');
});
await check('W03 ambiguous or conflicting legacy replay is not rewritten',async()=>{
 const {h,s}=await create();s.bridge.messages=[{role:'user',content:'same'},{role:'user',content:'same'}];await s.capture.flush();const ids=s.store.buildBranchWithIds().entryIds;const mk=payload=>`data: ${JSON.stringify({meta:{name:'agent:query'},payload})}\n\n`;for(const frames of [[mk({query:'same'})],[mk({query:'same'}),mk({query:'same',entryId:ids[0]})],[mk({query:'different'}),mk({query:'same'})]]){s.replay=frames;const before=s.replay.join('');assert(!h.migrateLegacyQueryTags(s)&&s.replay.join('')===before,'ambiguous history retagged');}
});
await check('W04 genuinely missing replay still recovers from tree',async()=>{
 const {e,h,s,ss}=await create();await h.submit(req({query:'tree survives'}),new Res(),s);await tick();await s.contextLock;await h.shutdownHub(undefined,ss);fs.rmSync(path.join(e.dir,'hub-sessions',s.id+'.replay.jsonl'));const restored=await h.createSession(ss,{makeBridge:o=>new Bridge(o)},e.dir,{id:s.id,title:'saved',startedAt:1,replay:[]});await restored._ensureBridge();assert(restored.bridge.messages.length===1&&restored.replay.some(f=>f.includes('tree survives')),'ENOENT recovery disabled');
});
await check('W05 GET response from pending write stays stale after PUT completion',async()=>{
 const {u,select,refresh}=modelUi();let save,read;const saveGate=new Promise(r=>save=r),readGate=new Promise(r=>read=r);u.e.context.fetch=async(url,opts)=>opts?.method==='PUT'?saveGate:readGate;select.value='new';select.dispatchEvent({type:'change'});refresh();save({ok:true});await tick();read({ok:true,json:async()=>({models:{implement:'old'}})});await tick();assert(select.value==='new'&&!select._modelSaving,'late GET reset saved model');u.e.context.fetch=async()=>({ok:true,json:async()=>({models:{implement:'confirmed'}})});refresh();await tick();assert(select.value==='confirmed','next normal refresh broken');
});
function mainModelUi(){const u=ui(),session={id:'aaaaaa',agentInfo:{model:'old',provider:'test',modalities:['image']}};u.active.value=session;Object.assign(u.e.context,{refreshModelChip(){},BALANCE_PROVIDERS:new Set(),toast:(...a)=>u.toasts.push(a),t:x=>x,activeSession:u.active});return{u,session,select:variable('web/js/sse.js','selectModel',u.e.context)}}
await check('W06 successful model switch updates after HTTP confirmation',async()=>{
 const {u,session,select}=mainModelUi();let release;u.e.context.fetch=()=>new Promise(r=>release=r);const changing=select(session,'new','test');assert(session.agentInfo.model==='old','unconfirmed model displayed');release({ok:true});await changing;assert(session.agentInfo.model==='new'&&session.agentInfo.modalities===undefined&&u.toasts.length===0,'success not displayed');
});
await check('W06 stale failure cannot overwrite newer success',async()=>{
 const {u,session,select}=mainModelUi(),pending=[];u.e.context.fetch=()=>new Promise(r=>pending.push(r));const a=select(session,'first','test'),b=select(session,'second','test');pending[1]({ok:true});await b;pending[0]({ok:false,status:500});await a;assert(session.agentInfo.model==='second'&&u.toasts.length===0,'stale failure changed newest selection');
});
await check('W06 successful HTTP response retains earlier SSE capabilities',async()=>{
 const {u,session,select}=mainModelUi();let release;u.e.context.fetch=()=>new Promise(r=>release=r);const p=select(session,'new','test');session.agentInfo={model:'new',provider:'test',modalities:['image']};release({ok:true});await p;assert(session.agentInfo.modalities[0]==='image','confirmed SSE capabilities cleared');
});
await check('W06 backend async model-switch errors become HTTP errors',async()=>{
 const {h,s}=await create();s.bridge.execCommand=async()=>{throw Error('switch failed')};const r=new Res();await h.setModelEndpoint(req({model:'new'}),r,s);assert(r.statusCode===500&&r.body.includes('switch failed'),'async failure returned success');
});
await check('W08 newer edit to same budget field prevents obsolete rollback',async()=>{
 const u=ui(),card=new El();card.dataset.type='implement';let release,writes=0,value=90000;const gate=new Promise(r=>release=r);Object.assign(u.e.context,{saBudgetSeq:0,currentSessionId:()=> 'aaaaaa',toast(){},t:x=>x,fetch:async(url,opts)=>opts?.method==='PUT'?{ok:++writes>1,status:500}:gate});const commit=variable('web/js/subagent-panel.js','commitBudgetField',u.e.context);commit(card,'budgetTokens',90000,c=>value=c.budgetTokens);await tick();value=50000;commit(card,'budgetTokens',50000,c=>value=c.budgetTokens);await tick();release({ok:true,json:async()=>[{type:'implement',budgetTokens:40000}]});await tick();assert(value===50000,'old failure undid newer edit');
});
await check('W03 legacy full replay can map entries predating compaction',async()=>{
 const {h,s}=await create();s.bridge.messages=[{role:'user',content:'first'},{role:'assistant',content:'answer'},{role:'user',content:'second'}];await s.capture.flush();const ids=s.store.buildBranchWithIds().entryIds;await s.store.appendCompaction(ids[2]);s.replay=['first','second'].map(query=>`data: ${JSON.stringify({meta:{name:'agent:query'},payload:{query}})}\n\n`);assert(h.migrateLegacyQueryTags(s),'pre-compaction history not migrated');assert(frame(s.replay[0]).payload.entryId===ids[0]&&frame(s.replay[1]).payload.entryId===ids[2],'pre-compaction IDs wrong');
});
clearTimeout(watchdog);console.log(JSON.stringify({checks:findings.length,passed:findings.filter(f=>f.passed).length,failed:findings.filter(f=>!f.passed).length}));if(findings.some(f=>!f.passed))process.exitCode=1;
})().catch(e=>{clearTimeout(watchdog);console.error(e);process.exitCode=1});
